# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://visual_effects/fog_viewport.gd"

var _player_fog_mult: Array = []


# Mole (Gourmet DLC): shrink the visible vision circle so the fog actually bites.
# 0.5 = 50% smaller radius than the default fog. Non-Mole players stay at 1.0.
const MOLE_FOG_VISIBILITY_MULT: float = 0.5







func _change_fog_size(_wave):
	var _fog_size_scale = 1.0
	if _wave > 20:
		_wave = 20
	_fog_size_scale = 2.75 - 1.75 * (_wave / 20.0)
	_wave_fog_scale = _fog_size_scale
	for i in range(RunData.get_player_count()):
		_player_bonus.push_back(RunData.get_player_effect(Keys.stat_fog_visibility_hash, i) / 100.0)
		var _fog_mult = 1.0
		var _char = RunData.get_player_character(i)
		if _char != null and _char.my_id == "character_mole":
			_fog_mult = MOLE_FOG_VISIBILITY_MULT
		_player_fog_mult.push_back(_fog_mult)
		player_lights[i].scale = Vector2.ONE * (1.0 + _player_bonus[i]) * _fog_mult





func _process(_delta):
	fog_sprite.scale = _base_fog_scale * _wave_fog_scale * camera.zoom.x
	var scale_factor = fog_sprite.scale.x
	fog_sprite.global_position = camera.global_position
	for light_index in player_lights.size():
		if (player_lights[light_index] == null):
			continue
		player_lights[light_index].scale = Vector2.ONE * (1.0 + _player_bonus[light_index]) * _player_fog_mult[light_index] / camera.zoom.x
		player_lights[light_index].global_position = (main._players[light_index].global_position - camera.global_position) / scale_factor + (size / 2)
		if (main._players[light_index].dead):
			var instance_to_free = player_lights[light_index]
			remove_child(instance_to_free)
			instance_to_free.queue_free()
			player_lights[light_index] = null
	for particle in fire_lights:
		fire_lights[particle].scale = Vector2.ONE / camera.zoom.x
		fire_lights[particle].global_position = (particle.global_position - camera.global_position) / scale_factor + (size / 2)
	for entity in structure_and_pet_lights:
		structure_and_pet_lights[entity].scale = Vector2.ONE / camera.zoom.x
		structure_and_pet_lights[entity].global_position = (entity.global_position - camera.global_position) / scale_factor + (size / 2)
	for entity in explosion_lights:
		explosion_lights[entity].scale = Vector2.ONE / camera.zoom.x
		explosion_lights[entity].global_position = (entity.global_position - camera.global_position) / scale_factor + (size / 2)
