# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://entities/units/enemies/enemy.gd"




func init(zone_min_pos: Vector2, zone_max_pos: Vector2, p_players_ref: Array = [], entity_spawner_ref = null) -> void :
	.init(zone_min_pos, zone_max_pos, p_players_ref, entity_spawner_ref)
	init_current_stats()
	init_effect_behaviors()
	var factor = RunData.sum_all_player_effects(Keys.stronger_loot_aliens_on_kill_hash)
	if is_loot and factor > 0:
		var bonus_health = factor * RunData.loot_aliens_killed_this_run
		reset_health_stat(bonus_health)
	if DebugService.nullify_enemy_speed:
		stats.speed = - 1000
		current_stats.speed = - 1000
	# Gourmet DLC - debt scaling used to be applied here, multiplying max_stats/current_stats
	# after init. That was wrong: reset_health_stat / reset_damage_stat recompute from
	# stats.get_base_health(), and elites (boost_args), bosses, respawns and the DLC lungs all
	# call them AFTER this point - so the scaling was thrown away on exactly the enemies it
	# mattered most on. It now lives in EntityService.get_final_enemy_health / _damage, which
	# every one of those paths goes through.
	_hitbox.connect("hit_something", self, "_on_hit_something")
	_hitbox.damage = current_stats.damage
	_attack_behavior.init(self)
	update_target()
