# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/run/character_selection.gd"

	


func _go_back() -> void :
	RunData.reload_music = false
	# Gourmet ecosystem - back returns to wherever the run flow started:
	# the Hub if its booth/shuttle led here, the title screen otherwise
	if MenuData.run_flow_from_lobby:
		MenuData.run_flow_from_lobby = false
		MenuData.character_select_for_lobby = false
		var _error = get_tree().change_scene(MenuData.lobby_scene)
	else:
		var _error = get_tree().change_scene(MenuData.title_screen_scene)
	ProgressData.end_activity(false)


		



func _on_selections_completed() -> void :
	# Gourmet ecosystem - the Hub's changing booth (HUB_PLAN flow law): store
	# the picks as the hub characters (= last played, persisted) and walk back
	# out. The run does NOT start here; the shuttle reads this state later.
	# Coop joins made on this screen persist in RunData play state.
	if MenuData.character_select_for_lobby:
		MenuData.character_select_for_lobby = false
		MenuData.run_flow_from_lobby = false
		var lobby_last_played: Array = ProgressData.settings.get("last_played_characters", ["", "", "", ""])
		for player_index in RunData.get_player_count():
			if player_index < lobby_last_played.size() and _player_characters[player_index] != null:
				lobby_last_played[player_index] = str(_player_characters[player_index].my_id)
		ProgressData.settings.last_played_characters = lobby_last_played
		ProgressData.save_settings()
		RunData.revert_all_selections()
		_change_scene(MenuData.lobby_scene)
		return
	if (ProgressData.settings.zone_is_random):
		_setup_zone(ProgressData.settings.zone_selected)
	for player_index in RunData.get_player_count():
		var character = _player_characters[player_index]
		RunData.add_character(character, player_index)
	if Utils.on_nintendo_nx_or_ounce and RunData.is_coop_run:
		OS.set_max_controller_count(RunData.get_player_count())
	if RunData.some_player_has_weapon_slots():
		_change_scene(MenuData.weapon_selection_scene)
	else:
		RunData.add_starting_items_and_weapons()
		_change_scene(MenuData.difficulty_selection_scene)
