# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/run/weapon_selection.gd"






func _go_back() -> void :
	for player_index in RunData.get_player_count():
		var character = RunData.get_player_character(player_index)
		Utils.last_elt_selected[player_index] = character
		RunData.remove_character(character, player_index)
	RunData.revert_all_selections()
	# Gourmet ecosystem - a flow begun at the Hub's shuttle backs out to the
	# Hub, not into character select (HUB_PLAN flow law)
	if MenuData.run_flow_from_lobby:
		MenuData.run_flow_from_lobby = false
		RunData.menu_selection_back = false
		_change_scene(MenuData.lobby_scene)
		return
	RunData.menu_selection_back = true
	_change_scene(MenuData.character_selection_scene)
