# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/hud/player_ui_elements.gd"



func update_hud(player: Player) -> void :
	if RunData.is_coop_run:
		life_bar.self_modulate.a = 0.75
		xp_bar.self_modulate.a = 0.75
		var player_color = CoopService.get_player_color(player_index)
		gold.gold_label.add_color_override("font_color", player_color)
		gold.icon.modulate = player_color
	life_bar.update_value(player.current_stats.health, player.max_stats.health)
	var die_in_one_hit = RunData.get_player_effect(Keys.die_in_one_hit_hash, player_index)
	if die_in_one_hit == 1:
		hide_life_label(player)
	else:
		update_life_label(player)
	var hit_protection_count = player._hit_protection
	update_hit_protection_count(player, hit_protection_count)
	xp_bar.update_value(int(RunData.get_player_xp(player_index)), int(RunData.get_next_level_xp_needed(player_index)))
	update_level_label()
	gold.update_value(RunData.get_player_gold(player_index))
	gold.update_debt(RunData.get_player_debt(player_index))  # Gourmet DLC - debt readout
