# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/pages/main_menu.gd"

	

	



	


func init() -> void :
	if Streamplay.playing():
		Streamplay.stop()
		RunData.reset()
	if not has_node("%HubButton") and start_button.get_parent().find_node("HubButton", false, false) == null:
		_add_hub_button()
	more_games_button.text = "MENU_DLC_AVAILABLE_STANDARD"
	more_games_button.add_color_override("font_color", Utils.DLC_BUTTON_TEXT_COLOR)
	more_games_button.theme = load("res://resources/themes/special_button_theme.tres")
	for dlc in ProgressData.available_dlcs:
		if dlc.my_id == "abyssal_terrors":
			more_games_button.text = "MENU_MORE_GAMES"
			more_games_button.remove_color_override("font_color")
			more_games_button.theme = null
			break
	reset_resume_state()
	setup_menu()
	if Utils.is_on_console():
		var newVersion = ProgressData.VERSION
		if Utils.on_nintendo_nx_or_ounce:
			newVersion = ProgressData.VERSION_SWITCH
		var newPos = newVersion.find("-")
		if newPos >= 0:
			newVersion = newVersion.substr(0, newPos)
		version_label.text = "version " + newVersion
		if Utils.on_gdk:
			xbox_gamertag.text = OS_Seaven.get_gamertag()
			xbox_gamertag.show()
		else:
			xbox_gamertag.hide()
	else:
		version_label.text = "version " + ProgressData.VERSION
	if not Utils.is_on_console() and ProgressData.load_status != LoadStatus.SAVE_OK:
		var status_text = "(!) "
		if ProgressData.load_status == LoadStatus.CORRUPTED_SAVE:
			status_text += tr("CORRUPTED_SAVE")
		elif ProgressData.load_status == LoadStatus.CORRUPTED_SAVE_LATEST:
			status_text += tr("CORRUPTED_SAVE_LATEST")
		elif ProgressData.load_status == LoadStatus.CORRUPTED_ALL_SAVES_STEAM:
			status_text += tr("CORRUPTED_ALL_SAVES_STEAM")
		elif ProgressData.load_status == LoadStatus.CORRUPTED_ALL_SAVES_NO_STEAM:
			status_text += tr("CORRUPTED_ALL_SAVES_NO_STEAM")
		elif ProgressData.load_status == LoadStatus.CORRUPTED_ALL_SAVES_EPIC:
			status_text += tr("CORRUPTED_ALL_SAVES_EPIC")
		elif ProgressData.load_status == LoadStatus.CORRUPTED_ALL_SAVES_NO_EPIC:
			status_text += tr("CORRUPTED_ALL_SAVES_NO_EPIC")
		elif ProgressData.load_status == LoadStatus.CORRUPTED_RUN_SAVE:
			status_text += tr("CORRUPTED_RUN_SAVE")
		error_label.text = status_text
		error_label.show()
	elif not Utils.is_on_console() and not CrashReporter.previous_crash_message.empty():
		var error_text = "(!) "
		if CrashReporter.previous_crashed_mod.empty():
			error_text += "%s %s" % [
				tr("CRASH_RECOVERY_MESSAGE_GENERAL"), 
				tr("CRASH_RECOVERY_MESSAGE_MODS_DISABLED")
			]
		else:
			error_text += "%s %s" % [
				tr("CRASH_RECOVERY_MESSAGE_MOD").replace("{0}", CrashReporter.previous_crashed_mod), 
				tr("CRASH_RECOVERY_MESSAGE_MODS_DISABLED")
			]
		error_label.text = error_text
		error_label.show()
	else:
		error_label.hide()
	var act = ProgressData.get_pending_activity()
	testActivity(act)



# Gourmet ecosystem - the Hub is its own main-menu destination (user 2026-08-18:
# an ALTERNATE place beside the normal flow, never inside the Start path). The
# button is cloned from Start at runtime so theme/focus styling always matches.
func _add_hub_button() -> void :
	var hub_button: Button = start_button.duplicate()
	hub_button.name = "HubButton"
	hub_button.text = tr("LOBBY_HUB")
	for connection in hub_button.get_signal_connection_list("pressed"):
		hub_button.disconnect("pressed", connection.target, connection.method)
	var _e = hub_button.connect("pressed", self, "_on_HubButton_pressed")
	start_button.get_parent().add_child(hub_button)
	start_button.get_parent().move_child(hub_button, start_button.get_index() + 1)



func _on_HubButton_pressed() -> void :
	MusicManager.tween( - 5)
	var _error = get_tree().change_scene(MenuData.lobby_scene)
