# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/pages/menu_options.gd"








func init_values_from_progress_data() -> void :
	mouse_only_button.pressed = ProgressData.settings.mouse_only
	manual_aim_button.pressed = ProgressData.settings.manual_aim
	manual_aim_on_mouse_press_button.pressed = ProgressData.settings.manual_aim_on_mouse_press
	movement_with_gamepad.pressed = ProgressData.settings.movement_with_gamepad
	hp_bar_button.pressed = ProgressData.settings.hp_bar_on_character
	boss_hp_bar_button.pressed = ProgressData.settings.hp_bar_on_bosses
	keep_lock_button.pressed = ProgressData.settings.keep_lock
	lock_coop_camera_button.pressed = ProgressData.settings.lock_coop_camera
	score_storing_button.select(ProgressData.settings.endless_score_storing)
	enemy_health_slider.set_value(ProgressData.settings.enemy_scaling.health)
	enemy_damage_slider.set_value(ProgressData.settings.enemy_scaling.damage)
	enemy_speed_slider.set_value(ProgressData.settings.enemy_scaling.speed)
	constant_projectile_button.select(ProgressData.settings.constant_projectile_option)
	explosion_opacity_slider.set_value(ProgressData.settings.explosion_opacity)
	projectile_opacity_slider.set_value(ProgressData.settings.projectile_opacity)
	pet_opacity_slider.set_value(ProgressData.settings.pet_opacity)
	effects_icons_description_button.pressed = ProgressData.settings.effects_icons_in_description
	font_size_slider.set_value(ProgressData.settings.font_size)
	color_positive._init_color(Color(ProgressData.settings.color_positive))
	color_negative._init_color(Color(ProgressData.settings.color_negative))
	color_tier0._init_color(Color(ProgressData.settings.tier_0_color))
	color_tier1._init_color(Color(ProgressData.settings.tier_1_color))
	color_tier2._init_color(Color(ProgressData.settings.tier_2_color))
	color_tier3._init_color(Color(ProgressData.settings.tier_3_color))
	color_tier4._init_color(Color(ProgressData.settings.tier_4_color))
	color_tier5._init_color(Color(ProgressData.settings.tier_5_color))
	character_highlighting_button.pressed = ProgressData.settings.character_highlighting
	weapon_highlighting_button.pressed = ProgressData.settings.weapon_highlighting
	projectile_highlighting_button.pressed = ProgressData.settings.projectile_highlighting
	turret_highlighting_button.pressed = ProgressData.settings.turret_highlighting
	pet_highlighting_button.pressed = ProgressData.settings.pet_highlighting
	gold_sounds_button.pressed = ProgressData.settings.alt_gold_sounds
	darken_screen_button.pressed = ProgressData.settings.darken_screen
	retry_wave_button.pressed = ProgressData.settings.retry_wave
	share_coop_loot_button.pressed = ProgressData.settings.share_coop_loot
	no_item_appearance.pressed = ProgressData.settings.no_item_appearance
	holding_button.pressed = ProgressData.settings.holding_button
	if not ProgressData.is_dlc_available("abyssal_terrors"):
		abyssal_terrors_dlc_button.hide()
	abyssal_terrors_dlc_button.set_pressed_no_signal( not ProgressData.settings.deactivated_dlcs.has("abyssal_terrors"))
	_init_pack_toggles()
	if not SkinManager.is_skin_set_available("green"):
		green_skins_button.hide()
	green_skins_button.set_pressed_no_signal( not ProgressData.settings.deactivated_skin_sets.has("green"))



# Gourmet ecosystem - one CheckButton per pack, generated beside the DLC toggle
# (same opt-out semantics). Title-screen only: toggling packs mid-run is
# unsupported, so the buttons are disabled anywhere but the title screen.
# Continue-safety lives in ProgressData.check_dlc_valid_for_saved_run_state.
var _pack_buttons: = {}

func _init_pack_toggles() -> void :
	var packs_allowed: bool = get_tree().current_scene != null and get_tree().current_scene.name == "TitleScreen"
	if _pack_buttons.empty():
		var packs_parent = abyssal_terrors_dlc_button.get_parent()
		var insert_index: int = abyssal_terrors_dlc_button.get_index() + 1
		for pack_id in Packs.available_packs:
			var pack_button: = CheckButton.new()
			pack_button.text = str(Packs.available_packs[pack_id].display_name) + " pack"
			pack_button.connect("toggled", self, "_on_pack_toggled", [pack_id])
			packs_parent.add_child(pack_button)
			packs_parent.move_child(pack_button, insert_index)
			insert_index += 1
			_pack_buttons[pack_id] = pack_button
	for pack_id in _pack_buttons:
		_pack_buttons[pack_id].set_pressed_no_signal(Packs.is_pack_enabled(pack_id))
		_pack_buttons[pack_id].disabled = not packs_allowed



func _on_pack_toggled(button_pressed: bool, pack_id: String) -> void :
	if button_pressed:
		Packs.activate_pack(pack_id)
	else:
		Packs.deactivate_pack(pack_id)
