# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/pages/menu_codex.gd"




func _pop():
	unlocked_items = 0
	unlocked_weapons = 0
	unlocked_entities = 0
	focus_before_created = get_focus_owner()
	popup()
	if RunData.is_coop_run:
		Utils._popup = self
	animation_tree.set("parameters/conditions/finish", false)
	animation_tree.active = true
	tab_challenge.set_elements(true)
	lb_texture.player_index = player_index
	rb_texture.player_index = player_index
	_focus_control($"%but_tab_challenger")
	var list_of_items: Array = ItemService.items.duplicate()
	list_of_items.sort_custom(SortItem, "sort_by_tier")
	for item in list_of_items:
		if ProgressData.items_unlocked.has(item.my_id_hash):
			item.is_locked = false
		else:
			item.is_locked = true
		if ProgressData.items_bought.has(item.my_id_hash):
			unlocked_items += 1
	inventory_items.set_elements(list_of_items)
	inventory_items.on_element_focused(inventory_items.get_child(0))
	var list_of_weapons: Array = ItemService.weapons.duplicate()
	list_of_weapons.sort_custom(SortItem, "sort_by_tier")
	var list_to_remove: Array
	for weapon in list_of_weapons:
		if ProgressData.weapons_unlocked.has(weapon.weapon_id_hash):
			weapon.is_locked = false
		else:
			weapon.is_locked = true
		if weapon.previous_upgrade != null:
			list_to_remove.append(weapon)
		elif ProgressData.items_bought.has(weapon.my_id_hash):
			unlocked_weapons += 1
	for weapon in list_to_remove:
		list_of_weapons.erase(weapon)
	inventory_weapons.set_elements(list_of_weapons)
	inventory_weapons.on_element_focused(inventory_weapons.get_child(0))
	_change_color_tier_button(but_tier0, Tier.COMMON)
	_change_color_tier_button(but_tier1, Tier.UNCOMMON)
	_change_color_tier_button(but_tier2, Tier.RARE)
	_change_color_tier_button(but_tier3, Tier.LEGENDARY)
	var list_of_entities: Array = ItemService.entities.duplicate()
	var list_of_entities_id: Array = []
	for entity in list_of_entities:
		if entity._get_how_many_killed() > 0:
			unlocked_entities += 1
		if list_of_entities_id.has(entity.my_id_hash):
			list_of_entities.erase(entity)
		else:
			list_of_entities_id.append(entity.my_id_hash)
	inventory_enemies.set_elements(list_of_entities)
	inventory_enemies.on_element_focused(inventory_enemies.get_child(0))
	_unlockall_icon.visible = ProgressData.is_unlock_all_save()



class SortItem:
	static func tier_rank(t: int) -> int:
		# Gourmet DLC - sort along the rarity LADDER (gray, green, blue, teal,
		# purple, red, pink, gold), not by raw tier int: the modded tiers are
		# 7-10 and would otherwise all clump after the vanilla 0-3
		var ladder_order: Dictionary = {0: 0, 7: 1, 1: 2, 8: 3, 2: 4, 3: 5, 9: 6, 10: 7}
		return int(ladder_order.get(t, t + 20))
	static func sort_by_tier(a, b):
		if tier_rank(a.tier) < tier_rank(b.tier):
			return true
		return false
