# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/pages/sort_inventory_button.gd"








func _sort_inventory(index: int = - 10, _inventory: Inventory = null):
	var elements: Array = inventory_to_sort.get_children()
	if index == - 10:
		index = selected
	var sort_type = get_item_id(index)
	var sortingType: String
	var other_type_of_sorting: bool = false
	match sort_type:
		SortingType.BYNAME:
			sortingType = "sort_by_name"
		SortingType.BYTIERS:
			sortingType = "sort_by_tier"
		SortingType.HOWMANYOBTAINED:
			sortingType = "sort_by_time_got_it"
		SortingType.HOWMANYKILLED:
			sortingType = "sort_by_killed"
		SortingType.BYSTRENGHT:
			sortingType = "sort_by_strenght"
		SortingType.BYHP:
			sortingType = "sort_by_hp"
		SortingType.BYCATEGORY:
			sortingType = "sort_by_category"
		SortingType.BYTIMEADDITIONTOINVENTORY:
			other_type_of_sorting = true
			elements = inventory_to_sort.order_of_addition.duplicate()
		SortingType.BYWEAPONDAMAGE:
			sortingType = "sort_by_damage"
		SortingType.BYWEAPONRELOADTIME:
			sortingType = "sort_by_reload_time"
		SortingType.BYWEAPONRANGE:
			sortingType = "sort_by_range"
		SortingType.BYENTITYTYPE:
			sortingType = "sort_by_entity_type"
	if not other_type_of_sorting:
		elements.sort_custom(SortInventory, sortingType)
	if reverse_order:
		elements.invert()
	for slot in inventory_to_sort.get_children():
		inventory_to_sort.remove_child(slot)
	for slot in elements:
		if not is_instance_valid(slot):
			continue
		inventory_to_sort.add_child(slot)
	inventory_to_sort.__set_focus_neighbours()









class SortInventory:
	static func sort_by_name(a, b):
		if compare_loca_names(a.item.name, b.item.name):
			return true
		return false
	static func compare_loca_names(name_a, name_b):
		return TranslationServer.translate(name_a) < TranslationServer.translate(name_b)
	static func tier_rank(t: int) -> int:
		# Gourmet DLC - sort along the rarity LADDER (gray, green, blue, teal,
		# purple, red, pink, gold), not by raw tier int: the modded tiers are
		# 7-10 and would otherwise all clump after the vanilla 0-3
		var ladder_order: Dictionary = {0: 0, 7: 1, 1: 2, 8: 3, 2: 4, 3: 5, 9: 6, 10: 7}
		return int(ladder_order.get(t, t + 20))
	static func sort_by_tier(a, b):
		if tier_rank(a.item.tier) < tier_rank(b.item.tier):
			return true
		elif tier_rank(a.item.tier) == tier_rank(b.item.tier):
			if a.item.name < b.item.name:
				return true
		return false
	static func sort_by_time_got_it(a, b):
		var a_quantity = a.item._get_bought_times()
		var b_quantity = b.item._get_bought_times()
		if a_quantity > b_quantity:
			return true
		elif a_quantity == b_quantity:
			if tier_rank(a.item.tier) < tier_rank(b.item.tier):
				return true
			elif tier_rank(a.item.tier) == tier_rank(b.item.tier):
				if a.item.name < b.item.name:
					return true
		return false
	static func sort_by_killed(a, b):
		var a_quantity = a.item._get_how_many_killed()
		var b_quantity = b.item._get_how_many_killed()
		if a_quantity > b_quantity:
			return true
		elif a_quantity == b_quantity:
			if tier_rank(a.item.tier) < tier_rank(b.item.tier):
				return true
			elif tier_rank(a.item.tier) == tier_rank(b.item.tier):
				if a.item.name < b.item.name:
					return true
		return false
	static func sort_by_strenght(a, b):
		if a.item.stats is Stats and b.item.stats is Stats:
			var damage_a = a.item.stats.damage + (a.item.stats.damage_increase_each_wave * 20) if a.item.stats != null else 0
			var damage_b = b.item.stats.damage + (b.item.stats.damage_increase_each_wave * 20) if b.item.stats != null else 0
			if damage_a < damage_b:
				return true
			elif damage_a == damage_b:
				if a.item.name < b.item.name:
					return true
			return false
		elif ( not (a.item.stats is Stats)) and ( not (b.item.stats is Stats)):
			if a.item.name < b.item.name:
				return true
			else:
				return false
		elif ( not (a.item.stats is Stats)) and (b.item.stats is Stats):
			return true
		elif (a.item.stats is Stats) and ( not (b.item.stats is Stats)):
			return false
	static func sort_by_hp(a, b):
		if a.item.stats is Stats and b.item.stats is Stats:
			var hp_a = a.item.stats.health + (a.item.stats.health_increase_each_wave * 20) if a.item.stats != null else 0
			var hp_b = b.item.stats.health + (b.item.stats.health_increase_each_wave * 20) if b.item.stats != null else 0
			if hp_a < hp_b:
				return true
			elif hp_a == hp_b:
				if a.item.name < b.item.name:
					return true
			return false
		elif ( not (a.item.stats is Stats)) and ( not (b.item.stats is Stats)):
			if a.item.name < b.item.name:
				return true
			else:
				return false
		elif ( not (a.item.stats is Stats)) and (b.item.stats is Stats):
			return true
		elif (a.item.stats is Stats) and ( not (b.item.stats is Stats)):
			return false
	static func sort_by_category(a, b):
		if a.item.sets[0].name < b.item.sets[0].name:
			return true
		elif a.item.sets[0].name == b.item.sets[0].name:
			if a.item.name < b.item.name:
				return true
		return false
	static func sort_by_damage(a, b):
		if a.item.stats.damage > b.item.stats.damage:
			return true
		elif a.item.stats.damage == b.item.stats.damage:
			if a.item.name < b.item.name:
				return true
		return false
	static func sort_by_reload_time(a, b):
		if a.item.stats.cooldown < b.item.stats.cooldown:
			return true
		elif a.item.stats.cooldown == b.item.stats.cooldown:
			if a.item.name < b.item.name:
				return true
		return false
	static func sort_by_range(a, b):
		if (a.item.stats.min_range + a.item.stats.max_range) < (b.item.stats.min_range + b.item.stats.max_range):
			return true
		elif (a.item.stats.min_range + a.item.stats.max_range) == (b.item.stats.min_range + b.item.stats.max_range):
			if a.item.name < b.item.name:
				return true
		return false
	static func sort_by_entity_type(a, b):
		var item_a = a.item
		var item_b = b.item
		var rank_a = get_rank(item_a)
		var rank_b = get_rank(item_b)
		if rank_a != rank_b:
			return rank_a < rank_b
		return compare_names(item_a.name, item_b.name)
	static func get_rank(item):
		if item is ItemPet:
			return 0
		if item.is_boss:
			return 3
		if item.is_elite:
			return 2
		return 1
	static func compare_names(name_a, name_b):
		var group_a = get_group_name(name_a)
		var group_b = get_group_name(name_b)
		if group_a != group_b:
			return group_a < group_b
		if name_a.length() != name_b.length():
			return name_a.length() < name_b.length()
		return name_a < name_b
	static func get_group_name(name):
		var parts = name.split("_")
		if parts.size() >= 2:
			return parts[parts.size() - 2] + "_" + parts[parts.size() - 1]
		return name
