# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://entities/units/enemies/attack_behaviors/shooting_attack_behavior.gd"


		
		
		
		
		











func get_cd() -> float:
	# Gourmet DLC - enemy_attack_speed effect (Tourist per Danger, Mime +15%):
	# positive values make enemies attack faster by shrinking their cooldowns
	var attack_speed_factor: float = 100.0 / (100.0 + RunData.sum_all_player_effects(Keys.enemy_attack_speed_hash))
	if long_cooldown_every_x_shoots != 0 and _shots_taken >= long_cooldown_every_x_shoots:
		_shots_taken = 0
		emit_signal("entered_long_cooldown")
		return long_cooldown * attack_speed_factor
	return rand_range(max(1, cooldown - max_cd_randomization), cooldown + max_cd_randomization) * attack_speed_factor
