# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://entities/units/movement_behaviors/follow_target_movement_behavior.gd"




func get_target_position():
	if not is_instance_valid(_parent.current_target):
		return global_position
	# Gourmet DLC - get_follow_target_position is a Unit-only method this mod adds, so
	# that chasers path to Sweet Potato's FROZEN position during her panic-teleport
	# instead of snapping to where she reappeared. Vanilla, though, legitimately parks
	# current_target on a TargetBehavior node as a "no valid target" sentinel - the
	# Lootworm with no trees and no gold left (lootworm_target_behavior.gd), and
	# PlayerOwner once its owner is dead. Those are plain Node2Ds with no such method,
	# and calling it on them hard-crashes the run. Fall back to vanilla's global_position.
	if _parent.current_target.has_method("get_follow_target_position"):
		return _parent.current_target.get_follow_target_position()
	return _parent.current_target.global_position
