# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://entities/units/movement_behaviors/follow_rand_pos_around_player_movement_behavior.gd"





func get_target_position():
	# Gourmet DLC - same Unit-only guard as follow_target_movement_behavior: current_target
	# can be a TargetBehavior sentinel node, which has no get_follow_target_position.
	if _parent.current_target.has_method("get_follow_target_position"):
		return _parent.current_target.get_follow_target_position() + _distance_from_player
	return _parent.current_target.global_position + _distance_from_player
