extends Node

# GourmetCore mod entry (GENERATED by asset-dev/build_workshop.py - DO NOT EDIT)
#
# 1. installs a script extension for every vanilla .gd the ecosystem modifies
#    (generated from a per-function diff against the pristine 1.1.15.4 tree)
# 2. root-injects the 5 custom services as runtime pseudo-autoloads
#    (project.godot cannot be patched by a mod). Node names MUST match the
#    live-tree autoload names: Utils.packs & co resolve /root/<Name> in both
#    worlds.
# 3. registers the "interact" input action (lobby NPCs) via InputMap.
#
# ONLY ModLoaderMod.install_script_extension works on autoload scripts - the
# deprecated ModLoader.install_script_extension shim silently no-ops there
# (probe-proven 2026-08-18).

const LOG_NAME = "nicolassut-GourmetCore"
const EXT_ROOT = "res://mods-unpacked/nicolassut-GourmetCore/extensions/"

const SERVICES = [
	["GourmetTracker", "res://singletons/gourmet_tracker.gd"],
	["ButcherSkin", "res://singletons/butcher_skin.gd"],
	["SpecialModifiers", "res://singletons/special_modifiers.gd"],
	["Packs", "res://singletons/pack_service.gd"],
	["GameModes", "res://singletons/game_mode_service.gd"],
]

const EXTENSIONS = [
	"challenges/global/challenge_data.gd",
	"effects/consumables/consumable_healing_effect.gd",
	"entities/structures/structure.gd",
	"entities/structures/turret/garden/garden.gd",
	"entities/units/enemies/attack_behaviors/shooting_attack_behavior.gd",
	"entities/units/enemies/enemy.gd",
	"entities/units/movement_behaviors/follow_rand_pos_around_player_movement_behavior.gd",
	"entities/units/movement_behaviors/follow_target_movement_behavior.gd",
	"entities/units/neutral/neutral.gd",
	"entities/units/player/player.gd",
	"entities/units/unit/unit.gd",
	"items/characters/character_data.gd",
	"items/consumables/consumable.gd",
	"items/difficulties/difficulty_data.gd",
	"items/global/effect.gd",
	"items/global/item_parent_data.gd",
	"items/global/weapon_data.gd",
	"items/upgrades/upgrade_data.gd",
	"main.gd",
	"singletons/announcement_manager.gd",
	"singletons/entity_service.gd",
	"singletons/item_service.gd",
	"singletons/item_service_get_shop_items_args.gd",
	"singletons/keys.gd",
	"singletons/linked_stats.gd",
	"singletons/menu_data.gd",
	"singletons/player_run_data.gd",
	"singletons/progress_data.gd",
	"singletons/progress_data_loader_v3.gd",
	"singletons/run_data.gd",
	"singletons/text.gd",
	"singletons/utils.gd",
	"singletons/weapon_service.gd",
	"ui/hud/player_ui_elements.gd",
	"ui/hud/ui_gold.gd",
	"ui/menus/global/popup_manager.gd",
	"ui/menus/ingame/character_panel_ui.gd",
	"ui/menus/ingame/upgrades_ui.gd",
	"ui/menus/ingame/upgrades_ui_player_container.gd",
	"ui/menus/pages/main_menu.gd",
	"ui/menus/pages/menu_codex.gd",
	"ui/menus/pages/menu_options.gd",
	"ui/menus/pages/sort_inventory_button.gd",
	"ui/menus/run/character_selection.gd",
	"ui/menus/run/difficulty_selection/difficulty_selection.gd",
	"ui/menus/run/run_options_panel.gd",
	"ui/menus/shop/base_shop.gd",
	"ui/menus/shop/button_with_icon.gd",
	"ui/menus/shop/coop_shop.gd",
	"ui/menus/shop/coop_shop_player_container.gd",
	"ui/menus/shop/item_description.gd",
	"ui/menus/shop/item_popup.gd",
	"ui/menus/shop/shop.gd",
	"ui/menus/shop/shop_item.gd",
	"ui/menus/shop/shop_items_container.gd",
	"ui/menus/shop/stats_container.gd",
	"ui/menus/shop/synergy_panel.gd",
	"visual_effects/fog_viewport.gd",
	"weapons/weapon.gd",
]


func _init(modLoader = ModLoader):
	ModLoaderUtils.log_info("Init", LOG_NAME)
	for ext in EXTENSIONS:
		ModLoaderMod.install_script_extension(EXT_ROOT.plus_file(ext))


func _ready():
	ModLoaderUtils.log_info("Ready", LOG_NAME)
	_register_interact_action()
	# IMMEDIATE add_child - call_deferred lands after the autoload phase, too
	# late (probe-proven 2026-08-18). The service NODES must exist at /root
	# before ProgressData._ready drives Packs.apply_at_boot; their own _ready
	# fires after every vanilla autoload's, same relative order as the live
	# tree where they are the last autoloads.
	var tree_root = get_tree().get_root()
	for svc in SERVICES:
		if tree_root.has_node(svc[0]):
			continue
		var node = load(svc[1]).new()
		node.name = svc[0]
		tree_root.add_child(node)


func _register_interact_action() -> void :
	# mirrors the live-tree project.godot action: E + gamepad button 3
	if InputMap.has_action("interact"):
		return
	InputMap.add_action("interact", 0.5)
	var key = InputEventKey.new()
	key.scancode = KEY_E
	InputMap.action_add_event("interact", key)
	var joy = InputEventJoypadButton.new()
	joy.button_index = 3
	InputMap.action_add_event("interact", joy)
