# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/ingame/character_panel_ui.gd"

	




func apply_items_appearance(all_items: Array) -> void :
	var character_node = $"%Character"
	for sprite in all_sprites_appearance:
		sprite.queue_free()
	all_sprites_appearance = []
	var allAppearances: Array = []
	for item in all_items:
		allAppearances.append_array(item.item_appearances)
	allAppearances.sort_custom(Sorter, "sort_depth_ascending")
	var appearances_behind = []
	for appearance in allAppearances:
		if ProgressData.settings.no_item_appearance and not appearance.is_character_appearance:
			continue
		var item_sprite = Sprite.new()
		all_sprites_appearance.append(item_sprite)
		item_sprite.texture = appearance.get_sprite()
		character_node.add_child(item_sprite)
		if appearance.depth < - 1:
			appearances_behind.push_back(item_sprite)
	var popped = appearances_behind.pop_back()
	while popped != null:
		character_node.move_child(popped, 0)
		popped = appearances_behind.pop_back()
	# tint the legs to match a recoloured body (green/brown characters)
	var legs_node = character_node.get_node_or_null("Legs")
	if legs_node and item_data is CharacterData and item_data.legs_modulate != Color(1, 1, 1):
		for leg in legs_node.get_children():
			var leg_sprite = leg.get_node_or_null("Sprite")
			if leg_sprite:
				leg_sprite.self_modulate = item_data.legs_modulate
