# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/ingame/upgrades_ui.gd"


class ConsumableToProcess:
	var consumable_data: ConsumableData
	var player_index: int
	var p2w_rung: int = - 1  # Gourmet DLC - P2W lootbox rarity, -1 for vanilla crates

# Gourmet DLC - upgrade picks the player still owes for the current level-up draft. 1 for
# everyone; the Freeloader gets 2 (ItemService.get_nb_upgrade_picks), so after his first pick
# we re-show the remaining cards instead of advancing.
var _freeloader_upgrade_picks_left: = [0, 0, 0, 0]




func _show_next_player_options() -> bool:
	for player_index in RunData.get_player_count():
		var player_container = _get_player_container(player_index)
		if _player_is_choosing[player_index]:
			continue
		if _extra_items_to_process[player_index]:
			var extra_item: ItemData = _get_extra_crate_item(player_index)
			player_container.show_item(extra_item)
			_player_is_choosing[player_index] = true
			continue
		var do_process_consumables: bool = not _consumables_to_process[player_index].empty()
		var player_options_to_process = _consumables_to_process[player_index] if do_process_consumables else _upgrades_to_process[player_index]
		if player_options_to_process.empty():
			player_container.finish()
			continue
		var option_to_process = player_options_to_process.pop_front()
		if do_process_consumables:
			_check_extra_items_in_crate_effect(player_index)
			player_container.show_consumable_data(option_to_process.consumable_data, option_to_process.p2w_rung)
		else:
			player_container.show_upgrades_for_level(option_to_process.level)
			_freeloader_upgrade_picks_left[player_index] = ItemService.get_nb_upgrade_picks(player_index)
		_update_player_stats(player_index)
		show()
		player_container.focus()
		_player_is_choosing[player_index] = true
		_showing_option[player_index] = option_to_process
	for player_index in RunData.get_player_count():
		if _player_is_choosing[player_index]:
			return true
	return false



func _on_choose_button_pressed(upgrade_data: UpgradeData, player_index: int) -> void :
	_player_is_choosing[player_index] = false
	emit_signal("upgrade_selected", upgrade_data, _showing_option[player_index])
	LinkedStats.reset_player(player_index)
	_update_player_stats(player_index)
	# Gourmet DLC - Freeloader keeps 2 upgrades from one draft. After his first pick, re-show
	# the remaining cards for a second pick before advancing. Everyone else has picks_left == 1
	# and never enters this branch.
	if _freeloader_upgrade_picks_left[player_index] > 1:
		_freeloader_upgrade_picks_left[player_index] -= 1
		if _get_player_container(player_index).reshow_remaining_after_pick(upgrade_data):
			_player_is_choosing[player_index] = true
			show()
			_get_player_container(player_index).focus()
			return
		_freeloader_upgrade_picks_left[player_index] = 0
	if not _show_next_player_options():
		emit_signal("options_processed")
