# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://entities/units/neutral/neutral.gd"



func init(zone_min_pos: Vector2, zone_max_pos: Vector2, players_ref: Array = [], entity_spawner_ref = null) -> void :
	.init(zone_min_pos, zone_max_pos, players_ref, entity_spawner_ref)
	init_current_stats()
	_apply_butcher_meat_rack()



# Gourmet DLC - Butcher: the on-map fruit tree shows as a meat drying rack. Pooled
# nodes carry textures across runs, so both directions are set explicitly. (butcher_meat_rack)
func _apply_butcher_meat_rack() -> void :
	if stats == null or stats.resource_path.find("tree") == - 1:
		return
	var spr = get_node_or_null("Animation/Sprite")
	if spr == null:
		return
	if not has_meta("orig_tree_tex"):
		set_meta("orig_tree_tex", spr.texture)
	if ButcherSkin.is_butcher_in_run():
		var meat = ButcherSkin.world_texture("meat_rack_ingame")
		if meat != null:
			spr.texture = meat
	else:
		spr.texture = get_meta("orig_tree_tex")



func respawn() -> void :
	.respawn()
	init_current_stats()
	current_number_of_hits = 0
	_apply_butcher_meat_rack()
