# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://entities/structures/structure.gd"

signal wanted_to_spawn_food(food_id_hash, pos)
