extends Node

# nicolassut-GourmetFood pack mod entry (GENERATED by asset-dev/build_workshop.py).
# Near-pure-data: pack registration is data-driven - GourmetCore's PackService
# scans res://packs/ and finds this mod's payload (pack_data.tres + content,
# overlaid at their true res:// paths from the mod zip; payload_manifest.json
# is the authoritative file list). mod_main only loads the pack's translation
# rows.

const LOG_NAME = "nicolassut-GourmetFood"
const TRANSLATIONS_CSV = "res://mods-unpacked/nicolassut-GourmetFood/translations.csv"


func _init():
	ModLoaderLog.info("Init", LOG_NAME)
	_load_translations()


func _load_translations() -> void :
	# runtime replacement for the project.godot translations list (a mod
	# cannot patch it): parse this mod's CSV rows into Translation resources
	var f = File.new()
	if f.open(TRANSLATIONS_CSV, File.READ) != OK:
		return
	var header = f.get_csv_line()
	if header.size() < 2:
		f.close()
		return
	var translations = []
	for i in range(1, header.size()):
		var t = Translation.new()
		t.locale = header[i]
		translations.push_back(t)
	while not f.eof_reached():
		var row = f.get_csv_line()
		if row.size() < 2 or row[0] == "":
			continue
		for i in range(1, int(min(row.size(), header.size()))):
			translations[i - 1].add_message(row[0], row[i])
	f.close()
	for t in translations:
		TranslationServer.add_translation(t)
