#!/usr/bin/env python3
"""Ecosystem Phase 8 - Workshop packaging toolchain (scaffold stage).

Generates `workshop/` from the current repo state:
  - nicolassut-GourmetCore/   manifest + mod_main stub + the CORE SURFACE inventory
    (every game-src engine file = a future script-extension target)
  - nicolassut-Gourmet<Pack>/ per pack: manifest (depends on Core) + mod_main stub +
    content_manifest.json (every resource path the pack registers, from its pack tres)
  - WORKSHOP_READINESS.md     the honest state report: what is packageable today,
    what blocks real packaging, and the conversion debt per engine file

This stage ships NO distribution and produces NO working mods - it is the
measurement + skeleton layer the actual conversion fills in. Idempotent:
regenerates everything from scratch on each run.
"""
import os, re, json, shutil, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gen_extensions
import gen_payloads
REPO = os.path.dirname(HERE)
OUT = os.path.join(REPO, "workshop")
PACKS = ["food", "forge", "ledger", "roster"]  # fortune merged into forge (2026-08-18)
GAME_VERSION = "1.1.15.4"

# files that are PACK data or generated, not Core engine surface
NON_CORE_PREFIXES = ("packs/", "items/custom/p2w/p2w_data.gd", "items/upgrades/appetite/",
                     "items/custom/custom_translations.csv", "items/upgrades/appetite/stomach.png")


TRANSLATION_LOADER = """
func _load_translations() -> void :
	# runtime replacement for the project.godot translations list (a mod
	# cannot patch it): parse this mod's CSV rows into Translation resources
	var f = File.new()
	if f.open(TRANSLATIONS_CSV, File.READ) != OK:
		return
	var header = f.get_csv_line()
	if header.size() < 2:
		f.close()
		return
	var translations = []
	for i in range(1, header.size()):
		var t = Translation.new()
		t.locale = header[i]
		translations.push_back(t)
	while not f.eof_reached():
		var row = f.get_csv_line()
		if row.size() < 2 or row[0] == "":
			continue
		for i in range(1, int(min(row.size(), header.size()))):
			translations[i - 1].add_message(row[0], row[i])
	f.close()
	for t in translations:
		TranslationServer.add_translation(t)
"""

PACK_MOD_MAIN_TEMPLATE = """extends Node

# %(mod)s pack mod entry (GENERATED by asset-dev/build_workshop.py).
# Near-pure-data: pack registration is data-driven - GourmetCore's PackService
# scans res://packs/ and finds this mod's payload (pack_data.tres + content,
# overlaid at their true res:// paths from the mod zip; payload_manifest.json
# is the authoritative file list). mod_main only loads the pack's translation
# rows.

const LOG_NAME = "%(mod)s"
const TRANSLATIONS_CSV = "res://mods-unpacked/%(mod)s/translations.csv"


func _init():
	ModLoaderLog.info("Init", LOG_NAME)
	_load_translations()

""" + TRANSLATION_LOADER


def manifest(name, description, dependencies):
    return {
        "name": name, "namespace": "nicolassut", "version_number": "0.1.0",
        "description": description,
        "website_url": "https://github.com/nicolassut/brotato-mods",
        "dependencies": dependencies,
        "extra": {"godot": {
            "incompatibilities": [], "authors": ["nicolassut"],
            "compatible_mod_loader_version": ["6.3.0"],
            "compatible_game_version": [GAME_VERSION],
            "config_defaults": {},
        }},
    }


def pack_content(pack_id):
    text = open(f"{REPO}/game-src/packs/{pack_id}/pack_data.tres").read()
    paths = re.findall(r'\[ext_resource path="res://([^"]+)" type="Resource"', text)
    return [p for p in paths if p != "packs/pack_data.gd"]


def main():
    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(OUT)

    # ---- core surface inventory ----
    core_files = []
    for root, _dirs, files in os.walk(f"{REPO}/game-src"):
        for f in files:
            rel = os.path.relpath(os.path.join(root, f), f"{REPO}/game-src")
            if rel == "README.md" or any(rel.startswith(p) for p in NON_CORE_PREFIXES):
                continue
            core_files.append(rel)
    core_files.sort()
    gd_files = [f for f in core_files if f.endswith(".gd")]
    other_files = [f for f in core_files if not f.endswith(".gd")]

    # With the pristine reference present (~/brotato-vanilla-reference, GDRE
    # v2.6.0 recovery of the Steam pck), the surface splits into REAL diffs:
    # modified-vanilla files (extension targets, with line counts), mod-ADDED
    # files (ship as-is, no extension needed), and precautionary mirrors
    # (identical to vanilla - not Core surface at all).
    import subprocess
    van = os.path.expanduser("~/brotato-vanilla-reference")
    diffed, added, identical = [], [], []
    if os.path.isdir(van):
        for f in gd_files:
            vpath = os.path.join(van, f)
            if not os.path.exists(vpath):
                added.append(f)
            elif subprocess.run(["cmp", "-s", vpath, f"{REPO}/game-src/{f}"]).returncode == 0:
                identical.append(f)
            else:
                n = int(subprocess.run(["bash", "-c", "diff '%s' '%s/game-src/%s' | grep -c '^[<>]'" % (vpath, REPO, f)],
                                       capture_output=True, text=True).stdout.strip() or 0)
                diffed.append({"file": f, "diff_lines": n})
        diffed.sort(key=lambda d: -d["diff_lines"])

    core_dir = os.path.join(OUT, "nicolassut-GourmetCore")
    os.makedirs(os.path.join(core_dir, "extensions"))
    json.dump(manifest("GourmetCore",
                       "Gourmet ecosystem base: engine extensions, PackService, game modes, the Hub. All Gourmet packs depend on this.",
                       []),
              open(os.path.join(core_dir, "manifest.json"), "w"), indent="\t")
    json.dump({"script_extension_targets": diffed if diffed else gd_files,
               "mod_added_scripts": added, "precautionary_mirrors_identical": identical,
               "non_script_surface": other_files},
              open(os.path.join(core_dir, "core_surface.json"), "w"), indent=1)
    # ---- REAL extensions: generated per-function diff vs the pristine tree ----
    targets = sorted(d["file"] for d in diffed)
    if not targets:
        raise SystemExit("no pristine reference found - cannot generate extensions")
    installed, errors, _audit = gen_extensions.generate(
        targets, f"{REPO}/game-src", core_dir)
    if errors:
        raise SystemExit(
            "extension generation FAILED for %d file(s) - see %s/AUDIT.md"
            % (len(errors), core_dir))
    ext_list = "\n".join('\t"%s",' % rel for rel in installed)
    open(os.path.join(core_dir, "mod_main.gd"), "w").write(
"""extends Node

# GourmetCore mod entry (GENERATED by asset-dev/build_workshop.py - DO NOT EDIT)
#
# 1. installs a script extension for every vanilla .gd the ecosystem modifies
#    (generated from a per-function diff against the pristine 1.1.15.4 tree)
# 2. root-injects the 5 custom services as runtime pseudo-autoloads
#    (project.godot cannot be patched by a mod). Node names MUST match the
#    live-tree autoload names: Utils.packs & co resolve /root/<Name> in both
#    worlds.
# 3. registers the "interact" input action (lobby NPCs) via InputMap.
#
# ONLY ModLoaderMod.install_script_extension works on autoload scripts - the
# deprecated ModLoader.install_script_extension shim silently no-ops there
# (probe-proven 2026-08-18).

const LOG_NAME = "nicolassut-GourmetCore"
const EXT_ROOT = "res://mods-unpacked/nicolassut-GourmetCore/extensions/"
const TRANSLATIONS_CSV = "res://mods-unpacked/nicolassut-GourmetCore/translations.csv"

const SERVICES = [
	["GourmetTracker", "res://singletons/gourmet_tracker.gd"],
	["ButcherSkin", "res://singletons/butcher_skin.gd"],
	["SpecialModifiers", "res://singletons/special_modifiers.gd"],
	["Packs", "res://singletons/pack_service.gd"],
	["GameModes", "res://singletons/game_mode_service.gd"],
]

const EXTENSIONS = [
%s
]


func _init():
	ModLoaderLog.info("Init", LOG_NAME)
	_load_translations()
	# PRE-WARM: fully load every vanilla target (parents first) BEFORE
	# ModLoader's sorter force-loads the extension scripts. Without this, the
	# sorter compiles extensions against half-loaded vanilla chains and caches
	# them broken - reload at apply time does not always recover (measured
	# 2026-08-18: 3 extensions failed to install).
	for ext in EXTENSIONS:
		var _warm = load("res://" + ext)
	for ext in EXTENSIONS:
		ModLoaderMod.install_script_extension(EXT_ROOT.plus_file(ext))


func _ready():
	ModLoaderLog.info("Ready", LOG_NAME)
	_retry_failed_extensions()
	_register_interact_action()
	_swap_early_autoload_scripts()
	# The service NODES must exist (findable by name) before ProgressData's
	# _ready drives Packs.apply_at_boot. Root itself rejects add_child during
	# the autoload cascade ("parent busy setting up children" - measured
	# 2026-08-18), so the services live under THIS mod node; Utils' accessor
	# falls back to searching the ModLoader subtree by node name.
	var tree_root = get_tree().get_root()
	for svc in SERVICES:
		if tree_root.has_node(svc[0]):
			continue
		var node = load(svc[1]).new()
		node.name = svc[0]
		add_child(node)


func _swap_early_autoload_scripts() -> void :
	# Autoloads that instantiate BEFORE ModLoader (Keys is autoload #4) keep
	# their vanilla script even after the path is taken over - swap the live
	# node's script so the extension's members exist. set_script re-runs the
	# member initializers (vanilla + extension); nothing has cached Keys state
	# this early (later autoloads have not run _ready yet).
	var keys = get_node_or_null("/root/Keys")
	if keys == null:
		return
	var ext_script = load("res://singletons/keys.gd")
	if keys.get_script() != ext_script:
		keys.set_script(ext_script)


func _retry_failed_extensions() -> void :
	# ModLoader's sorter force-loads extensions before any install; a compile
	# that fails there (transient half-loaded chains, class-identity flux) can
	# leave that one extension uninstalled. By _ready the world is stable:
	# reload the vanilla resident (rebinding class identities against the now-
	# extended scripts) and re-install - install_script_extension applies
	# immediately outside the init phase.
	for ext in EXTENSIONS:
		var resident: Script = load("res://" + ext)
		if resident != null and resident.has_meta("extension_script_path"):
			continue
		if resident != null:
			resident.reload()
		ModLoaderLog.info("Retrying failed extension: %%s" %% ext, LOG_NAME)
		ModLoaderMod.install_script_extension(EXT_ROOT.plus_file(ext))


func _register_interact_action() -> void :
	# mirrors the live-tree project.godot action: E + gamepad button 3
	if InputMap.has_action("interact"):
		return
	InputMap.add_action("interact", 0.5)
	var key = InputEventKey.new()
	key.scancode = KEY_E
	InputMap.action_add_event("interact", key)
	var joy = InputEventJoypadButton.new()
	joy.button_index = 3
	InputMap.action_add_event("interact", joy)
""" % ext_list + TRANSLATION_LOADER)
    print(f"generated {len(installed)} extensions + real mod_main.gd")

    # ---- per-pack mods ----
    pack_contents = {}
    for pack_id in PACKS:
        content = pack_content(pack_id)
        pack_contents[pack_id] = content
        pack_dir = os.path.join(OUT, "nicolassut-Gourmet%s" % pack_id.capitalize())
        os.makedirs(pack_dir)
        json.dump(manifest("Gourmet%s" % pack_id.capitalize(),
                           "Gourmet ecosystem pack: %s (%d resources). Requires GourmetCore." % (pack_id, len(content)),
                           ["nicolassut-GourmetCore"]),
                  open(os.path.join(pack_dir, "manifest.json"), "w"), indent="\t")
        json.dump({"pack_id": pack_id, "resources": content},
                  open(os.path.join(pack_dir, "content_manifest.json"), "w"), indent=1)

    # ---- payload manifests + translation split ----
    # Core-shipped code pins its references to the Core payload (extensions
    # preload things; Core must be self-contained regardless of pack combo).
    core_code = [os.path.join(r, f) for r, _d, fs in
                 os.walk(os.path.join(core_dir, "extensions"))
                 for f in fs if f.endswith(".gd")]
    core_code.append(os.path.join(core_dir, "mod_main.gd"))
    assigned, pay_audit = gen_payloads.assign_payloads(pack_contents, core_code)
    tr_rows, tr_header, tr_audit = gen_payloads.split_translations(assigned)

    mod_dir_of = {"core": core_dir}
    for pack_id in PACKS:
        mod_dir_of[pack_id] = os.path.join(
            OUT, "nicolassut-Gourmet%s" % pack_id.capitalize())
    import csv as _csv
    for owner, mod_dir in mod_dir_of.items():
        json.dump({"files": sorted(assigned[owner])},
                  open(os.path.join(mod_dir, "payload_manifest.json"), "w"),
                  indent=1)
        with open(os.path.join(mod_dir, "translations.csv"), "w",
                  newline="", encoding="utf-8") as f:
            w = _csv.writer(f)
            w.writerow(tr_header)
            for row in sorted(tr_rows[owner]):
                w.writerow(row)
    open(os.path.join(OUT, "PAYLOAD_AUDIT.md"), "w").write(
        "# Payload assignment audit (generated)\n\n" +
        "\n".join("- %s" % l for l in pay_audit + tr_audit) + "\n")

    # real pack mod_mains: near-pure-data - registration is data-driven
    # (PackService scans res://packs/, which the payload overlays); mod_main
    # only runtime-loads the pack's translation rows.
    for pack_id in PACKS:
        mod_name = "nicolassut-Gourmet%s" % pack_id.capitalize()
        open(os.path.join(mod_dir_of[pack_id], "mod_main.gd"), "w").write(
            PACK_MOD_MAIN_TEMPLATE % {"mod": mod_name})
        print(f"built {mod_name}: {len(pack_contents[pack_id])} resources, "
              f"{len(assigned[pack_id])} payload files, "
              f"{len(tr_rows[pack_id])} translation rows")
    print(f"built GourmetCore: {len(assigned['core'])} payload files, "
          f"{len(tr_rows['core'])} translation rows")

    # ---- readiness report ----
    hook_marked = sum(1 for f in gd_files if "Gourmet" in open(f"{REPO}/game-src/{f}").read())
    report = f"""# WORKSHOP_READINESS - Phase 8 state (generated by build_workshop.py)

## What exists
- {len(PACKS)} pack mod scaffolds + GourmetCore scaffold under `workshop/` (manifests
  validate against the ModLoader schema used by the working prototypes in
  `mods-unpacked/`).
- Pack content manifests are REAL: generated from the live pack tres files, so the
  data side of packaging is already mechanical.

## Core surface (what GourmetCore must carry) - MEASURED against pristine vanilla
- {len(diffed) if diffed else len(gd_files)} vanilla .gd files actually modified (extension targets, ranked by
  diff-line count in `core_surface.json`; top: {diffed[0]["file"] + " at " + str(diffed[0]["diff_lines"]) + " lines" if diffed else "n/a"}).
- {len(added)} mod-ADDED scripts (ship as files, no extension machinery needed).
- {len(identical)} precautionary mirrors identical to vanilla (not Core surface).
- {len(other_files)} non-script files (scenes/config/art) needing other strategies.
- {hook_marked}/{len(gd_files)} .gd files carry Gourmet-marked edits.

## Blockers before real packaging (ordered)
1. ~~Pristine decompile~~ **RESOLVED 2026-08-18**: `~/brotato-vanilla-reference/` is a
   GDRE v2.6.0 recovery of the Steam pck ({GAME_VERSION}), determinism-validated
   (untouched files byte-identical, 445/445 scripts). Regenerable: GDRE Tools in
   ~/Downloads, `--headless --recover=<pck> --output=<dir>`. Full-game sweep found
   exactly ONE unmirrored edit (debug_service.gd - the known local-only debug block).
2. ~~Autoload strategy~~ **RESOLVED BY EXPERIMENT 2026-08-18** (disposable-clone
   probes, real trees untouched; full backups taken first). Findings:
   - Script extensions via `ModLoaderMod.install_script_extension` WORK ON
     AUTOLOAD SCRIPTS (utils.gd + progress_data.gd proven) - the deprecated
     `ModLoader.install_script_extension` shim does NOT; never use it.
   - The critical ordering survives: an extension of ProgressData._ready runs
     BEFORE the vanilla body loads the save - packs-before-save-load holds.
   - Service root-injection: add_child must be IMMEDIATE from the mod's _ready
     (call_deferred lands after the autoload phase - too late).
   - Bare autoload identifiers are PARSE-FATAL on installs lacking them (655
     cascade errors with Packs/GameModes removed). Strategy: host services on
     an extension of an always-present vanilla autoload and rewrite references
     mechanically. Measured burden: Packs. x11, GameModes. x8, GourmetTracker.
     x66, SpecialModifiers. x19, ButcherSkin. x5 = 109 references total.
3. ~~project.godot input action~~ **RESOLVED**: Core's mod_main registers
   `interact` (E + gamepad button 3) via InputMap at runtime.
4. ~~item_service.tscn / scene diffs~~ **RESOLVED**: zero vanilla scenes ship.
   The item_service.tscn diff (5 vanilla item removals + `foods` export) is a
   guarded runtime prune + an extension export default; the pause.tscn diff
   (blobfish margins) is patched from the pause.gd extension. The 8 mod-ADDED
   scenes ship as files.
5. ~~Service references~~ **RESOLVED**: all 109 bare references rewritten to
   the Utils accessors (lazy /root/<Name> lookup, identical in both worlds).
6. ~~Payloads + translations~~ **RESOLVED**: payload_manifest.json per mod -
   the mod-added-file UNIVERSE is measured against the pristine tree and every
   file lands in exactly one payload (PAYLOAD_AUDIT.md records shared/pinned/
   dead/deregistered); per-mod translations.csv split from the sacred CSV and
   runtime-loaded in mod_main; `asset-dev/pack_workshop_zips.py` assembles
   workshop/dist/*.zip (payload at true res:// paths + .import/.stex).
7. ~~End-to-end gate~~ **RESOLVED - GATE PASSES**: `bash check_workshop.sh`
   boots a disposable no-DLC clone of the pristine reference with the mods in
   three install combos (all six / Core+Food / Core-only), asserting exact
   registered counts + PackService VERIFY OK per combo. Hard-won laws baked
   into the generator+mod_main (all measured 2026-08-18):
   - EXTENSION SANDWICH: an extension may never change a vanilla function's
     signature (vanilla children override the old one) - resolved via
     delegate funcs (get_name_text_for, _on_gourmet_item_discard_pressed)
   - pre-ModLoader autoloads (Keys, #4) keep the vanilla script; Core swaps
     it via set_script in _ready
   - services CANNOT be added to /root during the autoload cascade - they
     live under the Core mod node; Utils' accessor searches both
   - ModLoader's sorter force-loads extensions against half-loaded chains;
     mod_main PRE-WARMS all vanilla targets first and RETRIES failed installs
     in _ready (world stable there)
   - a child script cannot forward vanilla _init args (Godot 3 quirk) - the
     generator synthesizes forwarding constructors
   - cross-extension global-class bindings compile stale (ModLoader sort
     order) - creation sites use load-by-path; the generator hard-errors on
     new hazards
   - baked res://dlcs/ refs are fatal on DLC-less installs - DLC weapon sets
     attach at runtime (PackService._attach_dlc_sets)
   - the missing GUT test sources (in _global_script_classes but not the
     pck) abort ModLoader's child-reload helper - errors whitelisted, retry
     pass compensates.

## Known gaps (accepted, documented)
- The dlcs/ tree is the decompiled PAID DLC and never ships. Its one script
  edit (Freeloader curse hook) ships as a DLC-guarded late extension; the
  local cursed_chest_data.tres icon edit does NOT ship - Workshop DLC owners
  see the vanilla cursed-chest icon.
- The clone gate materializes payloads by copying (load_resource_pack of a
  zip WIPES res:// in editor mode - engine limitation); the zip overlay path
  is only exercised on the real exported game. Final zip validation happens
  on a Steam install.

## Law
Regenerate this report after any engine change: `python3 asset-dev/build_workshop.py`.
The scaffolds are throwaway; the inventories are the deliverable.
"""
    open(os.path.join(OUT, "WORKSHOP_READINESS.md"), "w").write(report)
    print(f"core surface: {len(gd_files)} .gd + {len(other_files)} other; report written")


if __name__ == "__main__":
    main()
