# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://items/global/item_parent_data.gd"



func get_effects_text(player_index: int) -> String:
	var text = ""
	for i in effects.size():
		# effects marked EFFECT_HIDDEN work silently (their text lives in a summary line)
		var effect_text = "" if effects[i].text_key == "EFFECT_HIDDEN" else effects[i].get_text(player_index)
		text += effect_text
		if effect_text != "" and i < effects.size() - 1:
			 text += "\n"
	text += _get_tracking_text(player_index)
	return text








func _get_tracking_text(player_index: int) -> String:
	var text : String = ""
	if player_index != RunData.DUMMY_PLAYER_INDEX and RunData.tracked_item_effects[player_index].has(my_id_hash) and tracking_text != "[EMPTY]":
		var item_effect = RunData.tracked_item_effects[player_index][my_id_hash]
		if item_effect is Array:
			for i in item_effect.size():
				var tracked_count = item_effect[i]
				var tracking_text_to_use = tracking_text
				if my_id_hash == Keys.item_bone_dice_hash and i == 1:
					tracking_text_to_use = "stats_lost"
				elif my_id_hash == Keys.item_bonk_dog_hash and i == 1:
					tracking_text_to_use = "damage_dealt"
				elif my_id_hash == Keys.item_bot_o_mine_hash and i == 1:
					tracking_text_to_use = "dropped_landmines"
				elif my_id_hash == Keys.character_hiker_hash and i == 0:
					tracking_text_to_use = "materials_gained"
				elif my_id_hash == Keys.item_doc_moth_hash and i == 1:
					tracking_text_to_use = "health_recovered"
				elif my_id_hash == Keys.item_soul_food_hash and i == 1:
					tracking_text_to_use = "soul_food_flipped"
				# Gourmet DLC - characters that bank a second, different quantity. Index 0 keeps
				# the card's own tracking_text; index 1 is relabelled here, same as Soul Food.
				elif my_id_hash == Keys.generate_hash("character_butcher") and i == 1:
					tracking_text_to_use = "butcher_appetite_rendered"
				elif my_id_hash == Keys.generate_hash("character_gourmet") and i == 1:
					tracking_text_to_use = "gourmet_speed_lost"
				elif my_id_hash == Keys.generate_hash("character_snail") and i == 1:
					tracking_text_to_use = "damage_dealt"
				elif my_id_hash == Keys.generate_hash("character_test_debt") and i == 1:
					tracking_text_to_use = "debtor_debt_repaid"
				text += "\n[color=#" + Utils.SECONDARY_FONT_COLOR.to_html() + "]" + Text.text(tracking_text_to_use.to_upper(), [Text.get_formatted_number(tracked_count)]) + "[/color]"
		else:
			var after = ""
			if my_id_hash == Keys.item_fish_hook_hash:
				after = "%"
			var append_text = "\n[color=#" + Utils.SECONDARY_FONT_COLOR.to_html() + "]" + Text.text(tracking_text.to_upper(), [Text.get_formatted_number(item_effect)]) + after + "[/color]"
			if my_id_hash == Keys.item_fish_hook_hash and item_effect == 0:
				append_text = ""
			text += append_text
	return text



func get_name_text(player_index: int = - 1) -> String:
	return tr(name)






func deserialize_and_merge(serialized: Dictionary) -> void:
	my_id = serialized.my_id
	my_id_hash = Keys.generate_hash(my_id)
	name = serialized.name
	tier = serialized.tier as int
	value = serialized.value as int
	tracking_text = serialized.tracking_text
	is_locked = serialized.is_locked
	is_cursed = serialized.is_cursed
	is_lockable = serialized.is_lockable if "is_lockable" in serialized else true
	curse_factor = serialized.curse_factor as float if "curse_factor" in serialized else 0.0
	var deserialized_effects = []
	for serialized_effect in serialized.effects:
		for effect in ItemService.effects:
			if effect.get_id() == serialized_effect.effect_id:
				var instance = effect.new()
				instance.deserialize_and_merge(serialized_effect)
				deserialized_effects.push_back(instance)
				break
	effects = deserialized_effects
	# Gourmet DLC - food display effects are PURE TEXT (key "", value 0, only a
	# text_key + consumable_food_* custom_key driving card lines). A save taken
	# before a card gained such a line would otherwise show the stale card
	# forever (e.g. Gumball Machine predating the red/blue colour lines). Safe
	# to append even on cursed instances: these effects carry no numbers.
	var display_template = ItemService.get_element_safe(ItemService.items, my_id)
	if display_template == null:
		display_template = ItemService.get_element_safe(ItemService.weapons, my_id)
	if display_template != null:
		for template_effect in display_template.effects:
			if template_effect.key != "" or not template_effect.custom_key.begins_with("consumable_food_"):
				continue
			var display_line_present: bool = false
			for own_effect in effects:
				if own_effect.custom_key == template_effect.custom_key:
					display_line_present = true
					break
			if not display_line_present:
				effects.push_back(template_effect.duplicate())
