# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://items/global/weapon_data.gd"




func _get_tracking_text(player_index: int) -> String:
	# Gourmet DLC - a food that credits a weapon (Frying Pan -> Fried Egg's permanent Luck)
	# accumulates through RunData.add_tracked_value under the UNTIERED weapon_id, because the
	# food's tracking_item_id cannot know which tier is equipped. WeaponData's own
	# tracked_value is fed ONLY by the three on_tracked_value_updated emitters in weapon.gd,
	# so without this bridge the Frying Pan card sat at "Luck gained: 0" for the whole run
	# while the real total piled up in a RunData bucket nothing ever read. Added, not
	# replaced, so vanilla weapons that do use tracked_value are unaffected.
	var displayed_value: int = tracked_value
	if player_index != RunData.DUMMY_PLAYER_INDEX and player_index < RunData.tracked_item_effects.size():
		var weapon_id_hash: int = Keys.generate_hash(weapon_id)
		if RunData.tracked_item_effects[player_index].has(weapon_id_hash):
			displayed_value += int(RunData.tracked_item_effects[player_index][weapon_id_hash])
	return "\n[color=#" + Utils.SECONDARY_FONT_COLOR.to_html() + "]" + Text.text(tracking_text.to_upper(), [str(displayed_value)]) + "[/color]"



func get_name_text(player_index: int = - 1) -> String:
	# Gourmet DLC - both halves of the ladder-naming rule, merged:
	#   player_index : the ladder belongs to the card's OWNER, so a Blacksmith or P2W in coop
	#                  never renames another player's weapons.
	#   for_weapon   : only WEAPONS are named by ladder position - upgrades and items keep
	#                  vanilla numbering, which is what stopped "Fingers III" reading as V.
	var tier_number = ItemService.get_tier_number(tier, player_index, true)
	return tr(name) + (" " + tier_number if tier_number != "" else "")
