# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/shop/button_with_icon.gd"

# Gourmet DLC - The Debtor buys on debt, so his prices show as "-N" in the negative colour.
var _debt_mode: = false



func set_color_from_currency(currency: int) -> void :
	# Gourmet DLC - Debtor prices always read in the negative colour (bought on debt).
	if _debt_mode:
		_color_locked = true
		_update_focus_colors()
		return
	if currency < _value:
		_color_locked = true
	else:
		_color_locked = false
	_update_focus_colors()



func set_value(value: int, currency: int) -> void :
	_value = value
	if _debt_mode:
		_label.text = "-" + str(value)
		_color_locked = true
		_update_focus_colors()
	else:
		_label.text = str(value)
		set_color_from_currency(currency)



func set_debt_mode(on: bool) -> void :
	_debt_mode = on
