# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/shop/coop_shop_player_container.gd"



func _ready():
	_set_player_index(player_index)
	if RunData.get_player_count() == 2:
		margin_container.add_constant_override("margin_left", 75)
		margin_container.add_constant_override("margin_right", 75)
	item_popup.set_synergies_visible(_should_show_synergies())
	_set_focus_neighbours()
	item_popup.connect("popup_toggled", self, "on_popup_toggled")
	# Gourmet DLC - Wildcard: default the coop stat sheet to the Rules view each shop (no-op for
	# other characters). In coop the sheet is a per-wave, on-demand carousel page, so the
	# one-time default in StatsContainer._ensure_rules_ui is not enough by itself.
	for stats_container in [primary_stats_container, secondary_stats_container]:
		stats_container.open_rules_default(player_index)
