# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/shop/coop_shop.gd"



# Gourmet ecosystem - the any-item discard path (see base_shop)
func _on_gourmet_item_discard_pressed(weapon_data: ItemParentData, player_index: int) -> void :
	._on_gourmet_item_discard_pressed(weapon_data, player_index)
	_get_coop_player_container(player_index).on_hide_focused_inventory_popup()
