# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/shop/item_popup.gd"



func _update_button_visibilities() -> void :
	var buttons: = [_combine_button, _discard_button, _cancel_button]
	if _item_data == null or not should_show_buttons(_item_data, _focused):
		for button in buttons:
			button.hide()
			button.focus_mode = FOCUS_NONE
		return
	for button in buttons:
		button.show()
		button.focus_mode = FOCUS_ALL if _focused else FOCUS_NONE
	_combine_button.visible = _item_data is WeaponData and RunData.can_combine(_item_data, player_index)
	# Gourmet DLC - Blacksmith: relabel the forge button for each step of the manual pair-pick
	if _combine_button.visible and _item_data is WeaponData and RunData.is_blacksmith(player_index):
		var forge_pick = RunData.get_forge_pick(player_index)
		if forge_pick == null:
			_combine_button.text = tr("GOURMET_FORGE_START")
		elif forge_pick == _item_data:
			_combine_button.text = tr("GOURMET_FORGE_CANCEL")
		else:
			_combine_button.text = tr("GOURMET_FORGE_CONFIRM")
	elif _item_data is WeaponData:
		_combine_button.text = tr("MENU_COMBINE")
	var base_recycling_value = _item_data.value
	var specific_recycling_price_factor = 1.0
	for specific_item_price in RunData.get_player_effect(Keys.specific_items_price_hash, player_index):
		assert (specific_item_price[0] is int)
		if Keys.hash_to_string[specific_item_price[0]] in _item_data.my_id:
			specific_recycling_price_factor = specific_item_price[1]
			break
	base_recycling_value *= specific_recycling_price_factor
	_discard_button.text = tr("MENU_RECYCLE") + " (+" + str(ItemService.get_recycling_value(RunData.current_wave, base_recycling_value, player_index, _item_data is WeaponData)) + ")"
	# Gourmet DLC - spawner selection replaces the recycle action for spawner items
	if is_spawner_selection_mode(_item_data):
		_combine_button.hide()
		var selected_hash: int = RunData.get_player_effect(Keys.selected_spawner_hash, player_index)
		var this_food_hash: int = Keys.empty_hash
		for popup_effect in _item_data.effects:
			if popup_effect.custom_key.begins_with("consumable_food_"):
				this_food_hash = Keys.generate_hash(popup_effect.custom_key)
				break
		if selected_hash != 0 and selected_hash == this_food_hash:
			_discard_button.text = tr("GOURMET_SPAWNER_ACTIVE")
			_discard_button.disabled = true
		else:
			_discard_button.text = tr("GOURMET_SELECT_SPAWNER")
			_discard_button.disabled = false
	else:
		_discard_button.disabled = false
	if RunData.get_player_effect_bool(Keys.lock_current_weapons_hash, player_index):
		_combine_button.hide()
		_discard_button.hide()



func should_show_buttons(item_data: ItemParentData, focused: bool) -> bool:
	# Gourmet DLC - Minimalist: owned items get the recycle menu too (no combine)
	var minimalist_char = RunData.get_player_character(player_index)
	if buttons_enabled and _is_inventory_element and minimalist_char != null and minimalist_char.my_id == "character_minimalist" and item_data is ItemData and not item_data is WeaponData and not item_data is CharacterData and ( not RunData.is_coop_run or focused):
		return true
	# Gourmet DLC - spawner selection (Set Menu / Picky Eater): owned spawner items
	# repurpose the discard button as "Set active"
	if is_spawner_selection_mode(item_data) and ( not RunData.is_coop_run or focused):
		return true
	return buttons_enabled and item_data is WeaponData and ( not RunData.is_coop_run or focused)





func is_spawner_selection_mode(item_data: ItemParentData) -> bool:
	if not buttons_enabled or not _is_inventory_element:
		return false
	if not item_data is ItemData or item_data is WeaponData or item_data is CharacterData:
		return false
	if not item_data.tags.has("spawner"):
		return false
	var selection_char = RunData.get_player_character(player_index)
	if selection_char != null and selection_char.my_id == "character_minimalist":
		return false
	var is_picky: bool = selection_char != null and selection_char.my_id == "character_picky_eater"
	return is_picky or RunData.get_player_effect(Keys.set_menu_hash, player_index) > 0
