# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/shop/shop.gd"




# Gourmet ecosystem - the any-item discard path (see base_shop)
func _on_gourmet_item_discard_pressed(weapon_data: ItemParentData, player_index: int) -> void :
	_block_background.hide()
	._on_gourmet_item_discard_pressed(weapon_data, player_index)
	if _focused_shop_item[player_index] != null:
		_focused_shop_item[player_index]._can_be_selected()
