# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/shop/synergy_panel.gd"



func set_data(set: SetData, player_index: int) -> void :
	var active_sets = RunData.players_data[player_index].active_sets
	var nb = min(set.set_bonuses.size() + 1, active_sets[set.my_id_hash]) as int if active_sets.has(set.my_id_hash) else 0
	# Gourmet DLC - Blacksmith: the APPLIED row is driven by class tier points
	# (run_data.update_sets), not by weapon count. Mirror that math here or the
	# panel highlights nothing / the wrong row while the stats are flowing.
	var bs_applied_row: int = - 1
	if RunData.is_blacksmith(player_index):
		var bs_points: int = int(RunData.players_data[player_index].active_set_points.get(set.my_id_hash, 0))
		var bs_level: int = bs_points / RunData.BS_SET_POINTS_PER_LEVEL
		if bs_level > RunData.BS_SET_MAX_LEVEL:
			bs_level = RunData.BS_SET_MAX_LEVEL
		if bs_level >= 1:
			bs_applied_row = int(min(bs_level - 1, set.set_bonuses.size() - 1))
	_synergy_name.text = tr(set.name)
	_synergy_effects.bbcode_text = ""
	var new_text = ""
	_plain_text = ""
	for i in set.set_bonuses.size():
		var is_applied = i + 2 == nb
		if RunData.is_blacksmith(player_index):
			is_applied = i == bs_applied_row
		var col_a = "" if is_applied else "[color=" + Utils.GRAY_COLOR_STR + "]"
		var col_b = "" if is_applied else "[/color]"
		var new_line = ""
		var value_text: = "(" + str(i + 2) + ") "
		new_line += value_text
		_plain_text += value_text
		var set_bonuses = set.set_bonuses[i]
		for j in set_bonuses.size():
			new_line += set_bonuses[j].get_text(player_index, is_applied)
			_plain_text += set_bonuses[j].get_text(player_index, false)
			if j != set_bonuses.size() - 1:
				new_line += ", "
				_plain_text += ", "
		if i != set.set_bonuses.size() - 1:
			new_line += "\n"
			_plain_text += "\n"
		new_text += col_a + new_line + col_b
	_synergy_effects.bbcode_text = new_text
	if RunData.is_coop_run:
		if new_text.length() >= 300:
			_synergy_effects.add_font_override("normal_font", small_font)
		else:
			_synergy_effects.add_font_override("normal_font", normal_font)
	_resize_to_text()
