# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://items/characters/character_data.gd"

# tint applied to the character's legs so they match a recoloured body (Color(1,1,1) = no change)
export (Color) var legs_modulate = Color( 1, 1, 1 )
