# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/run/difficulty_selection/difficulty_selection.gd"



func _on_element_pressed(element: InventoryElement, _inventory_player_index: int) -> void :
	if difficulty_selected:
		return
	if element.is_special:
		return
	else:
		difficulty_selected = true
		if not RunData.is_coop_run:
			var current_character = RunData.get_player_character(0)
			var character_difficulty = ProgressData.get_character_difficulty_info(current_character.my_id_hash, RunData.current_zone)
			character_difficulty.difficulty_selected_value = element.item.value
		RunData.current_difficulty = element.item.value
		RunData.reset_elites_spawn()
		RunData.init_elites_spawn()
		RunData.init_events_nightmare()
		RunData.enabled_dlcs = ProgressData.get_active_dlc_ids()
	# Gourmet ecosystem - stamp the selected game mode onto every player (the
	# pre-lobby selector is global; per-player selection arrives with the lobby
	# mode shrine). Validated against the live registry + pack availability.
	var selected_mode: String = str(ProgressData.settings.get("selected_game_mode", ""))
	for mode_player_index in RunData.get_player_count():
		RunData.players_data[mode_player_index].game_mode_ids = []
		if selected_mode != "" and not GameModes.mode_by_id(selected_mode).empty():
			for available_mode in GameModes.available_modes():
				if str(available_mode["id"]) == selected_mode:
					RunData.players_data[mode_player_index].game_mode_ids.push_back(selected_mode)
		ProgressData.save()
		for effect in element.item.effects:
			effect.apply(0)
		for player_index in range(RunData.get_player_count()):
			var player_run_data = RunData.players_data[player_index]
			player_run_data.uses_ban = RunData.is_ban_mode_active
			player_run_data.remaining_ban_token = RunData.BAN_MAX_TOKEN
		RunData.init_bosses_spawn()
	RunData.current_run_accessibility_settings = ProgressData.settings.enemy_scaling.duplicate()
	ProgressData.load_status = LoadStatus.SAVE_OK
	ProgressData.increment_stat("run_started")
	ProgressData.data["chal_hourglass_quit_wave"] = false
	var _error = get_tree().change_scene(MenuData.game_scene)
