# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/run/difficulty_selection/difficulty_selection.gd"



func _on_element_pressed(element: InventoryElement, _inventory_player_index: int) -> void :
	if difficulty_selected:
		return
	if element.is_special:
		return
	else:
		difficulty_selected = true
		if not RunData.is_coop_run:
			var current_character = RunData.get_player_character(0)
			var character_difficulty = ProgressData.get_character_difficulty_info(current_character.my_id_hash, RunData.current_zone)
			character_difficulty.difficulty_selected_value = element.item.value
		RunData.current_difficulty = element.item.value
		RunData.reset_elites_spawn()
		RunData.init_elites_spawn()
		RunData.init_events_nightmare()
		RunData.enabled_dlcs = ProgressData.get_active_dlc_ids()
		# (2026-08-18: this block and the one below sat at 1-tab depth, OUTSIDE
		# the else: branch - a parse error no boot gate ever saw because this
		# scene only parses when a run starts. Caught by the workshop gate.)
		# Gourmet ecosystem - stamp the selected game mode onto every player (the
		# pre-lobby selector is global; per-player selection arrives with the lobby
		# mode shrine). Validated against the live registry + pack availability.
		# run-wide multi-select (user 2026-08-18): the SAME validated mode list
		# is stamped onto every player - run-wide semantics riding the existing
		# per-player storage, so save/resume needs no loader change
		var selected_modes: Array = Utils.game_modes.selected_mode_ids()
		for mode_player_index in RunData.get_player_count():
			RunData.players_data[mode_player_index].game_mode_ids = selected_modes.duplicate()
		# Gourmet ecosystem - remember each player's character across sessions: the
		# Hub avatars wear these (HUB_PLAN step 1). This is the single run-start
		# choke point, so the vanilla Start path keeps them fresh too.
		var hub_last_played: Array = ProgressData.settings.get("last_played_characters", ["", "", "", ""])
		while hub_last_played.size() < 4:
			hub_last_played.push_back("")
		for lp_index in RunData.get_player_count():
			var lp_character = RunData.get_player_character(lp_index)
			if lp_character != null and lp_index < 4:
				hub_last_played[lp_index] = str(lp_character.my_id)
		ProgressData.settings.last_played_characters = hub_last_played
		ProgressData.save_settings()
		ProgressData.save()
		for effect in element.item.effects:
			effect.apply(0)
		for player_index in range(RunData.get_player_count()):
			var player_run_data = RunData.players_data[player_index]
			player_run_data.uses_ban = RunData.is_ban_mode_active
			player_run_data.remaining_ban_token = RunData.BAN_MAX_TOKEN
		RunData.init_bosses_spawn()
	RunData.current_run_accessibility_settings = ProgressData.settings.enemy_scaling.duplicate()
	ProgressData.load_status = LoadStatus.SAVE_OK
	ProgressData.increment_stat("run_started")
	ProgressData.data["chal_hourglass_quit_wave"] = false
	var _error = get_tree().change_scene(MenuData.game_scene)
