# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://ui/menus/global/popup_manager.gd"



func _on_shop_item_focused(shop_item: ShopItem):
	var player_index = _get_player_index_for_control(shop_item._button)
	# Gourmet DLC - the Freeloader's 8-slot shop uses the same compact cards co-op uses, so it
	# needs the same hover popup for the details those cards do not show.
	if _item_popups[player_index] and (RunData.is_coop_run or RunData.is_freeloader(player_index)):
		_item_popups[player_index].display_item_data(shop_item.item_data, shop_item._button)
	emit_signal("shop_item_focused", shop_item, player_index)
