# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://entities/structures/turret/garden/garden.gd"



# Gourmet DLC - Butcher: the garden shows as a meat locker (butcher_meat_locker)
func _ready() -> void :
	._ready()
	var spr = get_node_or_null("Animation/Sprite")
	if spr == null:
		return
	if not has_meta("orig_garden_tex"):
		set_meta("orig_garden_tex", spr.texture)
	if ButcherSkin.is_butcher_in_run():
		var meat = ButcherSkin.world_texture("meat_locker_ingame")
		if meat != null:
			spr.texture = meat
	else:
		spr.texture = get_meta("orig_garden_tex")
