# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://entities/units/unit/unit.gd"

# Gourmet DLC - Girly panic-teleport: while _panic_frozen she can't move or shoot;
# panic_target_override (a Vector2 when set) makes chasers path to the OLD spot so
# enemies don't follow her through the teleport. Both are inert on every other unit.
var _panic_frozen: bool = false

var panic_target_override = null

func _physics_process(delta: float) -> void :
	_current_movement = get_movement() if (_can_move and not _panic_frozen) else Vector2.ZERO
	update_animation(_current_movement)
	var velocity = get_next_velocity()
	_integrate_forces_velocity = velocity
	if mode == MODE_KINEMATIC:
		var infinite_inertia = true
		var margin = 0.08
		var delta_position: = Vector2.ZERO
		var result = Physics2DTestMotionResult.new()
		var is_colliding = test_motion(velocity * delta, infinite_inertia, margin, result)
		global_position += result.motion
		delta_position += result.motion
		if is_colliding:
			var slide_velocity = velocity.slide(result.collision_normal)
			var _is_colliding = test_motion(slide_velocity * delta, infinite_inertia, margin, result)
			global_position += result.motion
			delta_position += result.motion
		_on_moved(delta_position)
	if decaying_bonus_speed > 0:
		decaying_bonus_speed = max(decaying_bonus_speed - 60 * delta, 0.0)
	elif decaying_bonus_speed < 0:
		decaying_bonus_speed = min(decaying_bonus_speed + 60 * delta * 5, 0.0)


		



# Gourmet DLC - the position chasers should path to. Normally this unit's live
# position; during Girly's panic-teleport it's the frozen old spot so enemies keep
# heading there until she regains control.
func get_follow_target_position() -> Vector2:
	if panic_target_override != null:
		return panic_target_override
	return global_position



# Gourmet DLC - timed percentage slow (Pocket Sand + Culinary weapons) and the
# Meat Tenderizer damage mark. Evaluated live so no timers or stat resets needed;
# reapplication keeps the strongest value and the latest deadline.
var _gourmet_slow_pct: = 0

var _gourmet_slow_until_msec: = 0

var _gourmet_tenderize_pct: = 0

var _gourmet_tenderize_until_msec: = 0



func apply_gourmet_slow(pct: int, duration: float) -> void :
	if dead:
		return
	_gourmet_slow_pct = int(max(_gourmet_slow_pct, pct))
	_gourmet_slow_until_msec = int(max(_gourmet_slow_until_msec, OS.get_ticks_msec() + duration * 1000.0))



func get_move_speed() -> float:
	var move_speed: float = max(0.0, (current_stats.speed + bonus_speed + decaying_bonus_speed))
	if _gourmet_slow_pct != 0 and OS.get_ticks_msec() < _gourmet_slow_until_msec:
		move_speed *= (100.0 - _gourmet_slow_pct) / 100.0
	return move_speed



func take_damage(value: int, args: TakeDamageArgs) -> Array:
	if _pending_die:
		return [0, 0, false]
	var hitbox = args.hitbox
	var from_player_index = args.from_player_index
	var crit_damage = 0.0
	var crit_chance = 0.0
	var knockback_direction = Vector2.ZERO
	var knockback_amount = 0.0
	var knockback_piercing = 0.0
	var dmg_taken = [0, 0, false]
	if hitbox != null:
		crit_damage = hitbox.crit_damage
		crit_chance = hitbox.crit_chance
		knockback_direction = hitbox.knockback_direction
		if from_player_index < players_ref.size() and is_instance_valid(players_ref[from_player_index]):
			knockback_direction = 0.2 * knockback_direction + 0.8 * players_ref[from_player_index].global_position.direction_to(global_position)
		knockback_amount = hitbox.knockback_amount
		knockback_piercing = hitbox.knockback_piercing
	# Gourmet DLC - Magnifying Glass: bonus crit chance against elites and bosses.
	# Duck-typed via the spawner's boss list: unit.gd must never reference the
	# Boss class name (Unit -> Boss -> Enemy -> Unit is the cycle that bricks loading)
	if from_player_index >= 0 and hitbox != null and _entity_spawner_ref != null and _entity_spawner_ref.bosses.has(self):
		crit_chance += RunData.get_player_effect(Keys.crit_vs_elites_hash, from_player_index) / 100.0
	var is_crit = true if Utils.get_chance_success(crit_chance) else false
	var is_one_shot = false
	# Gourmet DLC - Culinary weapon specials carried on the hitbox
	var gourmet_execute: = 0
	var gourmet_slow_pct: = 0
	var gourmet_slow_chance: = 100
	var gourmet_tenderize: = 0
	var gourmet_extend_buffs: = 0
	var gourmet_heal_on_hit: = 0
	if hitbox:
		for effect in hitbox.effects:
			if _is_burning and effect.key_hash == Keys.crit_on_hitting_burning_target_hash:
				is_crit = true
			elif effect is OneShotOnHitEffect:
				if Utils.get_chance_success(effect.value / 100.0):
					is_one_shot = true
					_on_one_shotted(effect)
				else: is_one_shot = false
			elif effect.key_hash == Keys.execute_damage_hash:
				gourmet_execute = effect.value
			elif effect.key_hash == Keys.gourmet_slow_on_hit_hash:
				gourmet_slow_pct = effect.value
			elif effect.key_hash == Keys.gourmet_slow_chance_hash:
				gourmet_slow_chance = effect.value
			elif effect.key_hash == Keys.tenderize_on_hit_hash:
				gourmet_tenderize = effect.value
			elif effect.key_hash == Keys.extend_buffs_on_hit_hash:
				gourmet_extend_buffs = effect.value
			elif effect.key_hash == Keys.heal_on_hit_hash:
				gourmet_heal_on_hit = effect.value
	var dmg_value = value
	var sound = Utils.get_rand_element(hurt_sounds)
	if is_crit:
		dmg_value = round(value * crit_damage) as int
		sound = Utils.get_rand_element(crit_sounds)
	# Gourmet DLC - Pepper Grinder: flat bonus damage against burning targets
	if _is_burning and from_player_index >= 0:
		dmg_value += RunData.get_player_effect(Keys.damage_vs_burning_hash, from_player_index)
	# Gourmet DLC - Cleaver / Butcher's Saw: bonus damage below 25% HP
	if gourmet_execute != 0 and current_stats.health < max_stats.health * 0.25:
		dmg_value = int(dmg_value * (100.0 + gourmet_execute) / 100.0)
	# Gourmet DLC - Meat Tenderizer mark: marked units take extra damage
	if _gourmet_tenderize_pct != 0 and OS.get_ticks_msec() < _gourmet_tenderize_until_msec:
		dmg_value = int(dmg_value * (100.0 + _gourmet_tenderize_pct) / 100.0)
	# on-hit specials: slow / mark / buff extension / heal
	if gourmet_slow_pct != 0 and Utils.get_chance_success(gourmet_slow_chance / 100.0):
		apply_gourmet_slow(gourmet_slow_pct, 1.0)
	if gourmet_tenderize != 0:
		_gourmet_tenderize_pct = int(max(_gourmet_tenderize_pct, gourmet_tenderize))
		_gourmet_tenderize_until_msec = int(max(_gourmet_tenderize_until_msec, OS.get_ticks_msec() + 3000))
	if from_player_index >= 0 and from_player_index < players_ref.size() and is_instance_valid(players_ref[from_player_index]):
		if gourmet_extend_buffs != 0:
			for extended_buff in players_ref[from_player_index]._food_buffs.values():
				# rest-of-wave buffs have no timer to extend - skip them
				if extended_buff.has("timer"):
					extended_buff["timer"].time_left += gourmet_extend_buffs / 10.0
		if gourmet_heal_on_hit != 0:
			var _healed_on_hit = players_ref[from_player_index].on_healing_effect(gourmet_heal_on_hit, Keys.empty_hash)
	var dmg_value_result = get_damage_value(dmg_value, from_player_index, args.armor_applied, args.dodgeable, is_crit, hitbox, args.is_burning)
	if is_one_shot:
		dmg_value_result.value = max(current_stats.health, dmg_value_result.value)
		if hitbox:
			hitbox.one_shot_something(self)
	var full_dmg_value = dmg_value_result.value
	dmg_taken = clamp(full_dmg_value, 0, current_stats.health)
	current_stats.health = max(0.0, current_stats.health - full_dmg_value) as int
	if (is_crit or is_one_shot) and hitbox:
		hitbox.critically_hit_something(self, dmg_taken)
		if hitbox.from != null:
			emit_signal("crit_effect", hitbox.from)
	if full_dmg_value > 0:
		flash()
	if args.custom_sound:
		sound = args.custom_sound
	SoundManager2D.play(sound, global_position, 0, 0.2)
	var final_knockback_amount = knockback_amount
	if final_knockback_amount < 0 and hitbox != null:
		final_knockback_amount = get_knockback_amount_based_on_distance_to_attacker(final_knockback_amount, hitbox, players_ref[from_player_index])
	elif knockback_piercing > 0:
		final_knockback_amount = get_increased_piercing_knockback_amount(knockback_amount, knockback_piercing, stats.knockback_resistance)
	knockback_vector = knockback_direction * final_knockback_amount
	emit_signal("health_updated", self, current_stats.health, max_stats.health)
	var hit_type = HitType.NORMAL
	for effect_behavior in effect_behaviors.get_children():
		var behavior_hit_type_result = effect_behavior.on_taken_damage(args)
		if behavior_hit_type_result != HitType.NORMAL:
			hit_type = behavior_hit_type_result
	if current_stats.health <= 0:
		if hitbox:
			hitbox.killed_something(self)
		_die_args_unit.knockback_vector = knockback_direction * max(knockback_amount, MIN_DEATH_KNOCKBACK_AMOUNT)
		_die_args_unit.killed_by_player_index = from_player_index
		_die_args_unit.killing_blow_dmg_value = full_dmg_value
		_die_args_unit.is_burning = args.is_burning
		# Gourmet DLC - carry the killing entity into the die args; DieArgs.from
		# was never populated on damage deaths, so turret-kill detection
		# (Gumball Machine) always saw null and never fired
		_die_args_unit.from = args.from
		call_deferred("die", _die_args_unit)
		_pending_die = true
		if from_player_index >= 0 and Utils.get_chance_success(RunData.get_player_effect(Keys.heal_on_kill_hash, from_player_index) / 100.0):
			RunData.emit_signal("healing_effect", 1, from_player_index, Keys.item_goblet_hash)
		if is_crit:
			assert (from_player_index >= 0)
			var gold_added = 0
			var gold_on_crit_kill_effects = RunData.get_player_effect(Keys.gold_on_crit_kill_hash, from_player_index)
			for effect in gold_on_crit_kill_effects:
				if Utils.get_chance_success(effect[1] / 100.0):
					gold_added += 1
					RunData.add_tracked_value(from_player_index, Keys.item_hunting_trophy_hash, 1)
			if Utils.get_chance_success(RunData.get_player_effect(Keys.heal_on_crit_kill_hash, from_player_index) / 100.0):
				RunData.emit_signal("healing_effect", 1, from_player_index, Keys.item_tentacle_hash)
			for effect in hitbox.effects:
				if effect.key_hash == Keys.gold_on_crit_kill_hash and randf() <= effect.value / 100.0:
					gold_added += 1
					hitbox.added_gold_on_crit(gold_added)
			if gold_added > 0:
				RunData.add_gold(gold_added, from_player_index)
				hit_type = HitType.GOLD_ON_CRIT_KILL
	emit_signal(
		"took_damage", 
		self, 
		full_dmg_value, 
		knockback_direction, 
		is_crit, 
		false, 
		false, 
		dmg_value_result.armor_did_something, 
		args, 
		hit_type, 
		is_one_shot
	)
	return [full_dmg_value, dmg_taken, false]
