# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://singletons/announcement_manager.gd"





func _on_announcements_fetched(result, _response_code, _headers, body) -> void :
	_http_request.disconnect("request_completed", self, "_on_announcements_fetched")
	if result != HTTPRequest.RESULT_SUCCESS or _response_code != 200:
		return
	var parsed = parse_json(body.get_string_from_utf8())
	if not parsed is Dictionary or not parsed.has("data"):
		return
	var data = parsed.data
	for announcement in data:
		if not announcement["id"] in ProgressData.read_announcements:
			var current_utc_unix: = Time.get_unix_time_from_system()
			var date_start_unix: = Time.get_unix_time_from_datetime_string(announcement["date_start"])
			var date_end_unix: = Time.get_unix_time_from_datetime_string(announcement["date_end"])
			if date_start_unix <= current_utc_unix and current_utc_unix <= date_end_unix:
				for platform in announcement["platforms"]:
					if platform["platform_name"].to_lower() == Platform.get_type_as_string().to_lower():
						_announcement_id = announcement["id"]
						add_translations(announcement)
						break
				break
