# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://singletons/item_service_get_shop_items_args.gd"


func _init(shop_items_by_player: Array, p_player_index: int):
	player_index = p_player_index
	count = ItemService.get_nb_shop_items(p_player_index)
	owned_and_shop_items = RunData.get_player_items(p_player_index)
	for shop_item in shop_items_by_player[p_player_index]:
		if shop_item[0] is ItemData:
			owned_and_shop_items.push_back(shop_item[0])
