# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://singletons/item_service.gd"


# Gourmet DLC - Blacksmith weapon ladder. Four extra rarities sit between and above
# the vanilla four. They use tier numbers 7-10 because 4/5/6 are already taken by
# Tier.DANGER_4 / DANGER_5 / NIGHTMARE.
const TIER_BS_GREEN = 7

const TIER_BS_ORANGE = 8

const TIER_BS_PINK = 9

const TIER_BS_GOLD = 10


# Ladder order, weakest to strongest. Position in this array is the progression
# step; the value is the real tier number stored on the weapon resource.
const BS_TIER_LADDER = [Tier.COMMON, TIER_BS_GREEN, Tier.UNCOMMON, TIER_BS_ORANGE,
						Tier.RARE, Tier.LEGENDARY, TIER_BS_PINK, TIER_BS_GOLD]

const VANILLA_TIER_LADDER = [Tier.COMMON, Tier.UNCOMMON, Tier.RARE, Tier.LEGENDARY]


# ==================== P2W DEBUG (2026-08-12) - REVERT AFTER TEST ====================
# Forces every P2W shop slot to a GOLD chest costing 1 (celebration testing).
# Revert = set false. Gates this file's fill branch + shop_item.gd debug pricing.
# =====================================================================================


# Gourmet DLC - The P2W chest system. Chests are deliberately absent from every
# registry (items/weapons/consumables arrays), so nothing but his own shop can
# ever roll one; they load on demand from the generated data file.
const P2WData = preload("res://items/custom/p2w/p2w_data.gd")

var _p2w_chests = {}



func get_p2w_chest(rung: int) -> ItemData:
	if not _p2w_chests.has(rung):
		_p2w_chests[rung] = load(P2WData.CHEST_PATHS[rung])
	# every offer is its OWN instance: same-rung chests share a my_id, and a
	# shared cached object meant a cursed twin could alias a locked uncursed
	# chest through id-matched erase/unlock (locked chest "turned cursed" on
	# reroll - user 2026-08-13)
	return _p2w_chests[rung].duplicate()



# The chest rarity roll rides the same wave-gated ladder walk the Blacksmith's
# weapons use (get_tier_from_wave with the ladder flag), then maps the rolled
# tier int back to its chest rung.
func get_p2w_rung_for_wave(wave: int, player_index: int, increase_tier: int = 0) -> int:
	var chest_tier = get_tier_from_wave(wave, player_index, increase_tier, true)
	var rung: int = 1
	for r in P2WData.RUNG_TIERS:
		if P2WData.RUNG_TIERS[r] == chest_tier:
			rung = r
	return rung



func get_p2w_chest_for_wave(wave: int, player_index: int, increase_tier: int = 0) -> ItemData:
	return get_p2w_chest(get_p2w_rung_for_wave(wave, player_index, increase_tier))



# What comes out of a chest. Rolled at PURCHASE (the ceremony later only reveals).
# The odds table is the honest one printed on the chest card. Item buckets come
# from the locked rarity spread (P2WData.RUNG_BY_ID); weapon pools are the real
# ladder tiers. An empty bucket walks DOWN one rung until something exists, so a
# chest can never come up empty.
# vanilla tier a rung maps to, for non-P2W players opening picked-up lootboxes:
# their weapon drops are plain vanilla-tier weapons with vanilla names
const P2W_VANILLA_TIER_OF_RUNG = {1: 0, 2: 0, 3: 1, 4: 1, 5: 2, 6: 3, 7: 3, 8: 3}



func p2w_roll_chest_drop(rung: int, player_index: int, chest_cursed: bool, vanilla_weapons: bool = false) -> Dictionary:
	var total: = 0
	for entry in P2WData.CHEST_ODDS[rung]:
		total += entry[1]
	var pick: int = Utils.randi_range(0, total - 1)
	var out_rung: int = rung
	for entry in P2WData.CHEST_ODDS[rung]:
		pick -= entry[1]
		if pick < 0:
			out_rung = entry[0]
			break
	var want_weapon: bool = Utils.randi_range(0, 99) < P2WData.WEAPON_CHANCE
	var item_cursed: bool = chest_cursed and Utils.randi_range(0, 99) < P2WData.CURSED_ITEM_CHANCE
	# Build-awareness (user 2026-08-11), strictly WITHIN the rolled rarity so the
	# printed rung odds stay exactly true:
	# - items: tag-weighted pick. Every candidate keeps base weight 1 (nothing
	#   can ever be excluded), +0.25 per tag shared with the opener's owned
	#   items, hard-capped at 2.0 - at most twice as likely as an unrelated item.
	# - weapons: the vanilla same-class chance (35%) restricts to owned classes,
	#   falling back to the full pool when nothing matches.
	var owned_tags: = {}
	for owned_item in RunData.get_player_items_ref(player_index):
		if owned_item is ItemData and not owned_item is WeaponData and not owned_item is CharacterData:
			for owned_tag in owned_item.tags:
				owned_tags[owned_tag] = true
	var probe: int = out_rung
	while probe >= 1:
		var ladder_tier: int = P2W_VANILLA_TIER_OF_RUNG[probe] if vanilla_weapons else P2WData.RUNG_TIERS[probe]
		if want_weapon:
			var weapon_pool: = []
			for weapon in weapons:
				if weapon.tier == ladder_tier and ProgressData.weapons_unlocked.has(weapon.weapon_id_hash):
					weapon_pool.push_back(weapon)
			if not weapon_pool.empty():
				if Utils.get_chance_success(CHANCE_SAME_WEAPON_SET):
					var owned_sets: = {}
					for owned_weapon in RunData.get_player_weapons_ref(player_index):
						for owned_set in owned_weapon.sets:
							owned_sets[owned_set.my_id] = true
					if not owned_sets.empty():
						var class_pool: = []
						for weapon_cand in weapon_pool:
							for cand_set in weapon_cand.sets:
								if owned_sets.has(cand_set.my_id):
									class_pool.push_back(weapon_cand)
									break
						if not class_pool.empty():
							weapon_pool = class_pool
				var rolled_weapon = Utils.get_rand_element(weapon_pool)
				return {"kind": "weapon", "id": rolled_weapon.my_id, "item_cursed": item_cursed}
		var item_pool: = []
		for item in items:
			if not item.can_be_looted:
				continue
			if int(P2WData.RUNG_BY_ID.get(item.my_id, 0)) != probe:
				continue
			if item.max_nb != - 1 and RunData.get_nb_item(item.my_id_hash, player_index) >= item.max_nb:
				continue
			item_pool.push_back(item)
		if not item_pool.empty():
			var total_weight: float = 0.0
			var pool_weights: = []
			for item_cand in item_pool:
				var cand_weight: float = 1.0
				for cand_tag in item_cand.tags:
					if owned_tags.has(cand_tag):
						cand_weight += 0.25
				cand_weight = min(cand_weight, 2.0)
				pool_weights.push_back(cand_weight)
				total_weight += cand_weight
			var pick_roll: float = rand_range(0.0, total_weight)
			var rolled_item = item_pool[item_pool.size() - 1]
			for pool_i in item_pool.size():
				pick_roll -= pool_weights[pool_i]
				if pick_roll <= 0.0:
					rolled_item = item_pool[pool_i]
					break
			return {"kind": "item", "id": rolled_item.my_id, "item_cursed": item_cursed}
		# nothing at this rung for this roll: a weapon-roll falls back to items at
		# the same rung first (loop above), then the whole probe steps down
		want_weapon = false
		probe -= 1
	# unreachable in practice (rung 1 always has uncapped items), but never crash a shop
	return {"kind": "item", "id": "item_potato", "item_cursed": false}





const TIER_BS_GREEN_COLOR = Color(122.0 / 255, 219.0 / 255, 88.0 / 255, 1)

const TIER_BS_ORANGE_COLOR = Color(0.0 / 255, 210.0 / 255, 190.0 / 255, 1)  # teal (was orange - too close to gold, user 2026-08-10)

const TIER_BS_PINK_COLOR = Color(255.0 / 255, 105.0 / 255, 199.0 / 255, 1)

const TIER_BS_GOLD_COLOR = Color(255.0 / 255, 205.0 / 255, 60.0 / 255, 1)


const TIER_BS_GREEN_COLOR_DARK = Color(12.0 / 255, 26.0 / 255, 9.0 / 255, 1)

const TIER_BS_ORANGE_COLOR_DARK = Color(4.0 / 255, 26.0 / 255, 24.0 / 255, 1)

const TIER_BS_PINK_COLOR_DARK = Color(33.0 / 255, 13.0 / 255, 26.0 / 255, 1)

const TIER_BS_GOLD_COLOR_DARK = Color(33.0 / 255, 26.0 / 255, 7.0 / 255, 1)

# Gourmet DLC - The Freeloader sees twice the menu but may only take one thing from it.
# Everything that used to size itself off NB_SHOP_ITEMS now asks get_nb_shop_items().
const NB_SHOP_ITEMS_FREELOADER: = 8

# ... and the same doubling on the level-up draft. Was a bare literal 4 passed into
# get_upgrades() from upgrades_ui_player_container.
const NB_UPGRADE_OPTIONS: = 4

const NB_UPGRADE_OPTIONS_FREELOADER: = 8

# Gourmet DLC - the Freeloader keeps TWO upgrades from each level-up draft.
const NB_UPGRADE_PICKS_FREELOADER: = 2

# Gourmet DLC - items whose purpose is to hand you debt (loans) are free to buy; you already
# owe the debt, so a purchase price on top means paying extra. Add future loan ids here.
const FREE_DEBT_ITEM_IDS: = ["item_bank_loan"]

export (Array, Resource) var foods



func _ready() -> void :
	_gourmet_core_remove_vanilla_items()
	Utils.reset_stat_keys()
	for weapon in weapons:
		if weapon.upgrades_into != null:
			weapon.upgrades_into.previous_upgrade = weapon




func reset_tiers_data() -> void :
		_gourmet_core_remove_vanilla_items()
		_tiers_data = [
		[[], [], [], [], [], 0, 1.0, 0.0, 1.0], 
		[[], [], [], [], [], 0, 0.0, 0.06, 0.6], 
		[[], [], [], [], [], 2, 0.0, 0.02, 0.25],
		[[], [], [], [], [], 6, 0.0, 0.0023, 0.08],
		# Gourmet DLC - rows 4/5/6 are unused padding: those indices are already taken
		# by Tier.DANGER_4 / DANGER_5 / NIGHTMARE, so the Blacksmith's extra weapon
		# tiers start at 7 to avoid colliding with the danger colours and checks.
		[[], [], [], [], [], 0, 0.0, 0.0, 0.0],
		[[], [], [], [], [], 0, 0.0, 0.0, 0.0],
		[[], [], [], [], [], 0, 0.0, 0.0, 0.0],
		# Blacksmith-only ladder tiers. Only rolled when the player is the Blacksmith
		# (see get_tier_from_wave), so no other character can ever draw them.
		[[], [], [], [], [], 0, 0.0, 0.09, 0.75],
		[[], [], [], [], [], 1, 0.0, 0.035, 0.4],
		[[], [], [], [], [], 10, 0.0, 0.0012, 0.04],
		[[], [], [], [], [], 15, 0.0, 0.0006, 0.02]
	]



func init_unlocked_pool() -> void :
	_gourmet_core_remove_vanilla_items()
	reset_tiers_data()
	for item in items:
		if not item.can_be_looted:
			continue
		if ProgressData.items_unlocked.has(item.my_id_hash) and item.max_nb != 0:
			_tiers_data[item.tier][TierData.ALL_ITEMS].push_back(item)
			_tiers_data[item.tier][TierData.ITEMS].push_back(item)
	for weapon in weapons:
		if not weapon.can_be_looted:
			continue
		if ProgressData.weapons_unlocked.size() > 0:
			assert (ProgressData.weapons_unlocked[0] is int)
		if ProgressData.weapons_unlocked.has(weapon.weapon_id_hash):
			_tiers_data[weapon.tier][TierData.ALL_ITEMS].push_back(weapon)
			_tiers_data[weapon.tier][TierData.WEAPONS].push_back(weapon)
	for upgrade in upgrades:
		if ProgressData.upgrades_unlocked.has(upgrade.upgrade_id_hash):
			_tiers_data[upgrade.tier][TierData.UPGRADES].push_back(upgrade)
	for consumable in consumables:
		if ProgressData.consumables_unlocked.has(consumable.my_id_hash):
			_tiers_data[consumable.tier][TierData.CONSUMABLES].push_back(consumable)






# Gourmet DLC - foods are consumables that spawn only via their spawner item,
# so they live in their own registry and never enter the tier drop pools.
func get_food_from_hash(food_id_hash: int) -> ConsumableData:
	for food in foods:
		if food.get_my_id_hash() == food_id_hash:
			return food
	return null

	


# Gourmet DLC - how many offerings this player's shop holds. Character-aware replacement
# for the old NB_SHOP_ITEMS const, which was read in three places.
func get_nb_shop_items(player_index: int) -> int:
	# Gourmet DLC - the Freeloader's 8-slot menu, in coop too. Coop used to be excluded
	# because the reflow squished cards; it now lays out as 2 wide x 4 tall there (the shop
	# grid narrows its per-card minimum for the quarter-screen container), so all 8 fit on
	# screen with no scrolling.
	if RunData.is_freeloader(player_index):
		return NB_SHOP_ITEMS_FREELOADER
	# Gourmet DLC - Wildcard (Big Delivery): a shop-scoped slot delta. Clamped to the range
	# the shop grid can actually lay out; the Freeloader's widened menu is handled above and
	# deliberately not stacked with this.
	var slot_delta: int = int(RunData.get_player_effect(Keys.special_shop_slots_hash, player_index))
	if slot_delta != 0 and not RunData.is_coop_run:
		return int(clamp(NB_SHOP_ITEMS + slot_delta, 1, 8))
	return NB_SHOP_ITEMS





# Gourmet DLC - how many choices this player's level-up draft offers.
func get_nb_upgrade_options(player_index: int) -> int:
	# 8 in coop as well: the draft grid drops to 2 columns there, giving 2 wide x 4 tall.
	if RunData.is_freeloader(player_index):
		return NB_UPGRADE_OPTIONS_FREELOADER
	return NB_UPGRADE_OPTIONS




# Gourmet DLC - how many upgrades this player keeps per level-up draft (Freeloader: 2).
func get_nb_upgrade_picks(player_index: int) -> int:
	if RunData.is_freeloader(player_index):
		return NB_UPGRADE_PICKS_FREELOADER
	return 1




func get_player_shop_items(wave: int, player_index: int, args: ItemServiceGetShopItemsArgs) -> Array:
	# Gourmet DLC - The P2W: his shop sells ONLY Chests. Every slot rolls a chest
	# rarity on the extended ladder and returns early, so guaranteed items, the
	# weapon quota, the Mime mirror and the spawner floor never apply to him.
	if RunData.is_p2w(player_index):
		var chest_offers = []
		for i in args.count:
			# chests curse exactly like items: the vanilla stat_curse-based shop
			# roll (apply_item_effect_modifications), no flat rate (user 2026-08-11)
			var chest_offer = apply_item_effect_modifications(get_p2w_chest_for_wave(wave, player_index, args.increase_tier), player_index)
			chest_offers.push_back([chest_offer, wave])
		return chest_offers
	var new_items: = []
	var nb_weapons_guaranteed = 0
	var nb_weapons_added = 0
	var guaranteed_items = RunData.get_player_effect(Keys.guaranteed_shop_items_hash, player_index).duplicate()
	var nb_locked_weapons = 0
	for locked_item in args.locked_items:
		if locked_item[0] is WeaponData:
			nb_locked_weapons += 1
	if RunData.current_wave <= MAX_WAVE_TWO_WEAPONS_GUARANTEED:
		nb_weapons_guaranteed = 2
	elif RunData.current_wave <= MAX_WAVE_ONE_WEAPON_GUARANTEED:
		nb_weapons_guaranteed = 1
	var minimum_weapons_in_shop = RunData.get_player_effect(Keys.minimum_weapons_in_shop_hash, player_index)
	nb_weapons_guaranteed = max(nb_weapons_guaranteed, minimum_weapons_in_shop)
	for i in args.count:
		var type
		if RunData.current_wave <= MAX_WAVE_TWO_WEAPONS_GUARANTEED:
			type = TierData.WEAPONS if (nb_weapons_added + nb_locked_weapons < nb_weapons_guaranteed) else TierData.ITEMS
		elif guaranteed_items.size() > 0:
			type = TierData.ITEMS
		else:
			type = TierData.WEAPONS if (Utils.get_chance_success(CHANCE_WEAPON) or nb_weapons_added + nb_locked_weapons < nb_weapons_guaranteed) else TierData.ITEMS
		# Gourmet DLC - Blacksmith: his shop is weapons-only. He forges rather than
		# collecting items, so override the vanilla weapon/item roll outright. The
		# no-free-slots fallback to ITEMS is skipped for him too - a full Blacksmith
		# can still forge two weapons into one, so weapons stay the useful offer.
		var bs_char = RunData.get_player_character(player_index)
		var bs_weapons_only: bool = bs_char != null and bs_char.my_id == "character_blacksmith"
		if bs_weapons_only:
			type = TierData.WEAPONS
		if type == TierData.WEAPONS:
			nb_weapons_added += 1
		if not RunData.player_has_weapon_slots(player_index) and not bs_weapons_only:
			type = TierData.ITEMS
		var new_item
		if type == TierData.ITEMS and guaranteed_items.size() > 0:
			new_item = apply_item_effect_modifications(get_element(items, guaranteed_items[0][0]), player_index)
			guaranteed_items.pop_front()
		else:
			var rand_item_args: = GetRandItemForWaveArgs.new()
			rand_item_args.excluded_items = args.prev_items + new_items
			rand_item_args.owned_and_shop_items = args.owned_and_shop_items
			rand_item_args.increase_tier = args.increase_tier
			new_item = _get_rand_item_for_wave(wave, player_index, type, rand_item_args)
		new_items.push_back([new_item, wave])
	# Gourmet DLC - Mime: every shop contains exactly one Magic Mirror
	var mime_character = RunData.get_player_character(player_index)
	if mime_character != null and mime_character.my_id == "character_mime":
		var has_mirror: = false
		for locked_item in args.locked_items:
			if locked_item[0] != null and locked_item[0].my_id == "item_mirror":
				has_mirror = true
		for shop_entry in new_items:
			if shop_entry[0] != null and shop_entry[0].my_id == "item_mirror":
				has_mirror = true
		if not has_mirror:
			for item in items:
				if item.my_id == "item_mirror":
					for i in range(new_items.size() - 1, - 1, - 1):
						if not new_items[i][0] is WeaponData:
							new_items[i] = [item, wave]
							has_mirror = true
							break
					if not has_mirror and new_items.size() > 0:
						new_items[new_items.size() - 1] = [item, wave]
					break
	# Gourmet DLC - food characters: ONE roll per shop puts a guaranteed spawner in it. This
	# is a FLOOR, not a bias - the normal spawner appearances are rolled above and untouched,
	# so a shop that already offers one is left exactly as it came out. It only ever fires on
	# a shop that rolled none, which is the case the food characters actually lose runs to.
	var spawner_chance: int = RunData.get_player_effect(Keys.spawner_shop_chance_hash, player_index)
	if spawner_chance > 0 and Utils.get_chance_success(spawner_chance / 100.0):
		var has_spawner: = false
		# `tags` lives on ItemData only - a weapon in the shop or on a lock has no such
		# property, so every read of it is type-gated first.
		for locked_item in args.locked_items:
			if locked_item[0] is ItemData and locked_item[0].tags.has("spawner"):
				has_spawner = true
				break
		if not has_spawner:
			for shop_entry in new_items:
				if shop_entry[0] is ItemData and shop_entry[0].tags.has("spawner"):
					has_spawner = true
					break
		if not has_spawner:
			var spawner_args: = GetRandItemForWaveArgs.new()
			spawner_args.excluded_items = args.prev_items + new_items
			spawner_args.owned_and_shop_items = args.owned_and_shop_items
			spawner_args.increase_tier = args.increase_tier
			spawner_args.forced_shop_tag = "spawner"
			var spawner_item = _get_rand_item_for_wave(wave, player_index, TierData.ITEMS, spawner_args)
			# The tier can hold no eligible spawner at all (all owned to their cap, or a tier
			# with none registered). _get_rand_item_for_wave then falls back to its backup pool
			# and hands back an ordinary item, so check what actually came out - forcing that
			# into a slot would delete an offer to grant nothing.
			if spawner_item is ItemData and spawner_item.tags.has("spawner"):
				# Only ever overwrite an item slot. Waves 1-2 guarantee weapons, and eating one
				# of those to honour a 30% nicety would break a stronger promise.
				for i in range(new_items.size() - 1, - 1, - 1):
					if not new_items[i][0] is WeaponData:
						new_items[i] = [spawner_item, wave]
						break
	return new_items





func _get_rand_item_for_wave(wave: int, player_index: int, type: int, args: GetRandItemForWaveArgs) -> ItemParentData:
	var player_character = RunData.get_player_character(player_index)
	var rand_wanted = randf()
	# only the weapon roll may use the Blacksmith ladder - items/upgrades/consumables
	# have no entries at tiers 7-10 and would come back null
	var item_tier = get_tier_from_wave(wave, player_index, args.increase_tier,
									   type == TierData.WEAPONS)
	if args.fixed_tier != - 1:
		item_tier = args.fixed_tier
	if type == TierData.WEAPONS:
		var min_weapon_tier = RunData.get_player_effect(Keys.min_weapon_tier_hash, player_index)
		var max_weapon_tier = RunData.get_player_effect(Keys.max_weapon_tier_hash, player_index)
		item_tier = clamp(item_tier, min_weapon_tier, max_weapon_tier)
	var banned_items = RunData.players_data[player_index].banned_items
	var pool = get_pool(item_tier, type)
	var backup_pool = get_pool(item_tier, type)
	var items_to_remove = []
	if banned_items.size() > 0:
		for item_id in banned_items:
			if item_id is String:
				var item_id_hash = Keys.generate_hash(item_id)
				pool = remove_element_by_id(pool, item_id_hash)
				backup_pool = remove_element_by_id(backup_pool, item_id_hash)
			else:
				pool = remove_element_by_id(pool, item_id)
				backup_pool = remove_element_by_id(backup_pool, item_id)
	for shop_item in args.excluded_items:
		pool = remove_element_by_id_with_item(pool, shop_item[0])
		backup_pool = remove_element_by_id_with_item(pool, shop_item[0])
	if type == TierData.WEAPONS:
		var bonus_chance_same_weapon_set = max(0, (MAX_WAVE_ONE_WEAPON_GUARANTEED + 1 - RunData.current_wave) * (BONUS_CHANCE_SAME_WEAPON_SET / MAX_WAVE_ONE_WEAPON_GUARANTEED))
		var chance_same_weapon_set = CHANCE_SAME_WEAPON_SET + bonus_chance_same_weapon_set
		var bonus_chance_same_weapon = max(0, (MAX_WAVE_ONE_WEAPON_GUARANTEED + 1 - RunData.current_wave) * (BONUS_CHANCE_SAME_WEAPON / MAX_WAVE_ONE_WEAPON_GUARANTEED))
		var chance_same_weapon = CHANCE_SAME_WEAPON + bonus_chance_same_weapon
		var no_melee_weapons: bool = RunData.get_player_effect_bool(Keys.no_melee_weapons_hash, player_index)
		var no_ranged_weapons: bool = RunData.get_player_effect_bool(Keys.no_ranged_weapons_hash, player_index)
		var no_duplicate_weapons: bool = RunData.get_player_effect_bool(Keys.no_duplicate_weapons_hash, player_index)
		var no_structures: bool = RunData.get_player_effect(Keys.remove_shop_items_hash, player_index).has(Keys.structure_hash)
		var player_sets: Array = RunData.get_player_sets(player_index)
		var unique_weapon_ids: Dictionary = RunData.get_unique_weapon_ids(player_index)
		for item in pool:
			if no_melee_weapons and item.type == WeaponType.MELEE:
				backup_pool = remove_element_by_id_with_item(backup_pool, item)
				items_to_remove.push_back(item)
				continue
			if no_ranged_weapons and item.type == WeaponType.RANGED:
				backup_pool = remove_element_by_id_with_item(backup_pool, item)
				items_to_remove.push_back(item)
				continue
			if no_duplicate_weapons:
				for weapon in unique_weapon_ids.values():
					if item.weapon_id_hash == weapon.weapon_id_hash and item.tier < weapon.tier:
						backup_pool = remove_element_by_id_with_item(backup_pool, item)
						items_to_remove.push_back(item)
						break
					elif item.my_id_hash == weapon.my_id_hash and weapon.upgrades_into == null:
						backup_pool = remove_element_by_id_with_item(backup_pool, item)
						items_to_remove.push_back(item)
						break
			if no_structures and EntityService.is_weapon_spawning_structure(item):
				backup_pool = remove_element_by_id_with_item(backup_pool, item)
				items_to_remove.append(item)
			if rand_wanted < chance_same_weapon:
				if not item.weapon_id in unique_weapon_ids:
					items_to_remove.push_back(item)
					continue
			elif rand_wanted < chance_same_weapon_set:
				var remove: = true
				for set in item.sets:
					if set.my_id_hash in player_sets:
						remove = false
				if remove:
					items_to_remove.push_back(item)
					continue
	elif type == TierData.ITEMS:
		var wanted_item_tag_chance = CHANCE_WANTED_ITEM_TAG
		if RunData.get_player_effects(player_index).has(Keys.stat_boosted_wanted_item_tag_hash) and RunData.get_player_effect_bool(Keys.stat_boosted_wanted_item_tag_hash, player_index):
			wanted_item_tag_chance = BOOSTED_WANTED_ITEM_TAG
		if Utils.get_chance_success(wanted_item_tag_chance) and player_character.wanted_tags.size() > 0:
			for item in pool:
				var has_wanted_tag = false
				for tag in item.tags:
					if player_character.wanted_tags.has(tag):
						has_wanted_tag = true
						break
				if not has_wanted_tag:
					items_to_remove.push_back(item)
		# Gourmet DLC - the food characters' spawner help is a per-SHOP floor, not a per-slot
		# bias: see the spawner_shop_chance block at the end of get_player_shop_items. Rolling
		# it here (once per slot, restricting that slot's pool) stacked with the shop's normal
		# spawner rolls and skewed whole shops toward spawners.
		if args.forced_shop_tag != null:
			for item in pool:
				if not items_to_remove.has(item) and not item.tags.has(args.forced_shop_tag):
					items_to_remove.push_back(item)
		var remove_item_tags: Array = RunData.get_player_effect(Keys.remove_shop_items_hash, player_index)
		for tag_to_remove in remove_item_tags:
			for item in pool:
				if Keys.hash_to_string[tag_to_remove] in item.tags:
					items_to_remove.append(item)
		if RunData.current_wave < RunData.nb_of_waves:
			if player_character.banned_item_groups.size() > 0:
				for banned_item_group in player_character.banned_item_groups:
					if not banned_item_group in item_groups:
						print(str(banned_item_group) + " does not exist in ItemService.item_groups")
						continue
					for item in pool:
						if item_groups[banned_item_group].has(item.my_id):
							items_to_remove.append(item)
			if player_character.banned_items.size() > 0:
				for item in pool:
					if player_character.banned_items.has(item.my_id):
						items_to_remove.append(item)
		else:
			for item in pool:
				if banned_items_for_endless.has(item.my_id_hash):
					items_to_remove.append(item)
	var limited_items = get_limited_items(args.owned_and_shop_items)
	for key in limited_items:
		# Gourmet DLC - read the effective cap, not the raw one, so the Picky Eater's
		# doubled spawner limit keeps his spawners in the pool past their printed max
		if limited_items[key][1] >= RunData.get_item_max_nb(limited_items[key][0], player_index):
			backup_pool = remove_element_by_id_with_item(backup_pool, limited_items[key][0])
			items_to_remove.push_back(limited_items[key][0])
	for item in items_to_remove:
		pool = remove_element_by_id_with_item(pool, item)
	var elt
	if pool.size() == 0:
		if backup_pool.size() > 0:
			elt = Utils.get_rand_element(backup_pool)
		else:
			elt = Utils.get_rand_element(_tiers_data[item_tier][type])
	else:
		elt = Utils.get_rand_element(pool)
		if elt.my_id_hash == Keys.item_axolotl_hash and randf() < 0.5:
			elt = Utils.get_rand_element(pool)
	if DebugService.force_item_in_shop != "" and randf() < 0.5:
		elt = get_element(items, Keys.generate_hash(DebugService.force_item_in_shop))
		if elt == null:
			elt = get_element(weapons, Keys.generate_hash(DebugService.force_item_in_shop))
	if elt.my_id_hash == Keys.item_axolotl_hash and elt.effects.size() > 0 and "stats_swapped" in elt.effects[0]:
		elt.effects[0].stats_swapped = []
	return apply_item_effect_modifications(elt, player_index)





func get_tier_from_wave(wave: int, player_index: int, increase_tier: = 0, use_bs_ladder: = false) -> int:
	var rand = rand_range(0.0, 1.0)
	var luck = Utils.get_stat(Keys.stat_luck_hash, player_index) / 100.0
	# Gourmet DLC - the Blacksmith rolls an 8-step weapon ladder that interleaves four
	# extra tiers (7 green, 8 orange, 9 pink, 10 gold) with the vanilla four. Every
	# other character iterates the vanilla ladder only, so the extra tiers are
	# unreachable for them and the rest of the game is untouched. Never iterate
	# _tiers_data directly here - it now has padding rows that must never be rolled.
	# use_bs_ladder MUST stay opt-in and weapons-only. The extra tiers exist solely
	# as weapon rarities - _tiers_data[7..10] has no items, upgrades or consumables -
	# so letting level-up upgrades roll them returns null from get_rand_element and
	# the card renders the scene's placeholder labels before crashing on null.
	var bs_tier_char = RunData.get_player_character(player_index)
	# P2W rides the same ladder for his CHEST rarity roll (his shop never rolls
	# weapons or items directly, so this cannot leak tier-7..10 into other pools).
	var ladder: Array = BS_TIER_LADDER if (use_bs_ladder and bs_tier_char != null and (bs_tier_char.my_id == "character_blacksmith" or bs_tier_char.my_id == "character_p2w")) else VANILLA_TIER_LADDER
	var tier: int = Tier.COMMON
	for pos in range(ladder.size() - 1, - 1, - 1):
		var i = ladder[pos]
		var tier_data = _tiers_data[i]
		var wave_base_chance = max(0.0, ((wave - 1) - tier_data[TierData.MIN_WAVE]) * tier_data[TierData.WAVE_BONUS_CHANCE])
		var wave_chance = 0.0
		if luck >= 0:
			wave_chance = wave_base_chance * (1 + luck)
		else:
			wave_chance = wave_base_chance / (1 + abs(luck))
		var chance = tier_data[TierData.BASE_CHANCE] + wave_chance
		var max_chance = tier_data[TierData.MAX_CHANCE]
		if rand <= min(chance, max_chance):
			tier = i
			break
	# Gourmet DLC - increase_tier steps along the active ladder rather than the raw
	# tier number, so a +1 on the Blacksmith moves green -> vanilla T2 rather than
	# jumping out of his ladder entirely.
	if increase_tier != 0:
		var cur_pos = ladder.find(tier)
		if cur_pos == - 1:
			cur_pos = 0
		tier = ladder[clamp(cur_pos + increase_tier, 0, ladder.size() - 1)]
	return tier





# Gourmet DLC - tier ladder helpers. Anything that advances a weapon by "one tier"
# must step the player's ladder rather than doing tier + 1: for the Blacksmith the
# ladder is 0,7,1,8,2,3,9,10, so tier + 1 from vanilla T4 lands on 4 (DANGER_4, an
# empty pool) instead of pink, and from T1 it skips green entirely.
func get_tier_ladder(player_index: int) -> Array:
	# Blacksmith (forging) and P2W (chest drops) both live on the 8-step ladder:
	# their weapon naming, merging and tier-stepping all walk it.
	var c = RunData.get_player_character(player_index)
	return BS_TIER_LADDER if (c != null and (c.my_id == "character_blacksmith" or c.my_id == "character_p2w")) else VANILLA_TIER_LADDER



func get_next_tier(tier: int, player_index: int) -> int:
	var ladder: = get_tier_ladder(player_index)
	var pos: = ladder.find(tier)
	if pos == - 1 or pos >= ladder.size() - 1:
		return - 1
	return ladder[pos + 1]



# 1-based position on the ladder - what the UI should call this tier.
func get_tier_step(tier: int, player_index: int) -> int:
	var pos: = get_tier_ladder(player_index).find(tier)
	return (pos + 1) if pos != - 1 else (tier + 1)



func get_weapon_at_tier(weapon_id: String, tier: int):
	for w in weapons:
		if w.weapon_id == weapon_id and w.tier == tier:
			return w
	return null



# The weapon this one upgrades into for THIS player. Falls back to the resource's
# own upgrades_into so non-Blacksmith behaviour is bit-for-bit unchanged.
func get_upgrade_target(weapon_data, player_index: int):
	var nt: = get_next_tier(weapon_data.tier, player_index)
	if nt != - 1:
		var w = get_weapon_at_tier(weapon_data.weapon_id, nt)
		if w != null:
			return w
	return weapon_data.upgrades_into



func can_upgrade_further(weapon_data, player_index: int) -> bool:
	return get_upgrade_target(weapon_data, player_index) != null



func get_color_from_tier(tier: int, dark_version: bool = false) -> Color:
	match tier:
		Tier.UNCOMMON:
			return Color(ProgressData.settings.tier_1_color_dark) if dark_version else Color(ProgressData.settings.tier_1_color)
		Tier.RARE:
			return Color(ProgressData.settings.tier_2_color_dark) if dark_version else Color(ProgressData.settings.tier_2_color)
		Tier.LEGENDARY:
			return Color(ProgressData.settings.tier_3_color_dark) if dark_version else Color(ProgressData.settings.tier_3_color)
		Tier.DANGER_0:
			return Color(ProgressData.settings.tier_0_color_dark) if dark_version else Color(ProgressData.settings.tier_0_color)
		Tier.DANGER_4:
			return Color(ProgressData.settings.tier_4_color_dark) if dark_version else Color(ProgressData.settings.tier_4_color)
		Tier.DANGER_5, Tier.NIGHTMARE:
			return Color(ProgressData.settings.tier_5_color_dark) if dark_version else Color(ProgressData.settings.tier_5_color)
		# Gourmet DLC - Blacksmith ladder rarities. Fixed colours rather than the
		# player's configurable tier palette, since those slots are already used.
		TIER_BS_GREEN:
			return TIER_BS_GREEN_COLOR_DARK if dark_version else TIER_BS_GREEN_COLOR
		TIER_BS_ORANGE:
			return TIER_BS_ORANGE_COLOR_DARK if dark_version else TIER_BS_ORANGE_COLOR
		TIER_BS_PINK:
			return TIER_BS_PINK_COLOR_DARK if dark_version else TIER_BS_PINK_COLOR
		TIER_BS_GOLD:
			return TIER_BS_GOLD_COLOR_DARK if dark_version else TIER_BS_GOLD_COLOR
		_:
			return Color.white



# Gourmet DLC - P2W: his item copies carry their LADDER tier so the custom
# rarity shows everywhere (name color, inventory frame, popups) and survives
# saves (per-item tier serializes). Weapons already carry real ladder tiers.
func p2w_retier_item(item_data: ItemParentData) -> ItemParentData:
	if item_data == null or item_data is WeaponData:
		return item_data
	var rung: int = int(P2WData.RUNG_BY_ID.get(item_data.my_id, 0))
	if rung <= 0:
		return item_data
	var ladder_tier: int = P2WData.RUNG_TIERS[rung]
	if item_data.tier == ladder_tier:
		return item_data
	var retiered = item_data.duplicate()
	retiered.tier = ladder_tier
	return retiered



func get_tier_text(tier: int) -> String:
	# Gourmet DLC - the four ladder rarities carry their own names
	if tier == TIER_BS_GREEN: return "P2W_TIER_GREEN"
	if tier == TIER_BS_ORANGE: return "P2W_TIER_TEAL"
	if tier == TIER_BS_PINK: return "P2W_TIER_PINK"
	if tier == TIER_BS_GOLD: return "P2W_TIER_GOLD"
	if tier == 0: return "TIER_COMMON"
	elif tier == 1: return "TIER_UNCOMMON"
	elif tier == 2: return "TIER_RARE"
	else: return "TIER_LEGENDARY"



func get_tier_number(tier: int, player_index: int = - 1, for_weapon: bool = false) -> String:
	# Gourmet DLC - in a Blacksmith/P2W run the ladder is 8 steps long, so WEAPONS are named
	# I..VIII by ladder POSITION; without it every tier above 2 fell through to "IV".
	# Two independent gates, both required - each fixes a different bug:
	#   for_weapon   : WEAPONS ONLY. Level-up upgrades and items keep vanilla numbering; the
	#                  unqualified gate renamed "Fingers III" to "Fingers V".
	#   player_index : the ladder belongs to the OWNER of the card. A run-level check renamed
	#                  every other player's weapons in coop. -1 means "no owner context"
	#                  (codex, upgrades, anything non-weapon) and always gets vanilla naming.
	# Vanilla runs keep vanilla naming exactly: no numeral at T1, then II/III/IV.
	if for_weapon and player_index >= 0 and RunData.uses_tier_ladder(player_index):
		var pos: = BS_TIER_LADDER.find(tier)
		if pos != - 1:
			return ["I", "II", "III", "IV", "V", "VI", "VII", "VIII"][pos]
	if tier == 0: return ""
	elif tier == 1: return "II"
	elif tier == 2: return "III"
	else: return "IV"


func get_value(wave: int, base_value: int, player_index: int, affected_by_items_price_stat: bool, is_weapon: bool, item_id: int = Keys.empty_hash) -> int:
	# Gourmet DLC - nothing has a price for the Freeloader. Returned at the root so every
	# caller agrees on zero (shop card, coupon maths, item popups), not just the shop card.
	if RunData.is_freeloader(player_index):
		return 0
	# Gourmet DLC - a loan's whole job is to hand you debt; charging materials to take it means
	# paying extra on top of what you already owe. Debt-granting items are free to buy, at the
	# root so the shop card, coupon maths and popups all agree (like the Freeloader case above).
	if item_id != Keys.empty_hash and FREE_DEBT_ITEM_IDS.has(Keys.hash_to_string.get(item_id, "")):
		return 0
	var value_after_weapon_price = base_value
	var specific_item_price_factor = 0
	var items_price_factor = 1.0
	var weapons_price = RunData.get_player_effect(Keys.weapons_price_hash, player_index)
	value_after_weapon_price = base_value if not is_weapon or not affected_by_items_price_stat else base_value * (1.0 + weapons_price / 100.0)
	if item_id != Keys.empty_hash:
		for specific_item_price in RunData.get_player_effect(Keys.specific_items_price_hash, player_index):
			if Keys.hash_to_string[specific_item_price[0]] in Keys.hash_to_string[item_id]:
				specific_item_price_factor = specific_item_price[1]
				break
	var items_price = RunData.get_player_effect(Keys.items_price_hash, player_index)
	items_price_factor = 1.0 + (items_price + specific_item_price_factor) / 100.0 if affected_by_items_price_stat else 1.0
	var base_inflation = 0.1
	var inflation_modifier = RunData.get_player_effect(Keys.inflation_modifier_hash, 0)
	if (inflation_modifier > 0):
		base_inflation = (1.0 + float(inflation_modifier / 100.0)) / 10.0
	var endless_factor = RunData.get_endless_factor(wave) / 5.0 if affected_by_items_price_stat else 0.0
	return max(1.0, ((value_after_weapon_price + wave + (value_after_weapon_price * wave * base_inflation)) * items_price_factor * (1 + endless_factor))) as int



func get_recycling_value(wave: int, from_value: int, player_index: int, is_weapon: bool = false, affected_by_items_price_stat: bool = true) -> int:
	# Gourmet DLC - the Freeloader receives no materials from recycling, so the Recycle
	# button must not advertise any. Needs its own gate rather than riding on get_value
	# returning 0, because both the max(1.0, ...) below and the from_value == 1 early
	# return would resurrect a value of 1.
	if RunData.is_freeloader(player_index):
		return 0
	var actually_affected = affected_by_items_price_stat and RunData.current_wave <= RunData.nb_of_waves
	var recycling_gains = RunData.get_player_effect(Keys.recycling_gains_hash, player_index)
	var shop_value = get_value(wave, from_value, player_index, affected_by_items_price_stat, is_weapon)
	var recycling_value = max(1.0, (get_value(wave, from_value, player_index, actually_affected, is_weapon) * clamp(0.25 + recycling_gains / 100.0, 0.01, 1.0))) as int
	if from_value == 1:
		return 1
	return min(shop_value, recycling_value) as int

func _init() -> void :
	_gourmet_merge_item_groups()

func _gourmet_merge_item_groups() -> void :
	item_groups["lifesteal"] = ["item_butterfly", "item_bat", "item_whetstone", "item_decomposing_flesh", "item_bloody_hand", "item_fresh_meat", "item_vampire_fang"]
	item_groups["lifesteal_and_hp_regeneration"] = ["item_blood_leech", "item_mosquito_jar"]
	item_groups["hp_regeneration"] = ["item_mushroom", "item_plant", "item_sad_tomato", "item_medikit", "item_fairy", "item_potion", "item_fried_rice", "item_baby_squid", "item_coral", "item_penguin", "item_iron_lung", "item_meal_in_a_pill"]
	item_groups["consumable_heal"] = ["item_jerky", "item_weird_food", "item_lemonade", "item_fruit_basket", "item_chicken_soup", "item_buffet_insurance"]

# --- GourmetCore runtime patch: the 5 vanilla items removed by the mod ---
# (was: pruned from item_service.tscn's items array; a mod cannot ship a scene)
const GOURMET_REMOVED_VANILLA_ITEMS = ["item_cake", "item_coffee",
	"item_fried_rice", "item_honey", "item_fresh_meat"]
var _gourmet_vanilla_items_pruned: = false

func _gourmet_core_remove_vanilla_items() -> void :
	if _gourmet_vanilla_items_pruned:
		return
	if items.empty():
		return
	_gourmet_vanilla_items_pruned = true
	var kept = []
	for i in items:
		if not GOURMET_REMOVED_VANILLA_ITEMS.has(i.my_id):
			kept.push_back(i)
	items = kept
