# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://singletons/keys.gd"

var stat_appetite_hash: = generate_hash("stat_appetite")

var food_item_hash: = generate_hash("food_item")

var appetite_heal_hash: = generate_hash("appetite_heal")

var food_items_price_hash: = generate_hash("food_items_price")

var tourist_danger_done_hash: = generate_hash("tourist_danger_done")

# Gourmet DLC - wave number in which the Freeloader last bought. Lives in the effects dict
# because that IS serialized with the run; a plain RunData var reset on reload and let him
# buy a second thing from the same shop.
var freeloader_shop_wave_hash: = generate_hash("freeloader_shop_wave")

# Gourmet DLC - The Special: ids of the modifiers currently applied, and the ones previewed
# in the shop for the NEXT wave. Both live in the serialized effects dict so a reload keeps
# the same roll instead of silently re-rolling or double-applying.
# Gourmet DLC - per-shop-slot chance that the roll is restricted to food SPAWNER items.
# The vanilla wanted_tags bias only fires 5% of the time and "food" also matches ~25 plain
# food items, so spawners stayed rare for the characters built around them.
var spawner_shop_chance_hash: = generate_hash("spawner_shop_chance")

var special_active_mods_hash: = generate_hash("special_active_mods")

var special_next_mods_hash: = generate_hash("special_next_mods")

var special_shop_mods_hash: = generate_hash("special_shop_mods")

# Gourmet DLC - Wildcard modifier hooks: force a wave event / stretch the wave / resize the
# next shop. Plain int deltas so SpecialModifiers can apply and subtract them exactly.
var special_force_fog_hash: = generate_hash("special_force_fog")

var special_force_bullet_hell_hash: = generate_hash("special_force_bullet_hell")

var special_wave_duration_hash: = generate_hash("special_wave_duration")

var special_shop_slots_hash: = generate_hash("special_shop_slots")

# Gourmet DLC - Gourmet: fat stacks applied so far (1 per wave; -3% Speed, +1% size each)
var gourmet_fat_hash: = generate_hash("gourmet_fat")

# Gourmet DLC - Competitive Eater: Appetite modifications multiplier (run_data.get_stat_gain
# looks up "gain_" + the stat name, so this key must exist for the lookup to find it)
var gain_stat_appetite_hash: = generate_hash("gain_stat_appetite")

var gourmet_foods_eaten_hash: = generate_hash("gourmet_foods_eaten")

var wave_start_foods_hash: = generate_hash("wave_start_foods")

var kill_foods_hash: = generate_hash("kill_foods")

var burning_kill_foods_hash: = generate_hash("burning_kill_foods")

var crit_foods_hash: = generate_hash("crit_foods")

var burning_tick_foods_hash: = generate_hash("burning_tick_foods")

var explosion_foods_hash: = generate_hash("explosion_foods")

var material_foods_hash: = generate_hash("material_foods")

var level_up_foods_hash: = generate_hash("level_up_foods")

var damage_taken_foods_hash: = generate_hash("damage_taken_foods")

var elite_kill_foods_hash: = generate_hash("elite_kill_foods")

var consumable_count_foods_hash: = generate_hash("consumable_count_foods")

var step_foods_hash: = generate_hash("step_foods")

var timer_foods_hash: = generate_hash("timer_foods")

var full_hp_timer_foods_hash: = generate_hash("full_hp_timer_foods")

var standstill_timer_foods_hash: = generate_hash("standstill_timer_foods")

var mid_wave_foods_hash: = generate_hash("mid_wave_foods")

var random_times_foods_hash: = generate_hash("random_times_foods")

var reroll_banked_foods_hash: = generate_hash("reroll_banked_foods")

var close_kill_foods_hash: = generate_hash("close_kill_foods")

var turret_kill_foods_hash: = generate_hash("turret_kill_foods")

var far_kill_foods_hash: = generate_hash("far_kill_foods")

var banked_rerolls_hash: = generate_hash("banked_rerolls")

var doggy_bag_hash: = generate_hash("doggy_bag")

var banked_leftovers_hash: = generate_hash("banked_leftovers")

var damage_vs_burning_hash: = generate_hash("damage_vs_burning")

var consumables_no_heal_hash: = generate_hash("consumables_no_heal")

var food_buff_duration_hash: = generate_hash("food_buff_duration")

var food_buff_strength_hash: = generate_hash("food_buff_strength")

var food_heal_disabled_hash: = generate_hash("food_heal_disabled")

var food_bonus_heal_hash: = generate_hash("food_bonus_heal")

var mystery_meat_safe_hash: = generate_hash("mystery_meat_safe")

var spawner_trigger_speed_hash: = generate_hash("spawner_trigger_speed")

var food_spawns_halved_hash: = generate_hash("food_spawns_halved")

var second_helping_hash: = generate_hash("second_helping")

var cooler_box_hash: = generate_hash("cooler_box")

var compost_bin_hash: = generate_hash("compost_bin")

var food_speed_burst_hash: = generate_hash("food_speed_burst")

var projectiles_on_eat_hash: = generate_hash("projectiles_on_eat")

var grease_fire_hash: = generate_hash("grease_fire")

var full_belly_hash: = generate_hash("full_belly")

var food_stack_cap_bonus_hash: = generate_hash("food_stack_cap_bonus")

var wine_cellar_hash: = generate_hash("wine_cellar")

var delivery_drone_hash: = generate_hash("delivery_drone")

var food_coma_hash: = generate_hash("food_coma")

var snack_break_hash: = generate_hash("snack_break")

var buffet_insurance_hash: = generate_hash("buffet_insurance")

var crit_vs_elites_hash: = generate_hash("crit_vs_elites")

var burning_damage_taken_hash: = generate_hash("burning_damage_taken")

var caltrops_hash: = generate_hash("caltrops")

var static_cling_hash: = generate_hash("static_cling")

var echo_chamber_hash: = generate_hash("echo_chamber")

var nine_lives_hash: = generate_hash("nine_lives")

var nine_lives_used_hash: = generate_hash("nine_lives_used")

var loyalty_card_hash: = generate_hash("loyalty_card")

var shop_purchases_hash: = generate_hash("shop_purchases")

var regen_per_burning_enemy_hash: = generate_hash("regen_per_burning_enemy")

var burp_of_power_hash: = generate_hash("burp_of_power")

var panic_button_hash: = generate_hash("panic_button")

var pocket_sand_slow_hash: = generate_hash("pocket_sand_slow")

var set_menu_hash: = generate_hash("set_menu")

var selected_spawner_hash: = generate_hash("selected_spawner")

var spawner_items_price_hash: = generate_hash("spawner_items_price")

var enemy_attack_speed_hash: = generate_hash("enemy_attack_speed")

var execute_damage_hash: = generate_hash("execute_damage")

var gourmet_slow_on_hit_hash: = generate_hash("gourmet_slow_on_hit")

var gourmet_slow_chance_hash: = generate_hash("gourmet_slow_chance")

var tenderize_on_hit_hash: = generate_hash("tenderize_on_hit")

var extend_buffs_on_hit_hash: = generate_hash("extend_buffs_on_hit")

var heal_on_hit_hash: = generate_hash("heal_on_hit")

var soul_food_hash: = generate_hash("soul_food")

var soul_food_streak_hash: = generate_hash("soul_food_streak")

var minimalist_item_hash: = generate_hash("minimalist_item")

var item_soul_food_hash: = generate_hash("item_soul_food")

var credit_limit_hash: = generate_hash("credit_limit")  # Gourmet DLC - Credit Card shop overspend ceiling
