# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://singletons/menu_data.gd"

# Gourmet ecosystem - the walkable Hub, its own main-menu destination (never in
# the Start path - user law 2026-08-18). run_flow_from_lobby marks a run flow
# begun at the Hub's Departure door so Back returns there.
var lobby_scene: String = "res://ui/lobby/lobby.tscn"

var run_flow_from_lobby: bool = false

# set by the Hub's changing booth: character select stores the picks as hub
# characters and returns to the Hub instead of continuing to weapon select
var character_select_for_lobby: bool = false
