# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://singletons/progress_data.gd"


func _ready() -> void :
	init_save_paths()
	load_dlc_pcks()
	_gourmet_install_dlc_extension()
	check_for_available_dlcs()
	init_settings()
	load_settings()
	check_settings_version()
	init_data()
	randomize()
	saved_run_state = _get_empty_run_state()
	for available_dlc in available_dlcs:
		available_dlc.add_resources()
	# Gourmet ecosystem - packs register HERE, alongside the vanilla DLCs, so
	# every custom id exists before load_game_file() resolves the saved run.
	# (Packs' own _ready is only a safety fallback and runs much later.)
	Utils.packs.apply_at_boot()
	RunData.reset()
	if DebugService.generate_full_unlocked_save_file:
		unlock_all()
		save()
	else:
		load_game_file()
		add_unlocked_by_default()
	set_max_selectable_difficulty()
	for available_dlc in available_dlcs:
		if settings.deactivated_dlcs.has(available_dlc.my_id) or get_tree().current_scene.name == "GutRunner":
			available_dlc.remove_resources()
	if Utils.on_ps5:
		print("PS5 platform : activate activity")
		need_activity = true



func init_gameplay_options() -> Dictionary:
	return {
		"mouse_only": false, 
		"manual_aim": false, 
		"manual_aim_on_mouse_press": false, 
		"movement_with_gamepad": true, 
		"hp_bar_on_character": true, 
		"hp_bar_on_bosses": true, 
		"keep_lock": true, 
		"lock_coop_camera": false, 
		"random_zone": false, 
		"endless_score_storing": 0, 
		"share_coop_loot": true, 
		"deactivated_dlcs": [], 
		"disabled_packs": [], 
		"selected_game_mode": "", 
		"deactivated_skin_sets": [], 
		"no_item_appearance": false, 
		"holding_button": true, 
	}


func check_dlc_valid_for_saved_run_state() -> bool:
	if ProgressData.saved_run_state.has_run_state == false:
		return true
	# Gourmet ecosystem - a saved run also needs every PACK it was started with
	# (old saves without the key were made with everything on and pass vacuously)
	for saved_pack_id in saved_run_state.get("enabled_packs", []):
		if not Utils.packs.is_pack_enabled(str(saved_pack_id)):
			return false
	if saved_run_state.has("current_zone"):
		var current_zone = saved_run_state.current_zone
		if current_zone > 0:
			if not ProgressData.is_dlc_available("abyssal_terrors") and current_zone == 1:
				print("Not valid because save has DLC and DLC is not available")
				return false
	if not ProgressData.is_dlc_available("abyssal_terrors"):
		if saved_run_state.has("players_data"):
			for player in saved_run_state.players_data:
				var foundChar = false
				for character in ItemService.characters:
					if player.current_character != null and player.current_character.my_id == character.my_id:
						foundChar = true
				if foundChar == false:
					print("couldn't find player in list, probably in dlc, disable save")
					return false
	return true



func load_with_generic_loader(loader, path: = "") -> void :
	loader.load_game_file(path)
	load_status = loader.load_status
	if load_status == LoadStatus.CORRUPTED_ALL_SAVES:
		return
	if load_status == LoadStatus.SAVE_MISSING:
		return
	_append_without_duplicates(zones_unlocked, loader.zones_unlocked)
	_append_without_duplicates(characters_unlocked, loader.characters_unlocked)
	_append_without_duplicates(upgrades_unlocked, loader.upgrades_unlocked)
	_append_without_duplicates(consumables_unlocked, loader.consumables_unlocked)
	_append_without_duplicates(weapons_unlocked, loader.weapons_unlocked)
	_append_without_duplicates(items_unlocked, loader.items_unlocked)
	var challenges_completed_hash: Array = Utils.convert_to_hash_array(loader.challenges_completed)
	_append_without_duplicates(challenges_completed, challenges_completed_hash)
	if "systems_unlocked" in loader:
		_append_without_duplicates(systems_unlocked, Utils.convert_to_hash_array(loader.systems_unlocked))
	for difficulty_json in loader.difficulties_unlocked_serialized:
		var difficulty: = CharacterDifficultyInfo.new()
		difficulty.deserialize_and_merge(difficulty_json)
		difficulties_unlocked.append(difficulty)
	_dedublicate_difficulties_unlocked()
	inactive_mods = loader.inactive_mods.duplicate()
	read_announcements = loader.read_announcements.duplicate()
	saved_run_state = Utils.merge_dictionaries(saved_run_state, loader.run_state_deserialized)
	for k in ["nb_of_waves", "current_wave", "current_difficulty", "bonus_gold", "retries"]:
		if saved_run_state.has(k) and typeof(saved_run_state[k]) == TYPE_REAL:
			saved_run_state[k] = int(saved_run_state[k])
	for k in ["reroll_count", "paid_reroll_count", "initial_free_rerolls", "free_rerolls"]:
		if saved_run_state.has(k) and typeof(saved_run_state[k]) == TYPE_ARRAY:
			for i in saved_run_state[k].size():
				if typeof(saved_run_state[k][i]) == TYPE_REAL:
					saved_run_state[k][i] = int(saved_run_state[k][i])
	if loader is ProgressDataLoaderV1 or loader is ProgressDataLoaderV2:
		settings = Utils.merge_dictionaries(settings, loader.settings)
	data = Utils.merge_dictionaries(data, loader.data)
	for k in ["enemies_killed", "materials_collected", "trees_killed", "steps_taken", "enemies_killed_far_away"]:
		if data.has(k):
			data[k] = int(data[k])
	if not (loader is ProgressDataLoaderV1) and not (loader is ProgressDataLoaderV2):
		killed_enemies = Utils.merge_dictionaries(killed_enemies, loader.killed_enemies)
		for k in killed_enemies.keys():
			killed_enemies[k] = int(killed_enemies[k])
		killed_by_enemies = Utils.merge_dictionaries(killed_by_enemies, loader.killed_by_enemies)
		for k in killed_by_enemies.keys():
			killed_by_enemies[k] = int(killed_by_enemies[k])
		items_bought = Utils.merge_dictionaries(items_bought, loader.items_bought)
		for k in items_bought.keys():
			items_bought[k] = int(items_bought[k])


func _set_loader_properties(loader_v3: ProgressDataLoaderV3, run_state: Dictionary) -> void :
	loader_v3.zones_unlocked = zones_unlocked.duplicate()
	loader_v3.characters_unlocked = Utils.convert_to_hash_array(characters_unlocked.duplicate())
	loader_v3.upgrades_unlocked = Utils.convert_to_hash_array(upgrades_unlocked.duplicate())
	loader_v3.consumables_unlocked = Utils.convert_to_hash_array(consumables_unlocked.duplicate())
	loader_v3.weapons_unlocked = Utils.convert_to_hash_array(weapons_unlocked.duplicate())
	loader_v3.items_unlocked = Utils.convert_to_hash_array(items_unlocked.duplicate())
	loader_v3.challenges_completed = Utils.convert_to_hash_array(challenges_completed.duplicate())
	loader_v3.systems_unlocked = Utils.convert_to_hash_array(systems_unlocked.duplicate())
	loader_v3.difficulties_unlocked_serialized.clear()
	for difficulty_unlocked in difficulties_unlocked:
		loader_v3.difficulties_unlocked_serialized.push_back(difficulty_unlocked.serialize())
	loader_v3.inactive_mods = inactive_mods.duplicate()
	loader_v3.read_announcements = read_announcements.duplicate()
	loader_v3.run_state_deserialized = run_state.duplicate()
	loader_v3.data = data.duplicate()
	loader_v3.killed_enemies = killed_enemies.duplicate()
	loader_v3.killed_by_enemies = killed_by_enemies.duplicate()
	loader_v3.items_bought = items_bought.duplicate()

# --- GourmetCore: late script extension for the Abyssal Terrors DLC ---
func _gourmet_install_dlc_extension() -> void :
	if not ResourceLoader.exists("res://dlcs/dlc_1/dlc_1_data.gd"):
		return
	ModLoaderMod.install_script_extension("res://mods-unpacked/nicolassut-GourmetCore/extensions/dlcs/dlc_1/dlc_1_data.gd")
