# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://singletons/progress_data_loader_v3.gd"

# Gourmet ecosystem - persisted since Phase 4; OPTIONAL in the save (old saves
# lack it), so it must NEVER join the hard-fail property whitelist below
var systems_unlocked: = []


func load_progress_save_file(path: = "") -> void :
	if path.empty():
		path = save_path
	if path.empty():
		printerr(LOG_PREFIX + "Loading failed - missing save path")
		return
	print(LOG_PREFIX + "Loading %s" % path)
	var save_file: = File.new()
	if not save_file.file_exists(path):
		print(LOG_PREFIX + "No v3 save found")
		load_status = LoadStatus.SAVE_MISSING
		return
	var error = save_file.open(path, File.READ)
	var basename = "save_v3_" + String(profile_id)
	if error != OK:
		printerr(LOG_PREFIX + "Could not open %s. Error code: %s" % [path, error])
		_close_file_and_load_backups(basename, save_file, path)
		return
	var content: = save_file.get_as_text();
	if content == null:
		printerr(LOG_PREFIX + "Content of %s is null." % path)
		_close_file_and_load_backups(basename, save_file, path)
		return
	if content.strip_edges() == "":
		printerr(LOG_PREFIX + "Content of %s is empty." % path)
		_close_file_and_load_backups(basename, save_file, path)
		return
	var parse_result: = JSON.parse(content)
	if parse_result.error != OK:
		var error_line: = parse_result.error_line
		var error_string: = parse_result.error_string
		printerr(LOG_PREFIX + "Error parsing save file (%s): %s at line %s" % [parse_result.error, error_string, error_line])
		_close_file_and_load_backups(basename, save_file, path)
		return
	var save_object = parse_result.result
	if typeof(save_object) != TYPE_DICTIONARY:
		printerr(LOG_PREFIX + "Save file is not a dictionary")
		_close_file_and_load_backups(basename, save_file, path)
		return
	for property in ["zones_unlocked", "characters_unlocked", "upgrades_unlocked", "consumables_unlocked", "weapons_unlocked", "items_unlocked", "challenges_completed", "difficulties_unlocked", "inactive_mods"]:
		if not save_object.has(property):
			printerr(LOG_PREFIX + "Save file is missing property: %s" % property)
			_close_file_and_load_backups(basename, save_file, path)
			return
		if typeof(save_object[property]) != TYPE_ARRAY:
			printerr(LOG_PREFIX + "Property %s is not an array" % property)
			_close_file_and_load_backups(basename, save_file, path)
			return
	for property in ["data"]:
		if not save_object.has(property):
			printerr(LOG_PREFIX + "Save file is missing property: %s" % property)
			_close_file_and_load_backups(basename, save_file, path)
			return
		if typeof(save_object[property]) != TYPE_DICTIONARY:
			printerr(LOG_PREFIX + "Property %s is not a dictionary" % property)
			_close_file_and_load_backups(basename, save_file, path)
			return
	zones_unlocked = save_object.zones_unlocked
	characters_unlocked = Utils.convert_to_hash_array(save_object.characters_unlocked)
	upgrades_unlocked = Utils.convert_to_hash_array(save_object.upgrades_unlocked)
	consumables_unlocked = Utils.convert_to_hash_array(save_object.consumables_unlocked)
	weapons_unlocked = Utils.convert_to_hash_array(save_object.weapons_unlocked)
	items_unlocked = Utils.convert_to_hash_array(save_object.items_unlocked)
	var challenges_completed_hash = Utils.convert_to_hash_array(save_object.challenges_completed, true)
	challenges_completed = challenges_completed_hash
	systems_unlocked = Utils.convert_to_hash_array(save_object.get("systems_unlocked", []))
	difficulties_unlocked_serialized = save_object.difficulties_unlocked
	inactive_mods = save_object.inactive_mods
	read_announcements = save_object.get("read_announcements", [])
	data = save_object.data
	if save_object.has("killed_enemies"):
		killed_enemies = Utils.convert_dictionary_to_hash(save_object.killed_enemies)
	if save_object.has("killed_by_enemies"):
		killed_by_enemies = Utils.convert_dictionary_to_hash(save_object.killed_by_enemies)
	if save_object.has("items_bought"):
		items_bought = Utils.convert_dictionary_to_hash(save_object.items_bought)
	version = save_object.version
	save_file.close()


func deserialize_run_state(state: Dictionary) -> Dictionary:
	var result = state.duplicate()
	if not state.has_run_state:
		return result
	result.players_data = []
	for serialized_player_data in state.players_data:
		if serialized_player_data is String:
			result.has_run_state = false
			return result
		result.players_data.push_back(PlayerRunData.new().deserialize(serialized_player_data))
	for bg in ItemService.backgrounds:
		if bg.name.to_lower() == state.current_background:
			result.current_background = bg
			break
	result.challenges_completed_this_run = []
	state.challenges_completed_this_run = Utils.convert_to_hash_array(state.challenges_completed_this_run.duplicate())
	for challenge_id in state.challenges_completed_this_run:
		for chal_data in ChallengeService.challenges:
			if chal_data.my_id_hash == challenge_id:
				result.challenges_completed_this_run.push_back(chal_data)
				break
	result.locked_shop_items = [[], [], [], []]
	for player_index in state.locked_shop_items.size():
		for locked_item in state.locked_shop_items[player_index]:
			var item_data = ItemService.get_element_safe(ItemService.items, locked_item[0].my_id)
			var weapon_data = ItemService.get_element_safe(ItemService.weapons, locked_item[0].my_id)
			# Gourmet DLC - P2W chests live outside the item registry on purpose;
			# resolve a locked chest through the chest loader or it silently
			# vanishes from the shop on reload
			if item_data == null and weapon_data == null and str(locked_item[0].my_id).begins_with("item_p2w_chest_"):
				item_data = ItemService.get_p2w_chest(int(str(locked_item[0].my_id).replace("item_p2w_chest_", "")))
			if item_data != null:
				item_data = item_data.duplicate()
				item_data.deserialize_and_merge(locked_item[0])
				result.locked_shop_items[player_index].push_back([item_data, locked_item[1]])
			if weapon_data != null:
				weapon_data = weapon_data.duplicate()
				weapon_data.deserialize_and_merge(locked_item[0])
				result.locked_shop_items[player_index].push_back([weapon_data, locked_item[1]])
	result.shop_items = [[], [], [], []]
	for player_index in state.shop_items.size():
		for shop_item in state.shop_items[player_index]:
			if shop_item[0] is String:
				continue
			var item_data = ItemService.get_element_safe(ItemService.items, shop_item[0].my_id)
			var weapon_data = ItemService.get_element_safe(ItemService.weapons, shop_item[0].my_id)
			# Gourmet DLC - P2W chests live outside the item registry; without this
			# fallback a resumed mid-shop save came back with 0 offers (reroll fixed
			# it because a fresh fill re-rolls chests)
			if item_data == null and weapon_data == null and str(shop_item[0].my_id).begins_with("item_p2w_chest_"):
				item_data = ItemService.get_p2w_chest(int(str(shop_item[0].my_id).replace("item_p2w_chest_", "")))
			if item_data != null:
				item_data = item_data.duplicate()
				item_data.deserialize_and_merge(shop_item[0])
				result.shop_items[player_index].push_back([item_data, shop_item[1]])
			if weapon_data != null:
				weapon_data = weapon_data.duplicate()
				weapon_data.deserialize_and_merge(shop_item[0])
				result.shop_items[player_index].push_back([weapon_data, shop_item[1]])
	return result



	



	

	



	

	


		

			


func get_save_object() -> Dictionary:
	return {
		"zones_unlocked": zones_unlocked, 
		"characters_unlocked": characters_unlocked, 
		"upgrades_unlocked": upgrades_unlocked, 
		"consumables_unlocked": consumables_unlocked, 
		"weapons_unlocked": weapons_unlocked, 
		"items_unlocked": items_unlocked, 
		"challenges_completed": challenges_completed, 
		"systems_unlocked": systems_unlocked, 
		"difficulties_unlocked": difficulties_unlocked_serialized, 
		"inactive_mods": inactive_mods, 
		"read_announcements": read_announcements, 
		"current_run_state": serialize_run_state(run_state_deserialized), 
		"data": data, 
		"killed_enemies": killed_enemies, 
		"killed_by_enemies": killed_by_enemies, 
		"items_bought": items_bought, 
		"version": 3
	}

# forwarding constructor (vanilla base has required _init args; a child
# script without an explicit _init cannot forward them - Godot 3 quirk)
func _init(save_dir: = "", current_profile_id: int = 0).(save_dir, current_profile_id) -> void :
	pass
