# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://singletons/progress_data.gd"


# Gourmet ecosystem - ALL v3 loader construction goes through here. In the
# Workshop build this script compiles BEFORE the loader extension takes over
# its path (ModLoader sorts extensions by inheritance stack), so a bound
# ProgressDataLoaderV3 reference would create VANILLA loader instances without
# systems_unlocked. load-by-path resolves the taken-over script at call time.
func _gourmet_loader_v3(profile_id: int):
	return load("res://singletons/progress_data_loader_v3.gd").new(SAVE_DIR, profile_id)



func _ready() -> void :
	init_save_paths()
	load_dlc_pcks()
	_gourmet_install_dlc_extension()
	check_for_available_dlcs()
	init_settings()
	load_settings()
	check_settings_version()
	init_data()
	randomize()
	saved_run_state = _get_empty_run_state()
	for available_dlc in available_dlcs:
		available_dlc.add_resources()
	# Gourmet ecosystem - packs register HERE, alongside the vanilla DLCs, so
	# every custom id exists before load_game_file() resolves the saved run.
	# (Packs' own _ready is only a safety fallback and runs much later.)
	Utils.packs.apply_at_boot()
	RunData.reset()
	if DebugService.generate_full_unlocked_save_file:
		unlock_all()
		save()
	else:
		load_game_file()
		add_unlocked_by_default()
	set_max_selectable_difficulty()
	for available_dlc in available_dlcs:
		if settings.deactivated_dlcs.has(available_dlc.my_id) or get_tree().current_scene.name == "GutRunner":
			available_dlc.remove_resources()
	if Utils.on_ps5:
		print("PS5 platform : activate activity")
		need_activity = true


func reset_save_profile(id: int) -> void :
	if BETA:
		var loader_beta = ProgressDataLoaderBeta.new(SAVE_DIR, id)
		loader_beta.add_unlocked_by_default_from_blank_save()
		loader_beta.run_state_deserialized = _get_empty_run_state()
		loader_beta.save()
		if current_profile_id == id:
			load_with_generic_loader(loader_beta)
	else:
		var loader = _gourmet_loader_v3(id)
		loader.add_unlocked_by_default_from_blank_save()
		loader.run_state_deserialized = _get_empty_run_state()
		loader.save()
		if current_profile_id == id:
			load_with_generic_loader(loader)


func unlock_all_save_profile(id: int) -> void :
	if BETA:
		var loader_beta = ProgressDataLoaderBeta.new(SAVE_DIR, id)
		loader_beta.load_game_file()
		loader_beta.unlock_all()
		loader_beta.run_state_deserialized = _get_empty_run_state()
		loader_beta.save()
		if current_profile_id == id:
			load_with_generic_loader(loader_beta)
	else:
		var loader = _gourmet_loader_v3(id)
		loader.load_game_file()
		loader.unlock_all()
		loader.run_state_deserialized = _get_empty_run_state()
		loader.save()
		if current_profile_id == id:
			load_with_generic_loader(loader)


func copy_save_profile(from_id: int, to_id: int) -> void :
	if BETA:
		var from_loader_beta = ProgressDataLoaderBeta.new(SAVE_DIR, from_id)
		from_loader_beta.load_game_file()
		if from_loader_beta.load_status != LoadStatus.SAVE_OK:
			printerr("Could not copy save profile from id %s because it could not be loaded" % from_id)
			return
		var to_loader_beta = ProgressDataLoaderBeta.new(SAVE_DIR, to_id)
		to_loader_beta.zones_unlocked = from_loader_beta.zones_unlocked.duplicate()
		to_loader_beta.characters_unlocked = from_loader_beta.characters_unlocked.duplicate()
		to_loader_beta.upgrades_unlocked = from_loader_beta.upgrades_unlocked.duplicate()
		to_loader_beta.consumables_unlocked = from_loader_beta.consumables_unlocked.duplicate()
		to_loader_beta.weapons_unlocked = from_loader_beta.weapons_unlocked.duplicate()
		to_loader_beta.items_unlocked = from_loader_beta.items_unlocked.duplicate()
		to_loader_beta.challenges_completed = from_loader_beta.challenges_completed.duplicate()
		to_loader_beta.difficulties_unlocked_serialized.clear()
		for difficulty_unlocked in from_loader_beta.difficulties_unlocked_serialized:
			to_loader_beta.difficulties_unlocked_serialized.push_back(difficulty_unlocked)
		to_loader_beta.inactive_mods = from_loader_beta.inactive_mods.duplicate()
		to_loader_beta.read_announcements = from_loader_beta.read_announcements.duplicate()
		to_loader_beta.run_state_deserialized = from_loader_beta.run_state_deserialized.duplicate()
		to_loader_beta.data = from_loader_beta.data.duplicate()
		to_loader_beta.killed_enemies = from_loader_beta.killed_enemies.duplicate()
		to_loader_beta.killed_by_enemies = from_loader_beta.killed_by_enemies.duplicate()
		to_loader_beta.items_bought = from_loader_beta.items_bought.duplicate()
		to_loader_beta.save()
		if current_profile_id == to_id:
			load_with_generic_loader(to_loader_beta)
	else:
		var from_loader = _gourmet_loader_v3(from_id)
		from_loader.load_game_file()
		if from_loader.load_status != LoadStatus.SAVE_OK:
			printerr("Could not copy save profile from id %s because it could not be loaded" % from_id)
			return
		var to_loader = _gourmet_loader_v3(to_id)
		to_loader.zones_unlocked = from_loader.zones_unlocked.duplicate()
		to_loader.characters_unlocked = from_loader.characters_unlocked.duplicate()
		to_loader.upgrades_unlocked = from_loader.upgrades_unlocked.duplicate()
		to_loader.consumables_unlocked = from_loader.consumables_unlocked.duplicate()
		to_loader.weapons_unlocked = from_loader.weapons_unlocked.duplicate()
		to_loader.items_unlocked = from_loader.items_unlocked.duplicate()
		to_loader.challenges_completed = from_loader.challenges_completed.duplicate()
		to_loader.difficulties_unlocked_serialized.clear()
		for difficulty_unlocked in from_loader.difficulties_unlocked_serialized:
			to_loader.difficulties_unlocked_serialized.push_back(difficulty_unlocked)
		to_loader.inactive_mods = from_loader.inactive_mods.duplicate()
		to_loader.read_announcements = from_loader.read_announcements.duplicate()
		to_loader.run_state_deserialized = from_loader.run_state_deserialized.duplicate()
		to_loader.data = from_loader.data.duplicate()
		to_loader.killed_enemies = from_loader.killed_enemies.duplicate()
		to_loader.killed_by_enemies = from_loader.killed_by_enemies.duplicate()
		to_loader.items_bought = from_loader.items_bought.duplicate()
		to_loader.save()
		if current_profile_id == to_id:
			load_with_generic_loader(to_loader)



func init_gameplay_options() -> Dictionary:
	return {
		"mouse_only": false, 
		"manual_aim": false, 
		"manual_aim_on_mouse_press": false, 
		"movement_with_gamepad": true, 
		"hp_bar_on_character": true, 
		"hp_bar_on_bosses": true, 
		"keep_lock": true, 
		"lock_coop_camera": false, 
		"random_zone": false, 
		"endless_score_storing": 0, 
		"share_coop_loot": true, 
		"deactivated_dlcs": [], 
		"disabled_packs": [], 
		"selected_game_mode": "", 
		"last_played_characters": ["", "", "", ""], 
		"deactivated_skin_sets": [], 
		"no_item_appearance": false, 
		"holding_button": true, 
	}


func check_dlc_valid_for_saved_run_state() -> bool:
	if ProgressData.saved_run_state.has_run_state == false:
		return true
	# Gourmet ecosystem - a saved run also needs every PACK it was started with
	# (old saves without the key were made with everything on and pass vacuously)
	for saved_pack_id in saved_run_state.get("enabled_packs", []):
		if not Utils.packs.is_pack_enabled(str(saved_pack_id)):
			return false
	if saved_run_state.has("current_zone"):
		var current_zone = saved_run_state.current_zone
		if current_zone > 0:
			if not ProgressData.is_dlc_available("abyssal_terrors") and current_zone == 1:
				print("Not valid because save has DLC and DLC is not available")
				return false
	if not ProgressData.is_dlc_available("abyssal_terrors"):
		if saved_run_state.has("players_data"):
			for player in saved_run_state.players_data:
				var foundChar = false
				for character in ItemService.characters:
					if player.current_character != null and player.current_character.my_id == character.my_id:
						foundChar = true
				if foundChar == false:
					print("couldn't find player in list, probably in dlc, disable save")
					return false
	return true




func init_save_paths(user_dir_override: = "user://") -> void :
	var dir = Directory.new()
	var dir_path = user_dir_override + Platform.get_user_id()
	var directory_exists = dir.dir_exists(dir_path)
	if not directory_exists:
		var err = dir.make_dir(dir_path)
		if err != OK:
			printerr("Could not create the directory %s. Error code: %s" % [dir_path, err])
			return
	SAVE_DIR = dir_path
	if BETA:
		SAVE_PATH = ProgressDataLoaderBeta.new(SAVE_DIR, current_profile_id).save_path
	else:
		SAVE_PATH = _gourmet_loader_v3(current_profile_id).save_path
	LOG_PATH = dir_path + "/log.txt"
	print("LOG_PATH: " + str(LOG_PATH))
	var file = File.new()
	file.open(LOG_PATH, File.WRITE)
	file.close()
	if not Utils.is_on_console() and not directory_exists:
		_copy_files_from_fallback_dir(user_dir_override)





func load_game_file(try_fallback: = true) -> void :
	if DebugService.reinitialize_save:
		save()
		return
	if BETA:
		var loader_beta = ProgressDataLoaderBeta.new(SAVE_DIR, current_profile_id)
		load_with_generic_loader(loader_beta)
		show_main_title_beta_save_warning_popup = loader_beta.show_main_title_beta_save_warning_popup
		if load_status == LoadStatus.SAVE_OK:
			return
		if load_status != LoadStatus.SAVE_MISSING:
			return
	print("--- Load game file ---")
	print("Try to load save v3")
	var loader_v3 = _gourmet_loader_v3(current_profile_id)
	load_with_generic_loader(loader_v3)
	if load_status == LoadStatus.SAVE_OK:
		return
	if load_status != LoadStatus.SAVE_MISSING:
		return
	if current_profile_id > 0:
		load_status = LoadStatus.SAVE_OK
		save()
		return
	print("No save v3. Try to load save v2")
	var loader_v2 = ProgressDataLoaderV2.new(SAVE_DIR)
	load_with_generic_loader(loader_v2)
	if load_status == LoadStatus.SAVE_OK:
		print("Save v2 OK, try to merge old V1")
		merge_old_v1_save()
		return
	if load_status != LoadStatus.SAVE_MISSING:
		print("Save v2 corrupted. Not trying v1")
		return
	var loader_v1 = null
	print("No save v2. Try to load save v1")
	if Utils.is_on_console():
		loader_v1 = ProgressDataLoaderV1.new("user:/")
	else:
		loader_v1 = ProgressDataLoaderV1.new(SAVE_DIR)
	load_with_generic_loader(loader_v1)
	if load_status == LoadStatus.SAVE_OK:
		print("Migrating v1 save to v3")
		save()
		return
	elif load_status != LoadStatus.SAVE_MISSING:
		print("Save v1 corrupted")
	else:
		if try_fallback and not Utils.is_on_console():
			print("No save found, trying to copy from fallback")
			_use_fallback_save()
			return
		print("No save found, creating new save")
		load_status = LoadStatus.SAVE_OK
		save()



func load_with_generic_loader(loader, path: = "") -> void :
	loader.load_game_file(path)
	load_status = loader.load_status
	if load_status == LoadStatus.CORRUPTED_ALL_SAVES:
		return
	if load_status == LoadStatus.SAVE_MISSING:
		return
	_append_without_duplicates(zones_unlocked, loader.zones_unlocked)
	_append_without_duplicates(characters_unlocked, loader.characters_unlocked)
	_append_without_duplicates(upgrades_unlocked, loader.upgrades_unlocked)
	_append_without_duplicates(consumables_unlocked, loader.consumables_unlocked)
	_append_without_duplicates(weapons_unlocked, loader.weapons_unlocked)
	_append_without_duplicates(items_unlocked, loader.items_unlocked)
	var challenges_completed_hash: Array = Utils.convert_to_hash_array(loader.challenges_completed)
	_append_without_duplicates(challenges_completed, challenges_completed_hash)
	if "systems_unlocked" in loader:
		_append_without_duplicates(systems_unlocked, Utils.convert_to_hash_array(loader.systems_unlocked))
	for difficulty_json in loader.difficulties_unlocked_serialized:
		var difficulty: = CharacterDifficultyInfo.new()
		difficulty.deserialize_and_merge(difficulty_json)
		difficulties_unlocked.append(difficulty)
	_dedublicate_difficulties_unlocked()
	inactive_mods = loader.inactive_mods.duplicate()
	read_announcements = loader.read_announcements.duplicate()
	saved_run_state = Utils.merge_dictionaries(saved_run_state, loader.run_state_deserialized)
	for k in ["nb_of_waves", "current_wave", "current_difficulty", "bonus_gold", "retries"]:
		if saved_run_state.has(k) and typeof(saved_run_state[k]) == TYPE_REAL:
			saved_run_state[k] = int(saved_run_state[k])
	for k in ["reroll_count", "paid_reroll_count", "initial_free_rerolls", "free_rerolls"]:
		if saved_run_state.has(k) and typeof(saved_run_state[k]) == TYPE_ARRAY:
			for i in saved_run_state[k].size():
				if typeof(saved_run_state[k][i]) == TYPE_REAL:
					saved_run_state[k][i] = int(saved_run_state[k][i])
	if loader is ProgressDataLoaderV1 or loader is ProgressDataLoaderV2:
		settings = Utils.merge_dictionaries(settings, loader.settings)
	data = Utils.merge_dictionaries(data, loader.data)
	for k in ["enemies_killed", "materials_collected", "trees_killed", "steps_taken", "enemies_killed_far_away"]:
		if data.has(k):
			data[k] = int(data[k])
	if not (loader is ProgressDataLoaderV1) and not (loader is ProgressDataLoaderV2):
		killed_enemies = Utils.merge_dictionaries(killed_enemies, loader.killed_enemies)
		for k in killed_enemies.keys():
			killed_enemies[k] = int(killed_enemies[k])
		killed_by_enemies = Utils.merge_dictionaries(killed_by_enemies, loader.killed_by_enemies)
		for k in killed_by_enemies.keys():
			killed_by_enemies[k] = int(killed_by_enemies[k])
		items_bought = Utils.merge_dictionaries(items_bought, loader.items_bought)
		for k in items_bought.keys():
			items_bought[k] = int(items_bought[k])





func save() -> void :
	if DebugService.disable_saving:
		return
	if load_status == LoadStatus.CORRUPTED_ALL_SAVES_NO_STEAM or load_status == LoadStatus.CORRUPTED_ALL_SAVES_NO_EPIC:
		printerr("Aborting save due to unrecoverable corruption")
		return
	save_settings()
	if BETA:
		var loader_beta = ProgressDataLoaderBeta.new(SAVE_DIR, current_profile_id)
		_set_loader_properties_beta(loader_beta, saved_run_state)
		loader_beta.show_main_title_beta_save_warning_popup = show_main_title_beta_save_warning_popup
		loader_beta.save()
	else:
		var loader_v3 = _gourmet_loader_v3(current_profile_id)
		_set_loader_properties(loader_v3, saved_run_state)
		loader_v3.save()





func get_current_save_object() -> Dictionary:
	if BETA:
		var loader_beta = ProgressDataLoaderBeta.new(SAVE_DIR, current_profile_id)
		_set_loader_properties_beta(loader_beta, _get_current_run_state())
		return loader_beta.get_save_object()
	var loader_v3 = _gourmet_loader_v3(current_profile_id)
	_set_loader_properties(loader_v3, _get_current_run_state())
	return loader_v3.get_save_object()


func _set_loader_properties(loader_v3: ProgressDataLoaderV3, run_state: Dictionary) -> void :
	loader_v3.zones_unlocked = zones_unlocked.duplicate()
	loader_v3.characters_unlocked = Utils.convert_to_hash_array(characters_unlocked.duplicate())
	loader_v3.upgrades_unlocked = Utils.convert_to_hash_array(upgrades_unlocked.duplicate())
	loader_v3.consumables_unlocked = Utils.convert_to_hash_array(consumables_unlocked.duplicate())
	loader_v3.weapons_unlocked = Utils.convert_to_hash_array(weapons_unlocked.duplicate())
	loader_v3.items_unlocked = Utils.convert_to_hash_array(items_unlocked.duplicate())
	loader_v3.challenges_completed = Utils.convert_to_hash_array(challenges_completed.duplicate())
	loader_v3.systems_unlocked = Utils.convert_to_hash_array(systems_unlocked.duplicate())
	loader_v3.difficulties_unlocked_serialized.clear()
	for difficulty_unlocked in difficulties_unlocked:
		loader_v3.difficulties_unlocked_serialized.push_back(difficulty_unlocked.serialize())
	loader_v3.inactive_mods = inactive_mods.duplicate()
	loader_v3.read_announcements = read_announcements.duplicate()
	loader_v3.run_state_deserialized = run_state.duplicate()
	loader_v3.data = data.duplicate()
	loader_v3.killed_enemies = killed_enemies.duplicate()
	loader_v3.killed_by_enemies = killed_by_enemies.duplicate()
	loader_v3.items_bought = items_bought.duplicate()


func get_profile_stats() -> Array:
	var result = []
	for i in range(3):
		if BETA:
			var loader_beta = ProgressDataLoaderBeta.new(SAVE_DIR, i)
			var stats = loader_beta.load_profile_stats()
			result.push_back(stats)
		else:
			var loader = _gourmet_loader_v3(i)
			var stats = loader.load_profile_stats()
			result.push_back(stats)
	return result

# --- GourmetCore: late script extension for the Abyssal Terrors DLC ---
func _gourmet_install_dlc_extension() -> void :
	if not ResourceLoader.exists("res://dlcs/dlc_1/dlc_1_data.gd"):
		return
	ModLoaderMod.install_script_extension("res://mods-unpacked/nicolassut-GourmetCore/extensions/dlcs/dlc_1/dlc_1_data.gd")
