# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://singletons/run_data.gd"


# Gourmet DLC - Blacksmith class (weapon set) scaling. Class level comes from the SUM of
# ladder tiers of the weapons carrying that class, not the weapon count: every 4 points is
# one level, so 4/8/12/16/20/24 map to levels 1-6. The bonus itself is a flat 3x (it
# replaces the earlier 3x rather than stacking with it). Drawbacks are NOT multiplied -
# see update_sets: doubling a penalty would make the Blacksmith's classes worse, not better.
const BS_SET_POINTS_PER_LEVEL: = 4

const BS_SET_MAX_LEVEL: = 6

const BS_SET_STRENGTH_MULT: = 2

# Every other character keeps vanilla's five class levels, even though the sets now
# define six. Only the Blacksmith's ladder reaches the sixth.
const VANILLA_SET_MAX_LEVEL: = 5

# Gourmet ecosystem - pack set this run was started with (Continue is invalidated
# if a required pack is disabled later; see ProgressData.check_dlc_valid_for_saved_run_state)
var enabled_packs = []


func _ready() -> void :
	# Gourmet DLC - The Debtor's card trackers, refreshed off the signal instead of trusting a
	# hand-placed call at every debt site. EVERY path that moves debt already emits this, so
	# the tracker cannot go stale again: it shipped reading +0% at 1000 debt precisely because
	# the buy-on-credit branch in remove_currency was the one site missing an explicit call.
	var _debt_tracker_conn = connect("gold_changed", self, "_on_gold_changed_refresh_debt")
	if DebugService.unlock_all_challenges:
		ChallengeService._generate_hashes()
		for chal in ChallengeService.challenges:
			ChallengeService.complete_challenge(chal.get_my_id_hash())
	if DebugService.reinitialize_store_data:
		Platform.reinitialize_store_data()
	dummy_player_effects = PlayerRunData.init_effects()
	dummy_player_remove_speed_data = init_remove_speed_data(DUMMY_PLAYER_INDEX)




func on_wave_end() -> void :
	wave_timer = null
	var max_steps_taken: = 0.0
	for steps_taken in steps_taken_this_wave:
		max_steps_taken = max(max_steps_taken, steps_taken)
	ProgressData.data["steps_taken"] += int(max_steps_taken)
	for player_index in get_player_count():
		var player_data = players_data[player_index]
		var has_overtime_pay = false
		var has_second_mortgage = false
		for item in get_player_items(player_index):
			if item.my_id == "item_overtime_pay":
				has_overtime_pay = true
			elif item.my_id == "item_second_mortgage":
				has_second_mortgage = true
		if has_overtime_pay:
			var attack_speed_gain: = min(6, int(player_data.overtime_pay_gold_this_wave / 80))
			if attack_speed_gain > 0:
				# The card says "permanent", so bank it permanently. Was TempStats.add_stat,
				# which is wiped by the wave-start TempStats.reset - it never actually persisted.
				add_stat(Keys.stat_attack_speed_hash, attack_speed_gain, player_index)
				add_tracked_value(player_index, Keys.generate_hash("item_overtime_pay"), attack_speed_gain)
		player_data.overtime_pay_gold_this_wave = 0
		if has_second_mortgage and player_data.gold > 0:
			var mortgage_gain: = int(round(player_data.gold * 0.15))
			add_gold(mortgage_gain, player_index)
			add_tracked_value(player_index, Keys.generate_hash("item_second_mortgage"), mortgage_gain)
	_reset_per_wave_properties()



func unlock_player_shop_item(item_data: ItemParentData, player_index: int) -> void :
	# Gourmet DLC - P2W chests share a my_id per rung, so id-matching could
	# unlock the wrong twin (e.g. keep a cursed one, drop the uncursed one).
	# Match the exact instance first; the id walk stays as the fallback.
	var player_locked_items = locked_shop_items[player_index]
	for locked_item in player_locked_items:
		if locked_item[0] == item_data:
			player_locked_items.erase(locked_item)
			return
	for locked_item in player_locked_items:
		if locked_item[0].my_id == item_data.my_id:
			player_locked_items.erase(locked_item)
			break



func reset(restart: bool = false) -> void :
	current_run_accessibility_settings = ProgressData.settings.enemy_scaling.duplicate()
	constant_projectile = ProgressData.settings.constant_projectile_option
	is_ban_mode_active = ProgressData.settings.ban_mode_toggled
	reset_background()
	reset_weapons_dmg_dealt()
	reset_weapons_tracked_value_this_wave()
	reset_wave_caches()
	reset_run_caches()
	for player_index in tracked_item_effects.size():
		tracked_item_effects[player_index] = init_tracked_effects()
	if not restart:
		set_player_count(1, true)
		set_coop_run(false)
		is_endless_run = false
		enabled_dlcs = ProgressData.get_active_dlc_ids()
		enabled_packs = Packs.enabled_pack_ids()
		current_difficulty = 0
		ProgressData.reset_dlc_resources_to_active_dlcs()
	else:
		var characters: = []
		for player_data in players_data:
			characters.push_back(player_data.current_character)
		var selected_weapons: = []
		var selected_items: = []
		for player_data in players_data:
			selected_weapons.push_back(player_data.selected_weapon)
			selected_items.push_back(player_data.selected_item)
		set_player_count(get_player_count(), true)
		for i in characters.size():
			var character = characters[i]
			add_character(character, i)
		for i in selected_weapons.size():
			var selected_weapon = selected_weapons[i]
			if selected_weapon:
				add_weapon(selected_weapon, i, true)
		for i in selected_items.size():
			var selected_item = selected_items[i]
			if selected_item:
				add_item(selected_item, i, true)
		add_starting_items_and_weapons()
		var difficulty = ItemService.get_element(ItemService.difficulties, Keys.empty_hash, current_difficulty)
		for effect in difficulty.effects:
			effect.apply(0)
	_reset_per_wave_properties()
	DebugService.reset_for_new_run()
	reset_elites_spawn()
	reset_events_nightmare()
	init_elites_spawn()
	init_events_nightmare()
	init_bosses_spawn()
	resumed_from_state_in_shop = false
	shop_effects_checked = false
	bonus_gold = 0
	total_bonus_gold = 0
	retries = 0
	elites_killed_this_run = []
	bosses_killed_this_run = []
	loot_aliens_killed_this_run = 0
	challenges_completed_this_run = []
	run_won = false
	all_last_wave_bosses_killed = false
	locked_shop_items = [[], [], [], []]
	difficulty_unlocked = - 1
	max_endless_wave_record_beaten = - 1
	current_wave = DebugService.starting_wave
	if DebugService.randomize_waves:
		current_wave = Utils.randi_range(9, 20)
	instant_waves = DebugService.instant_waves
	invulnerable = DebugService.invulnerable
	for player_index in get_player_count():
		players_data[player_index].uses_ban = RunData.is_ban_mode_active
		players_data[player_index].remaining_ban_token = RunData.BAN_MAX_TOKEN
	TempStats.reset()
	LinkedStats.reset()
	ItemService.init_unlocked_pool()





func add_gold(value: int, player_index: int, ignore_debt: bool = false) -> void :
	if value == 0:
		return
	# Gourmet DLC - The Freeloader: materials grant no currency, only XP. Gating the single
	# add_gold entry point kills all 18 call sites at once (pickups, harvesting, recycling,
	# item boxes, trees, cursed-enemy payouts) and takes overtime_pay_gold_this_wave with it,
	# so Overtime Pay and Second Mortgage die for free without their own hooks. add_xp is a
	# separate call at every pickup site and is deliberately left untouched, which is what
	# keeps "materials only give XP" true.
	if is_freeloader(player_index):
		return
	var player_data = players_data[player_index]
	# Gourmet DLC - The Debtor: no spendable money, ever. Incoming materials repay debt 1:1 and
	# nothing lands in the wallet, even at 0 debt. XP is a separate add_xp call at each pickup
	# site (untouched), so pickups still level him - the same split the Freeloader uses.
	if is_debtor(player_index):
		if value > 0 and player_data.debt > 0:
			var repaid: int = int(min(value, player_data.debt))
			player_data.debt = int(max(0, player_data.debt - value))
			refresh_debt_tracker(repaid)
			emit_signal("gold_changed", player_data.gold, player_index)
		return
	# Gourmet DLC - debt repayment: while in debt, ALL incoming materials go to the debt first
	# and you gain nothing until it clears. Each debt point costs 2 materials; debt_progress is
	# the half-material carry so 1-at-a-time gold pickups still repay at the true 2:1 rate.
	# ignore_debt=true is the Bank Loan's 500-material grant, which must land in the wallet
	# rather than instantly repaying the very debt the loan is about to create.
	if value > 0 and not ignore_debt and player_data.debt > 0:
		var owed_materials: int = player_data.debt * 2 - player_data.debt_progress
		var to_debt: int = int(min(value, owed_materials))
		value -= to_debt
		player_data.debt_progress += to_debt
		player_data.debt -= player_data.debt_progress / 2
		player_data.debt_progress = player_data.debt_progress % 2
		if player_data.debt <= 0:
			player_data.debt = 0
			player_data.debt_progress = 0
		refresh_debt_tracker()
		emit_signal("gold_changed", player_data.gold, player_index)
		if value <= 0:
			return
	player_data.gold += value
	if value > 0:
		player_data.overtime_pay_gold_this_wave += value
	ChallengeService.try_complete_challenge(ChallengeService.chal_hoarder_hash, player_data.gold)
	emit_signal("gold_changed", player_data.gold, player_index)



# Gourmet DLC - debt helpers.
# Credit limit = total shop overspend allowed, in debt POINTS. It is the summed credit_limit
# effect (100 per Credit Card), so no card = 0 = no overspend for anyone else.
func get_credit_limit(player_index: int) -> int:
	return int(get_player_effect(Keys.credit_limit_hash, player_index))


# How much further into debt a shop overspend may go right now: the shared debt pool means a
# Bank Loan's 300 debt eats into this ceiling until repaid below the limit.
func get_available_credit(player_index: int) -> int:
	# Gourmet DLC - The Debtor buys on unlimited credit: no ceiling, so every purchase can turn
	# into debt no matter how deep he already is.
	if is_debtor(player_index):
		return 1000000000
	return int(max(0, get_credit_limit(player_index) - players_data[player_index].debt))


func get_player_debt(player_index: int) -> int:
	return players_data[player_index].debt


# Add debt directly (Bank Loan). Points, not materials; each point is 2 materials to repay.
func add_debt(points: int, player_index: int) -> void :
	if points <= 0:
		return
	players_data[player_index].debt += points
	refresh_debt_tracker()
	emit_signal("gold_changed", players_data[player_index].gold, player_index)



func add_character(character: CharacterData, player_index: int) -> void :
	players_data[player_index].current_character = character
	add_item(character, player_index)
	# Gourmet DLC - The Debtor never holds spendable materials, so he must not keep the
	# starting wallet either. set_player_count hands out DebugService.starting_gold before a
	# character is even chosen, which is why this has to be zeroed here, once he is known -
	# add_gold's debtor gate only stops materials arriving, it cannot undo a pre-set balance.
	if is_debtor(player_index):
		players_data[player_index].gold = 0
		emit_signal("gold_changed", 0, player_index)
		# seed the card trackers now so both lines are on the card from wave 1, at +0%
		refresh_debt_tracker()




func add_item(item: ItemData, player_index: int, is_selection: bool = false) -> void :
	if is_selection:
		players_data[player_index].selected_item = item.duplicate()
	# Gourmet DLC - Bank Loan fires once, the moment it is acquired by ANY route (bought,
	# starting item, mirror-duplicated): +500 materials, then +300 debt. The 500 uses
	# ignore_debt so it lands in the wallet rather than instantly repaying the debt the loan
	# is about to create. The action effect carries value 1 while fresh; flipping it to 0
	# both prevents a re-fire and flips the card text to "Used" (effect.gd). Save-restore
	# rebuilds items directly (not via add_item) AND an owned loan is always already value 0,
	# so a reload can never re-trigger this.
	if item.my_id == "item_bank_loan":
		for loan_effect in item.effects:
			if loan_effect.custom_key == "bank_loan" and int(loan_effect.value) > 0:
				add_gold(500, player_index, true)
				add_debt(300, player_index)
				loan_effect.value = 0
				GourmetTracker.ev("bank_loan_used", {"p": player_index})
				break
	players_data[player_index].items.push_back(item)
	_update_item_caches(item, player_index)
	apply_item_effects(item, player_index)
	add_item_displayed(item, player_index)
	update_item_related_effects(player_index)
	LinkedStats.reset_player(player_index)
	_check_bait_chal(item.my_id_hash, player_index)
	check_scavenger_chal()
	add_item_to_item_count(item)



func update_sets(player_index: int) -> void :
	var player_data = players_data[player_index]
	var active_set_effects = player_data.active_set_effects
	var active_sets = player_data.active_sets
	var active_set_points = player_data.active_set_points
	for effect in active_set_effects:
		effect[1].unapply(player_index)
	active_sets.clear()
	active_set_points.clear()
	active_set_effects.clear()
	var weapons: = get_player_weapons(player_index)
	# Gourmet DLC - Blacksmith: class strength is driven by total weapon TIERS in a class,
	# not by how many weapons carry it. Each weapon contributes its ladder step (1-8) and
	# every BS_SET_POINTS_PER_LEVEL points buys a class level, so 4/8/12/16/20/24 -> levels
	# 1-6. One tier-8 weapon alone is worth 8 points = level 2.
	var bs_sets: = is_blacksmith(player_index)
	for weapon in weapons:
		for set in weapon.sets:
			if get_player_effect_bool(Keys.all_weapons_count_for_sets_hash, player_index):
				active_sets[set.my_id_hash] = weapons.size()
			elif active_sets.has(set.my_id_hash):
				active_sets[set.my_id_hash] += 1
			else:
				active_sets[set.my_id_hash] = 1
			if bs_sets:
				active_set_points[set.my_id_hash] = int(active_set_points.get(set.my_id_hash, 0)) + ItemService.get_tier_step(weapon.tier, player_index)
	for key in active_sets:
		assert (key is int)
		var set = ItemService.get_set(key)
		var bonus_index: int = - 1
		# Gourmet DLC - flat 3x for the Blacksmith. This REPLACES the old 2x, it does not
		# stack with it. Each effect is applied AND recorded once per multiple, because
		# active_set_effects is unapplied one entry at a time above - an unbalanced apply
		# would leave the extra copies stuck to the player permanently.
		var set_mult: int = 1
		if bs_sets:
			var level: int = int(active_set_points.get(key, 0)) / BS_SET_POINTS_PER_LEVEL
			if level > BS_SET_MAX_LEVEL:
				level = BS_SET_MAX_LEVEL
			if level >= 1:
				bonus_index = int(min(level - 1, set.set_bonuses.size() - 1))
				set_mult = BS_SET_STRENGTH_MULT
		elif active_sets[key] >= 2:
			# Gourmet DLC - vanilla stays capped at FIVE levels. The sets now carry a sixth
			# group for the Blacksmith's tier-based ladder, and without this cap any other
			# character holding 7+ weapons of one class (reachable with slot items) would
			# start drawing it - a silent buff to everyone.
			bonus_index = int(min(active_sets[key] - 2, min(VANILLA_SET_MAX_LEVEL, set.set_bonuses.size()) - 1))
		if bonus_index >= 0:
			for effect in set.set_bonuses[bonus_index]:
				# Gourmet DLC - upsides are multiplied, drawbacks are applied ONCE at face
				# value (blunt's -10 Speed, ethereal's -5 Armor, legendary's -100 Max HP).
				# Multiplying those would make the Blacksmith's own classes punish him.
				var reps: int = set_mult if effect.value > 0 else 1
				for _bs_i in reps:
					effect.apply(player_index)
					active_set_effects.push_back([key, effect])






func apply_item_effects(item_data: ItemParentData, player_index: int) -> void :
	Utils.reset_stat_cache(player_index)
	var effects = get_player_effects(player_index)
	for effect in item_data.effects:
		if item_data is ItemData and not item_data is UpgradeData and Utils.is_stat_key(effect.key_hash):
			var value_before = effects[effect.key_hash]
			effect.apply(player_index)
			var value_after = effects[effect.key_hash]
			# Gourmet DLC guard: a numeric stat-gain delta only makes sense for numeric
			# effects. Some effect keys are Array-valued (e.g. projectiles_on_eat); never
			# subtract Arrays here or item purchases hard-crash.
			if (value_before is int or value_before is float) and (value_after is int or value_after is float):
				var value_change = value_after - value_before
				if value_change > 0:
					_apply_gain_stat_for_equipped_item_with_stat_effects(effect.key_hash, player_index)
		elif effect is ConsumableDamageEffect:
			effect.apply(player_index, item_data)
		else:
			effect.apply(player_index)
	ChallengeService.check_stat_challenges(player_index)



# Gourmet DLC - Blacksmith: transient (never saved) per-player armed weapon for the
# two-step manual forge. player_index -> WeaponData.
var _forge_picks: = {}

# The shop's UI weapon instances (element.item) are NOT always the same objects as the
# data-side players_data.weapons entries, so identity checks against the data list fail.
# The shop syncs its live UI weapon list here; the forge logic runs against these instances
# (which is what the popup hands us). Falls back to the data list outside the shop.
var _forge_owned_weapons: = {}



func set_forge_owned_weapons(player_index: int, weapons: Array) -> void:
	_forge_owned_weapons[player_index] = weapons



func _forge_weapons_for(player_index: int) -> Array:
	# Blacksmith forge partner + pick self-heal checks must run against the LIVE
	# weapon list. The old UI mirror (_forge_owned_weapons, fed by _sync_forge_weapons
	# on elements_changed) went stale/empty whenever clear_elements() fired its
	# elements_changed mid-rebuild - the container is momentarily empty there - which
	# hid the Forge button for legitimately forgeable pairs (e.g. two Tier I Skewers).
	# get_player_weapons() only shallow-copies the array, so the shop UI holds these
	# very same WeaponData instances: the live list is identity-equivalent to the UI
	# elements (pick / element.item comparisons still hold) and can never be stale.
	return get_player_weapons_ref(player_index)



func is_blacksmith(player_index: int) -> bool:
	var forge_character = get_player_character(player_index)
	return forge_character != null and forge_character.my_id == "character_blacksmith"



func is_mime(player_index: int) -> bool:
	var mirror_character = get_player_character(player_index)
	return mirror_character != null and mirror_character.my_id == "character_mime"



# Gourmet DLC - Mime: can a mirrored weapon purchase actually fit?
# The shop gate cannot simply ask has_weapon_slot_available. Mirrors hand him 2+ copies at
# once, copies merge with EACH OTHER, and the result can merge again up the line - so a buy
# that looks impossible on a full inventory frequently is not. Vanilla's gate only allows a
# full-inventory buy when an EXACT my_id match is already owned, which wrongly blocked
# "3x Stick T2, buy Stick T1 with a mirror" even though the two new T1s merge into a T2 and
# then pair with an owned T2 for a T3.
# This simulates the same lowest-tier-first cascade base_shop._auto_merge_to_fit performs and
# reports whether it lands back inside the slot limit. Keep the two in sync.
func mime_purchase_fits(shop_weapon: WeaponData, player_index: int) -> bool:
	return mime_max_copies_that_fit(shop_weapon, player_index) > 0



# Largest number of total copies (purchase + mirrors) that the cascade can absorb, or 0 if
# even the bare purchase cannot fit. Mirrors are capped to this, exactly as the ITEM path
# already caps duplication with min(value, remaining_item_count - 1): taking every mirror is
# not always better. Owning 1x Stick T1 on a full inventory, a normal character can buy a
# Stick T1 and merge to T2, but forcing two mirrored copies leaves 1x T1 + 1x T2 and does not
# fit - so the Mime would be unable to make a purchase anyone else could. He takes as many
# mirrors as fit and no more.
func mime_max_copies_that_fit(shop_weapon: WeaponData, player_index: int) -> int:
	var mirrors: = 0
	for dup_effect in get_player_effect(Keys.duplicate_item_hash, player_index):
		mirrors += int(dup_effect[1])
	for copies in range(mirrors + 1, 0, -1):
		if _mime_copies_fit(shop_weapon, player_index, copies):
			return copies
	return 0



func _mime_copies_fit(shop_weapon: WeaponData, player_index: int, copies: int) -> bool:
	var effects: = get_player_effects(player_index)
	var slot_max: int = int(effects[Keys.weapon_slot_hash])
	var owned: = get_player_weapons_ref(player_index)
	var total: int = owned.size() + copies
	# only the bought weapon's own line can merge; everything else is immovable ballast
	var line: = {}
	for weapon in owned:
		if weapon.weapon_id == shop_weapon.weapon_id:
			line[weapon.tier] = int(line.get(weapon.tier, 0)) + 1
	line[shop_weapon.tier] = int(line.get(shop_weapon.tier, 0)) + copies
	# The real merge ceiling: a weapon can only combine while it HAS an upgrade to become.
	# Walk the shop weapon's upgrades_into chain to find the top tier of this line, and cap
	# that by the run's max_weapon_tier. WITHOUT this the loop ran to max_weapon_tier, which
	# DEFAULTS TO 99 - so it merged T4 pairs into an imaginary T5, T6, ... concluded that any
	# number of copies eventually fits, and offered "x62" on a full inventory. Buying that
	# then added 62 weapons the real cascade could not absorb.
	var chain_top: int = shop_weapon.tier
	var chain_walk = shop_weapon
	while chain_walk != null and chain_walk.upgrades_into != null:
		chain_walk = chain_walk.upgrades_into
		chain_top = chain_walk.tier
	var merge_ceiling: int = int(min(chain_top, int(effects[Keys.max_weapon_tier_hash])))
	var guard: = 0
	while total > slot_max:
		guard += 1
		if guard > 64:
			return false
		var merged: = false
		for tier in range(0, merge_ceiling):
			if int(line.get(tier, 0)) >= 2:
				line[tier] = int(line[tier]) - 2
				line[tier + 1] = int(line.get(tier + 1, 0)) + 1
				total -= 1
				merged = true
				break
		if not merged:
			return false
	return true







# Gourmet DLC - The Special (character #18): every wave rolls random modifiers.
# Gourmet ecosystem - game modes (GameModes.REGISTRY ids per player)
func is_game_mode_active(mode_id: String, player_index: int) -> bool:
	if player_index < 0 or player_index >= players_data.size():
		return false
	return players_data[player_index].game_mode_ids.has(mode_id)



# The Wildcard's per-wave modifier lifecycle (roll/preview/apply/teardown) runs
# for The Wildcard himself AND for any player running the "Wildcard Rules" game
# mode - every lifecycle gate reads THIS, never is_special directly.
func has_wildcard_flow(player_index: int) -> bool:
	return is_special(player_index) or is_game_mode_active("wildcard_rules", player_index)



func is_special(player_index: int) -> bool:
	var character = get_player_character(player_index)
	return character != null and character.my_id == "character_special"



# Gourmet DLC - The Freeloader (character #16). Single gate for his whole kit: 8 shop
# items / 8 upgrades, everything free, one purchase per shop, no reroll, no lock, no
# crate items, no gold economy, flat 25% curse roll. Every other rule checks this.
func is_freeloader(player_index: int) -> bool:
	var character = get_player_character(player_index)
	return character != null and character.my_id == "character_freeloader"



# True when ANY player in the run is the Freeloader. Needed by the few hooks that have
# no player_index in scope (the gold gate runs per-player, but the shop-width helper is
# asked for a layout before player context exists in coop).
func has_freeloader() -> bool:
	for i in get_player_count():
		if is_freeloader(i):
			return true
	return false



# Gourmet DLC - The P2W (chest/lootbox character). Single gate for the whole kit.
func is_p2w(player_index: int) -> bool:
	var character = get_player_character(player_index)
	return character != null and character.my_id == "character_p2w"



# Session-local uid so armed shop cards can name their pending entry without
# index-shift bugs when another chest opens first. NOT serialized: a reload
# flushes all pending chests at shop entry, so uids never need to survive one.
var _p2w_next_uid: int = 0



# True when ANY player in the run is the P2W (crates become lootboxes run-wide).
func has_p2w() -> bool:
	return first_p2w_index() != - 1



func first_p2w_index() -> int:
	for i in get_player_count():
		if is_p2w(i):
			return i
	return - 1



# Pure resolve: id -> data, curse applied (random boost rolled HERE, once),
# P2W retier applied. No queue changes, no counters.
func _p2w_resolve_pure(entry: Dictionary, player_index: int) -> ItemParentData:
	var data: ItemParentData = null
	if entry.kind == "weapon":
		data = ItemService.get_element_safe(ItemService.weapons, entry.id)
	else:
		data = ItemService.get_element_safe(ItemService.items, entry.id)
	if data != null:
		data = _p2w_curse_drop(data, entry, player_index)
		if is_p2w(player_index):
			data = ItemService.p2w_retier_item(data)
	return data



# One instance per pending chest: the reel DISPLAYS this exact object and the
# claim GRANTS it, so the card can never disagree with the inventory (the curse
# boost is random - resolving twice showed base stats on the card while the
# granted item was boosted). Session-local; a reload just re-resolves.
var _p2w_drop_cache: = {}



func p2w_resolve_uid(player_index: int, uid: int) -> ItemParentData:
	if _p2w_drop_cache.has(uid):
		return _p2w_drop_cache[uid]
	var entry: Dictionary = p2w_peek_pending(player_index, uid)
	if entry.empty():
		return null
	var data: ItemParentData = _p2w_resolve_pure(entry, player_index)
	_p2w_drop_cache[uid] = data
	return data



# Wave-end path (no pending queue): resolve once at display time and count.
func p2w_resolve_entry(entry: Dictionary, player_index: int) -> ItemParentData:
	var data: ItemParentData = _p2w_resolve_pure(entry, player_index)
	if data != null and is_p2w(player_index):
		add_tracked_value(player_index, Keys.generate_hash("character_p2w"), 1)
	return data



# Buying a chest: roll the curse AND the contents NOW (CSGO decides at purchase,
# reveals at open), store serialized so a save/quit can never eat a paid chest.
# Returns the pending entry (uid/cursed) for the shop UI to arm its card with.
func p2w_arm_chest(player_index: int, rung: int, chest_cursed: bool = false) -> Dictionary:
	# cursed state comes from the CARD (chests curse via the vanilla shop roll,
	# lock-curse pity included); this only records it into the pending entry
	var drop: Dictionary = ItemService.p2w_roll_chest_drop(rung, player_index, chest_cursed)
	drop["rung"] = rung
	drop["cursed"] = chest_cursed
	drop["uid"] = _p2w_next_uid
	_p2w_next_uid += 1
	players_data[player_index].p2w_pending.push_back(drop)
	return drop



# Read-only look at a pending chest (the reel needs rung/drop/curse to stage the
# ceremony BEFORE the grant happens).
func p2w_peek_pending(player_index: int, uid: int) -> Dictionary:
	for entry in players_data[player_index].p2w_pending:
		if int(entry.get("uid", - 1)) == uid:
			return entry
	return {}



# Claim a pending drop for the SHOP path: remove + resolve + curse + count, but
# do NOT grant - base_shop routes the grant through its own buy pipeline so the
# gear-container UI updates (granting from here left the item invisible in-shop).
func p2w_claim_drop(player_index: int, uid: int) -> ItemParentData:
	var pending: Array = players_data[player_index].p2w_pending
	for i in pending.size():
		if int(pending[i].get("uid", - 1)) == uid:
			var entry: Dictionary = pending[i]
			# grant the SAME instance the reel displayed (cache), resolving
			# fresh only when no display happened (flush, coop)
			var claim_data: ItemParentData = _p2w_drop_cache.get(uid)
			if claim_data == null:
				claim_data = _p2w_resolve_pure(entry, player_index)
			var _erased = _p2w_drop_cache.erase(uid)
			pending.remove(i)
			add_tracked_value(player_index, Keys.generate_hash("character_p2w"), 1)
			return claim_data
	return null



func p2w_open_chest_uid(player_index: int, uid: int) -> ItemParentData:
	var pending: Array = players_data[player_index].p2w_pending
	for i in pending.size():
		if int(pending[i].get("uid", - 1)) == uid:
			return p2w_open_chest(player_index, i)
	return null



# Opening a pending chest: resolve the pre-rolled drop, curse it if the roll said
# so (Abyssal machinery; quietly does nothing without the DLC), grant it, count it.
func p2w_open_chest(player_index: int, pending_index: int) -> ItemParentData:
	var pending: Array = players_data[player_index].p2w_pending
	if pending_index < 0 or pending_index >= pending.size():
		return null
	var entry: Dictionary = pending[pending_index]
	pending.remove(pending_index)
	var _stale = _p2w_drop_cache.erase(int(entry.get("uid", - 1)))
	var granted: ItemParentData = null
	if entry.kind == "weapon":
		var weapon_data = ItemService.get_element_safe(ItemService.weapons, entry.id)
		if weapon_data != null:
			granted = _p2w_curse_drop(weapon_data, entry, player_index)
			# a full inventory converts the weapon into its shop value in materials
			# rather than dropping nothing (chest can roll while slots are full)
			if get_player_weapons_ref(player_index).size() < int(get_player_effect(Keys.weapon_slot_hash, player_index)):
				add_weapon(granted, player_index)
			else:
				add_gold(granted.value, player_index)
	else:
		var item_data = ItemService.get_element_safe(ItemService.items, entry.id)
		if item_data != null:
			granted = _p2w_curse_drop(item_data, entry, player_index)
			if is_p2w(player_index):
				granted = ItemService.p2w_retier_item(granted)
			add_item(granted, player_index)
	add_tracked_value(player_index, Keys.generate_hash("character_p2w"), 1)
	return granted



func _p2w_curse_drop(data: ItemParentData, entry: Dictionary, player_index: int) -> ItemParentData:
	if not entry.get("item_cursed", false):
		return data
	for dlc_id in enabled_dlcs:
		var dlc_data = ProgressData.get_dlc_data(dlc_id)
		if dlc_data != null and dlc_data.has_method("curse_item"):
			return dlc_data.curse_item(data, player_index)
	return data



# Safety net: any chest still unopened when the shop closes (or a run resumes
# outside a shop) grants silently - paid content is never lost.
func p2w_flush_pending(player_index: int) -> void :
	while players_data[player_index].p2w_pending.size() > 0:
		p2w_open_chest(player_index, 0)



# Gourmet DLC - run-level check for UI that has no player_index to work with
# (weapon name suffixes in particular). The extended tier ladder is a property of
# the run's weapon pool, so if any player is the Blacksmith the 8-step naming applies.
# The 8-step ladder is a property of any run whose content uses it: the
# Blacksmith (forging) or the P2W (chest weapon drops).
# Gourmet DLC - PER-PLAYER ladder check. any_player_uses_tier_ladder below answers "does this
# RUN use the ladder", which is the wrong question for a weapon card: in coop it renamed every
# other player's weapons too. Card naming asks this one, keyed on the card's owner.
func uses_tier_ladder(player_index: int) -> bool:
	return is_blacksmith(player_index) or is_p2w(player_index)



func any_player_uses_tier_ladder() -> bool:
	for i in get_player_count():
		if is_blacksmith(i) or is_p2w(i):
			return true
	return false



func any_player_is_blacksmith() -> bool:
	for i in get_player_count():
		if is_blacksmith(i):
			return true
	return false



# Gourmet DLC - The Debtor (character_test_debt). No money economy: pickups give only XP and
# repay debt 1:1; buying goes on unlimited credit; debt takes +10% interest each wave. Enemy
# scaling from debt is GLOBAL (see get_total_debt); every other rule is gated on this.
func is_debtor(player_index: int) -> bool:
	var character = get_player_character(player_index)
	return character != null and character.my_id == "character_test_debt"



# Total outstanding debt across all active players. Enemies scale off this (+1% HP & damage per
# 20 debt) - a GLOBAL rule, so anyone carrying debt makes the arena harder, not just the Debtor.
func get_total_debt() -> int:
	var total: = 0
	for i in get_player_count():
		total += players_data[i].debt
	return total



# Gourmet DLC - debt makes every enemy tougher: +1% Health and Damage per DEBT_PER_PERCENT
# debt carried by any player. Consumed in EntityService.get_final_enemy_health / _damage, which
# is the ONLY place every enemy stat path goes through - it used to live in enemy.init, where
# reset_health_stat / reset_damage_stat (elites, bosses, respawns, the lungs) recomputed from
# base stats and silently threw the scaling away.
const DEBT_PER_PERCENT: = 5



func get_debt_enemy_factor() -> float:
	return 1.0 + (get_total_debt() / (DEBT_PER_PERCENT * 100.0))



func get_debt_enemy_percent() -> int:
	return int(get_total_debt() / DEBT_PER_PERCENT)



# Gourmet DLC - The Debtor's card trackers.
#   [0] the enemy buff his debt is producing RIGHT NOW - SET, not accumulated, because it is a
#       live reading of the current debt rather than a running total like every other tracker.
#   [1] total debt repaid this run - a normal accumulator, added in add_gold.
# Writes straight into the dict instead of using set_tracked_value: that helper bails when the
# key is absent, and a run RESTORED FROM A SAVE carries the tracked-effects dict that was
# serialised with it, so a key added to init_tracked_items later simply is not there. Without
# this the card line silently never appears in any run started before the key existed.
# Signal-driven safety net (see _ready). Deliberately ignores both arguments: the tracker is
# derived from total debt, not from the gold value that happened to change.
func _on_gold_changed_refresh_debt(_new_value, _player_index) -> void :
	refresh_debt_tracker()



func refresh_debt_tracker(repaid: int = 0) -> void :
	var debtor_hash: int = Keys.generate_hash("character_test_debt")
	var buff: int = get_debt_enemy_percent()
	for i in get_player_count():
		if not is_debtor(i):
			continue
		var tracked: Dictionary = tracked_item_effects[i]
		if not (tracked.get(debtor_hash) is Array):
			tracked[debtor_hash] = [0, 0]
		tracked[debtor_hash][0] = buff
		if repaid > 0:
			tracked[debtor_hash][1] += repaid



# Gourmet DLC - Debtor: debt compounds +10% at the end of every cleared wave (called from
# main.clean_up_room). Only the Debtor accrues interest.
func apply_debt_interest() -> void :
	for i in get_player_count():
		if is_debtor(i) and players_data[i].debt > 0:
			players_data[i].debt = int(ceil(players_data[i].debt * 1.05))
			refresh_debt_tracker()
			emit_signal("gold_changed", players_data[i].gold, i)



# The weapon currently armed as the first half of a forge. Self-heals if that weapon
# has since left the inventory (recycled, forged away), so it can never dangle.
func get_forge_pick(player_index: int) -> WeaponData:
	var pick = _forge_picks.get(player_index)
	if pick != null and not (pick in _forge_weapons_for(player_index)):
		_forge_picks.erase(player_index)
		return null
	return pick



func set_forge_pick(player_index: int, weapon_data: WeaponData) -> void:
	if weapon_data == null:
		_forge_picks.erase(player_index)
	else:
		_forge_picks[player_index] = weapon_data



func clear_forge_pick(player_index: int) -> void:
	_forge_picks.erase(player_index)



# A legal Blacksmith pair: two DIFFERENT owned weapons of the same tier that share at
# least one class, where an unlocked next-tier weapon exists in that shared class.
# Identical duplicates qualify too (they share every class) - the decided design.
func is_valid_forge_pair(weapon_a: WeaponData, weapon_b: WeaponData, player_index: int) -> bool:
	if weapon_a == null or weapon_b == null or weapon_a == weapon_b:
		return false
	if weapon_a.tier != weapon_b.tier:
		return false
	# Gourmet DLC - the old "tier >= max_weapon_tier" gate is gone. max_weapon_tier is the
	# VANILLA ceiling (Tier.LEGENDARY), so it blocked every forge at ladder step 6 and made
	# steps 7 and 8 reachable only via the Anvil. The ladder is the authority now, and
	# get_forge_target_tier handles the top of it.
	var shared_sets: = []
	for set_a in weapon_a.sets:
		for set_b in weapon_b.sets:
			if set_a.my_id == set_b.my_id:
				shared_sets.push_back(set_a)
	if shared_sets.empty():
		return false
	return not get_blacksmith_forge_pool(get_forge_target_tier(weapon_a.tier, player_index), shared_sets).empty()



# Gourmet DLC - what a forge produces from two weapons of `tier`: one ladder step up,
# or - once already at the top of the ladder - another weapon of the SAME tier. That
# makes two max-tier weapons fuse into a single different max-tier one instead of being
# unforgeable dead weight. Raw tier + 1 must never be used: it lands on DANGER_4.
func get_forge_target_tier(tier: int, player_index: int) -> int:
	var next_tier: int = ItemService.get_next_tier(tier, player_index)
	return tier if next_tier == - 1 else next_tier



# Does this weapon have at least one legal forge partner in the inventory?
func has_forge_partner(weapon_data: WeaponData, player_index: int) -> bool:
	for other_weapon in _forge_weapons_for(player_index):
		if is_valid_forge_pair(weapon_data, other_weapon, player_index):
			return true
	return false



func can_combine(weapon_data: WeaponData, player_index: int) -> bool:
	# Gourmet DLC - Blacksmith: no vanilla auto-merge. You arm one weapon, then pick a
	# legal partner; the forge button drives that two-step flow, so an illegal pair
	# simply never shows a button (the game refuses impossible merges by construction).
	if is_blacksmith(player_index):
		var pick = get_forge_pick(player_index)
		if pick == null:
			return has_forge_partner(weapon_data, player_index)
		elif pick == weapon_data:
			return true  # armed weapon: the button cancels the selection
		else:
			return is_valid_forge_pair(pick, weapon_data, player_index)
	var nb_duplicates = 0
	var weapons: = get_player_weapons_ref(player_index)
	for weapon in weapons:
		if weapon.my_id == weapon_data.my_id:
			nb_duplicates += 1
	var max_weapon_tier = get_player_effect(Keys.max_weapon_tier_hash, player_index)
	# Gourmet DLC - "can this merge?" follows the player's ladder, so the Blacksmith
	# can still combine at vanilla T4 (-> pink) and stops only at gold.
	if nb_duplicates >= 2 and ItemService.can_upgrade_further(weapon_data, player_index) and weapon_data.tier < max_weapon_tier:
		return true
	return false







# forge pool: UNLOCKED weapons of the target tier carrying any of the given classes
func get_blacksmith_forge_pool(target_tier: int, class_sets: Array) -> Array:
	var pool: = []
	for weapon in ItemService.weapons:
		if weapon.tier != target_tier:
			continue
		if not ProgressData.weapons_unlocked.has(weapon.weapon_id_hash):
			continue
		var shares: = false
		for weapon_set in weapon.sets:
			for wanted_set in class_sets:
				if weapon_set.my_id == wanted_set.my_id:
					shares = true
		if shares:
			pool.push_back(weapon)
	return pool



func remove_currency(value: int, player_index: int) -> void :
	var effects: = get_player_effects(player_index)
	if effects[Keys.hp_shop_hash]:
		remove_stat(Keys.stat_max_hp_hash, value, player_index)
		return
	# Gourmet DLC - Credit Card: a shop purchase may overspend the wallet, and the shortfall
	# becomes debt (1 material overspent = 1 debt point = 2 materials to repay). The affordability
	# gate (shop_items_container) already confirmed the overspend fits inside available credit, so
	# this only ever runs for a card holder buying beyond their materials. The card tracks the
	# debt it takes on. Rerolls and non-shop costs still use remove_gold and cannot go negative.
	var player_data = players_data[player_index]
	if value > player_data.gold and get_available_credit(player_index) > 0:
		var overspend: int = value - player_data.gold
		overspend = int(min(overspend, get_available_credit(player_index)))
		remove_gold(player_data.gold, player_index)  # empty the wallet
		if overspend > 0:
			player_data.debt += overspend
			add_tracked_value(player_index, Keys.generate_hash("item_credit_card"), overspend)
			refresh_debt_tracker()
			emit_signal("gold_changed", player_data.gold, player_index)
		return
	remove_gold(value, player_index)





func get_nb_food_items(player_index: int) -> int:
	var result: = 0
	for item in get_player_items_ref(player_index):
		if item.tags.has("food"):
			result += 1
	return result



# Gourmet DLC - Minimalist tier ladder: items grant All Stats by tier
# (T0 +2, T1 +4, T2 +6, T3 +8 -> units 1/2/3/4 x scaler value 2). While all 6
# slots hold max-tier items, everything gives +12 instead (units x 1.5).
# Duck-typed on purpose: no item class references from a singleton the item
# chain feeds back into (cyclic-dependency law).
func get_nb_minimalist_items(player_index: int) -> float:
	var nb_items: = 0
	var units: = 0
	var all_max_tier: = true
	for item in get_player_items_ref(player_index):
		if item.my_id.begins_with("item_"):
			nb_items += 1
			units += item.tier + 1
			if item.tier < 3:
				all_max_tier = false
	if nb_items == 6 and all_max_tier:
		return units * 1.5
	return float(units)



# Gourmet DLC - Juggler: weapons attack one at a time, cycling left to right
var _juggler_pos: = {}


func is_juggler_cycling(player_index: int) -> bool:
	var character = get_player_character(player_index)
	return character != null and character.my_id == "character_juggler"



func get_juggler_active_pos(player_index: int) -> int:
	var nb = get_player_weapons_ref(player_index).size()
	if nb <= 0:
		return - 1
	return _juggler_pos.get(player_index, 0) % nb



func advance_juggler(player_index: int) -> void :
	_juggler_pos[player_index] = get_juggler_active_pos(player_index) + 1



# Gourmet DLC - the effective per-run cap on an item, and the single source of truth for
# it: shop gating, the loot pool and the "LIMITED (n/max)" card label all go through here.
# Picky Eater: only one food spawner TYPE ever fires for him, so he is allowed twice as
# many copies of that type (a limit-3 spawner becomes limit 6). Keyed on the "spawner"
# tag that build_food_system.py stamps on every spawner item, so non-spawner food items
# (Soul Food, Set Menu, Wine Cellar and the other unique diamonds) keep their own cap.
func get_item_max_nb(item_data, player_index: int) -> int:
	if item_data.max_nb <= 0:
		return item_data.max_nb
	if item_data.tags.has("spawner"):
		var picky_character = get_player_character(player_index)
		if picky_character != null and picky_character.my_id == "character_picky_eater":
			return item_data.max_nb * 2
	return item_data.max_nb





func get_remaining_max_nb_item(item_data: ItemData, player_index: int) -> int:
	if item_data.max_nb == - 1:
		return Utils.LARGE_NUMBER
	var existing_item_count: = get_nb_item(item_data.my_id_hash, player_index)
	return max(0, get_item_max_nb(item_data, player_index) - existing_item_count) as int



func get_state() -> Dictionary:
	var players_data_copy: = []
	for player_data in players_data:
		players_data_copy.push_back(player_data.duplicate())
	return {
		"players_data": players_data_copy, 

		"enemy_scaling": current_run_accessibility_settings.duplicate(), 
		"constant_projectile": constant_projectile, 
		"nb_of_waves": nb_of_waves, 
		"current_zone": current_zone, 
		"current_wave": current_wave, 
		"current_difficulty": current_difficulty, 
		"bonus_gold": bonus_gold, 
		"total_bonus_gold": total_bonus_gold, 
		"retries": retries, 
		"elites_spawn": elites_spawn.duplicate(), 
		"bosses_spawn": bosses_spawn.duplicate(), 
		"events_spawn": events_spawn.duplicate(), 
		"events_fog_of_war": events_fog_of_war.duplicate(), 
		"events_bullet_hell": events_bullet_hell.duplicate(), 
		"shop_effects_checked": shop_effects_checked, 
		"elites_killed_this_run": elites_killed_this_run.duplicate(), 
		"bosses_killed_this_run": bosses_killed_this_run.duplicate(), 
		"loot_aliens_killed_this_run": loot_aliens_killed_this_run, 

		"challenges_completed_this_run": challenges_completed_this_run.duplicate(), 
		"locked_shop_items": locked_shop_items.duplicate(true), 
		"current_background": current_background, 

		"max_endless_wave_record_beaten": max_endless_wave_record_beaten, 
		"is_endless_run": is_endless_run, 
		"is_coop_run": is_coop_run, 
		"play_mode": PlayMode.SOLO, 
		"is_streamplay_run": false, 
		"enabled_dlcs": enabled_dlcs, 
		"enabled_packs": enabled_packs, 

		"tracked_item_effects": tracked_item_effects.duplicate(true)
	}



func resume_from_state(state: Dictionary) -> void :
	ProgressData.update_dlc_resources_based_on_run_state(state)
	var players_data_copy: = []
	for player_data in state.players_data:
		players_data_copy.push_back(player_data.duplicate())
	players_data = players_data_copy
	current_run_accessibility_settings = state.enemy_scaling.duplicate()
	if state.has("constant_projectile"):
		constant_projectile = int(state.constant_projectile)
	nb_of_waves = state.nb_of_waves
	retries = state.retries
	current_zone = state.current_zone
	current_wave = state.current_wave
	current_difficulty = state.current_difficulty
	bonus_gold = state.bonus_gold
	total_bonus_gold = state.total_bonus_gold if "total_bonus_gold" in state else 0
	elites_spawn = state.elites_spawn.duplicate()
	for e in elites_spawn:
		match typeof(e[2]):
			TYPE_STRING:
				e[2] = Keys.generate_hash((e[2]))
			TYPE_REAL:
				e[2] = int(e[2])
	bosses_spawn = state.bosses_spawn.duplicate()
	if state.has("events_spawn"):
		events_spawn = state.events_spawn.duplicate()
	if state.has("events_fog_of_war"):
		events_fog_of_war = state.events_fog_of_war.duplicate()
	if state.has("events_bullet_hell"):
		events_bullet_hell = state.events_bullet_hell.duplicate()
	shop_effects_checked = state.shop_effects_checked
	elites_killed_this_run = state.elites_killed_this_run
	bosses_killed_this_run = state.bosses_killed_this_run
	loot_aliens_killed_this_run = state.loot_aliens_killed_this_run
	for challenge in state.challenges_completed_this_run:
		if not challenges_completed_this_run.has(challenge):
			challenges_completed_this_run.append(challenge)
	locked_shop_items = state.locked_shop_items.duplicate(true)
	current_background = state.current_background
	max_endless_wave_record_beaten = state.max_endless_wave_record_beaten
	is_endless_run = state.is_endless_run
	set_coop_run(state.is_coop_run)
	play_mode = RunData.PlayMode.COOP if state.is_coop_run else state.get("play_mode", RunData.PlayMode.SOLO)
	is_streamplay_run = play_mode == RunData.PlayMode.STREAMPLAY_LOCAL or play_mode == RunData.PlayMode.STREAMPLAY_INTERNET
	enabled_dlcs = state.enabled_dlcs
	enabled_packs = state.get("enabled_packs", [])
	tracked_item_effects = Utils.convert_to_hash_array(state.tracked_item_effects.duplicate())
	ZoneService.current_zone = ZoneService.get_zone_data(current_zone).duplicate()
	LinkedStats.reset()



func get_scaling_bonus(value: int, stat_scaled: String, nb_stat_scaled: int, perm_stats_only: bool, player_index: int) -> int:
	assert ( not stat_scaled.is_valid_integer())
	var stat_scaled_hash: int = Keys.generate_hash(stat_scaled)
	var actual_nb_scaled: = 0.0
	if stat_scaled_hash == Keys.materials_hash:
		actual_nb_scaled = get_player_gold(player_index)
	elif stat_scaled_hash == Keys.structure_hash:
		actual_nb_scaled = get_nb_structures(player_index)
	elif stat_scaled_hash == Keys.pet_hash:
		actual_nb_scaled = get_nb_pets(player_index)
	elif stat_scaled == "living_enemy":
		actual_nb_scaled = current_living_enemies
	elif stat_scaled_hash == Keys.burning_enemy_hash:
		actual_nb_scaled = current_burning_enemies
	elif stat_scaled_hash == Keys.different_item_hash:
		actual_nb_scaled = get_nb_different_items_of_tier( - 1, player_index)
	elif stat_scaled_hash == Keys.common_item_hash:
		actual_nb_scaled = get_nb_different_items_of_tier(Tier.COMMON, player_index)
	elif stat_scaled_hash == Keys.legendary_item_hash:
		actual_nb_scaled = get_nb_different_items_of_tier(Tier.LEGENDARY, player_index)
	elif stat_scaled_hash == Keys.duplicate_item_hash:
		actual_nb_scaled = get_duplicate_items_count(player_index)
	elif stat_scaled.begins_with("item_"):
		actual_nb_scaled = get_nb_item(stat_scaled_hash, player_index)
	elif stat_scaled_hash == Keys.living_tree_hash:
		actual_nb_scaled = current_living_trees
	elif stat_scaled_hash == Keys.percent_player_missing_health_hash:
		var current_health = get_player_current_health(player_index)
		var max_health = get_player_max_health(player_index)
		actual_nb_scaled = WeaponService.apply_inverted_health_bonus(1, 1, current_health, max_health)
	elif stat_scaled_hash == Keys.free_weapon_slots_hash:
		actual_nb_scaled = get_free_weapon_slots(player_index)
	elif stat_scaled_hash == Keys.food_item_hash:
		actual_nb_scaled = get_nb_food_items(player_index)
	elif stat_scaled_hash == Keys.minimalist_item_hash:
		actual_nb_scaled = get_nb_minimalist_items(player_index)
	elif perm_stats_only:
		actual_nb_scaled = get_stat(stat_scaled_hash, player_index)
	else:
		actual_nb_scaled = get_stat(stat_scaled_hash, player_index) + TempStats.get_stat(stat_scaled_hash, player_index)
	return int(value * (actual_nb_scaled / nb_stat_scaled))

func _init() -> void :
	_gourmet_merge_init_tracked_items()

func _gourmet_merge_init_tracked_items() -> void :
	init_tracked_items[Keys.generate_hash("character_gourmet")] = [0, 0]
	init_tracked_items[Keys.generate_hash("character_snail")] = [0, 0]
	init_tracked_items[Keys.generate_hash("character_girly")] = 0
	init_tracked_items[Keys.generate_hash("character_p2w")] = 0
	init_tracked_items[Keys.generate_hash("weapon_frying_pan")] = 0
	init_tracked_items[Keys.generate_hash("item_doggy_bag")] = 0
	init_tracked_items[Keys.generate_hash("item_farmers_market")] = 0
	init_tracked_items[Keys.generate_hash("item_compost_bin")] = 0
	init_tracked_items[Keys.generate_hash("item_loyalty_card")] = 0
	init_tracked_items[Keys.generate_hash("item_credit_card")] = 0
	init_tracked_items[Keys.generate_hash("character_test_debt")] = [0, 0]
	init_tracked_items[Keys.generate_hash("item_soul_food")] = [0, 0]
	init_tracked_items[Keys.generate_hash("item_overtime_pay")] = 0
	init_tracked_items[Keys.generate_hash("item_second_mortgage")] = 0
	init_tracked_items[Keys.generate_hash("item_snack_break")] = 0
	init_tracked_items[Keys.generate_hash("character_butcher")] = [0, 0]
	init_tracked_items[Keys.generate_hash("character_dishwasher")] = 0
	init_tracked_items[Keys.generate_hash("character_zombie")] = 0
	init_tracked_items[Keys.generate_hash("item_food_fight")] = 0
	init_tracked_items[Keys.generate_hash("item_spyglass")] = 0
	init_tracked_items[Keys.generate_hash("character_minimalist")] = 0
	init_tracked_items[Keys.generate_hash("character_comp_eater")] = 0
	init_tracked_items[Keys.generate_hash("character_ruminant")] = 0
	init_tracked_items[Keys.generate_hash("character_blacksmith")] = 0
	init_tracked_items[Keys.generate_hash("character_mime")] = 0
	init_tracked_items[Keys.generate_hash("item_vampire_fang")] = 0
	init_tracked_items[Keys.generate_hash("item_buffet_insurance")] = 0
	init_tracked_items[Keys.generate_hash("item_caltrops")] = 0
	init_tracked_items[Keys.generate_hash("item_grease_fire")] = 0
	init_tracked_items[Keys.generate_hash("item_static_cling")] = 0
	init_tracked_items[Keys.generate_hash("item_echo_chamber")] = 0
	init_tracked_items[Keys.generate_hash("item_second_helping")] = 0
	init_tracked_items[Keys.generate_hash("item_nine_lives")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_cake_slice")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_cheese_cube")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_chili_pepper")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_escargot")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_espresso")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_fried_rice")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_fries")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_fruit_salad")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_golden_apple")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_honey_drop")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_ice_cream")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_leftovers")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_mint")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_mystery_meat")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_pizza_slice")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_popcorn")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_protein_shake")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_steak")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_sushi_roll")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_warm_cookie")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_ribs")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_chili_dog")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_gumball")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_bloody_mary")] = 0
	init_tracked_items[Keys.generate_hash("consumable_food_fried_egg")] = 0
	init_tracked_items[Keys.generate_hash("item_wine_cellar")] = 0
	init_tracked_items[Keys.generate_hash("item_delivery_drone")] = 0
