# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://singletons/text.gd"

func _init() -> void :
	_gourmet_merge_keys_needing_operator()

func _gourmet_merge_keys_needing_operator() -> void :
	keys_needing_operator["stat_curse"] = [0]
	keys_needing_operator["stat_appetite"] = [0]
	keys_needing_operator["food_items_price"] = [0]
	keys_needing_operator["spawner_items_price"] = [0]
	keys_needing_operator["enemy_attack_speed"] = [0]
	keys_needing_operator["gain_stat_percent_damage"] = [0]
	keys_needing_operator["gain_stat_melee_damage"] = [0]
	keys_needing_operator["gain_stat_attack_speed"] = [0]
	keys_needing_operator["gain_stat_speed"] = [0]
	keys_needing_operator["gain_stat_ranged_damage"] = [0]
	keys_needing_operator["gain_stat_luck"] = [0]
	keys_needing_operator["gain_stat_dodge"] = [0]
	keys_needing_operator["gain_stat_max_hp"] = [0]
	keys_needing_operator["gain_stat_hp_regeneration"] = [0]
	keys_needing_operator["gain_stat_elemental_damage"] = [0]
	keys_needing_operator["gain_stat_armor"] = [0]
	keys_needing_operator["gain_stat_harvesting"] = [0]
	keys_needing_operator["gain_stat_appetite"] = [0]
	keys_needing_operator["gain_xp_gain"] = [0]
