# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://singletons/utils.gd"



func get_capped_stat(stat_hsh: int, player_index) -> float:
	var stat: = get_stat(stat_hsh, player_index)
	var cap_key: int
	match stat_hsh:
		Keys.stat_max_hp_hash:
			cap_key = Keys.hp_cap_hash
		Keys.stat_speed_hash:
			cap_key = Keys.speed_cap_hash
		Keys.stat_dodge_hash:
			cap_key = Keys.dodge_cap_hash
		Keys.stat_curse_hash:
			cap_key = Keys.curse_cap_hash
		Keys.stat_crit_chance_hash:
			cap_key = Keys.crit_chance_cap_hash
		_:
			printerr("stat %s has no associated cap" % Keys.hash_to_string[stat_hsh])
	var cap = RunData.get_player_effect(cap_key, player_index)
	# Gourmet DLC - Zombie: anything raising his 10% dodge cap is 50% less effective
	if stat_hsh == Keys.stat_dodge_hash:
		var zombie_char = RunData.get_player_character(player_index)
		if zombie_char != null and zombie_char.my_id == "character_zombie" and cap > 10:
			cap = 10 + (cap - 10) / 2.0
	return min(stat, cap)
