# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://singletons/weapon_service.gd"



func explode(effect: ExplodingEffect, args: WeaponServiceExplodeArgs) -> Node:
	var main: Main = Utils.get_scene_node()
	var instance = main.get_node_from_pool(effect.explosion_scene.get_instance_id(), main._explosions)
	if instance == null:
		instance = effect.explosion_scene.instance()
		main.add_explosion(instance)
	if main._is_fog_wave:
		main._fog_viewport._on_spawn_explosion(instance)
	instance.pool_id = effect.explosion_scene.get_instance_id()
	instance.player_index = args.from_player_index
	instance.global_position = args.pos
	instance.sound_db_mod = effect.sound_db_mod
	instance.set_damage_tracking_key(args.damage_tracking_key_hash)
	instance.set_damage(args)
	instance.set_smoke_amount(round(effect.scale * effect.base_smoke_amount))
	instance.set_area(effect.scale)
	if args.from != null:
		instance.set_from(args.from)
	instance.start_explosion()
	# Gourmet DLC - Popcorn Machine hook. Deliberately HERE and not in main.add_explosion:
	# this runs for every explosion (pooled instances never reach add_explosion) and
	# instance.player_index has been assigned by now. See main.on_explosion_spawned.
	main.on_explosion_spawned(instance.player_index)
	return instance
