# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://items/difficulties/difficulty_data.gd"



func get_name_text(_player_index: int = - 1) -> String:
	return Text.text(tr(name), [str(value)])
