# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://weapons/weapon.gd"

# Gourmet DLC - Juggler metronome: true while this weapon holds the juggle turn
# (edge flag so the 0.3s interval is assigned exactly once per turn)
var _juggler_turn_started: = false

# Gourmet DLC - Juggler combo: +8% damage for every weapon that already fired this cycle,
# so a 6-weapon loadout ends its cycle on a +40% hit and resets. Makes a wide loadout worth
# more than the metronome's flat fire rate suggests. The boosted stats object and its
# original damage are held so the next shoot() can put it back exactly.
const JUGGLER_COMBO_PER_WEAPON: = 0.08

var _juggler_boosted_stats = null

var _juggler_base_damage: = - 1



func init_stats(at_wave_begin: bool = true) -> void :
	var args: = WeaponServiceInitStatsArgs.new()
	args.sets = weapon_sets
	args.effects = effects
	if stats is RangedWeaponStats:
		current_stats = WeaponService.init_ranged_stats(stats, player_index, false, args)
		_stats_every_x_shots = WeaponService.init_stats_every_x_projectiles(stats, player_index, args)
		for x_shot_stats in _stats_every_x_shots.values():
			x_shot_stats.burning_data.from = self
	else:
		current_stats = WeaponService.init_melee_stats(stats, player_index, args)
	_hitbox.projectiles_on_hit = []
	var on_hit_args: = WeaponServiceInitStatsArgs.new()
	for effect in effects:
		if effect is ProjectilesOnHitEffect:
			var weapon_stats = WeaponService.init_ranged_stats(effect.weapon_stats, player_index, true, on_hit_args)
			_hitbox.projectiles_on_hit = [effect.value, weapon_stats, effect.auto_target_enemy]
	current_stats.burning_data.from = self
	var hitbox_args: = Hitbox.HitboxArgs.new().set_from_weapon_stats(current_stats)
	# Gourmet DLC - stats were just rebuilt, so any Juggler combo boost on the old object
	# is void; drop the restore bookkeeping rather than writing damage back onto stale stats
	_juggler_boosted_stats = null
	_juggler_base_damage = - 1
	_hitbox.effect_scale = current_stats.effect_scale
	_hitbox.set_damage(current_stats.damage, hitbox_args)
	_hitbox.speed_percent_modifier = current_stats.speed_percent_modifier
	_hitbox.effects = effects
	_hitbox.from = self
	if at_wave_begin:
		_current_cooldown = get_next_cooldown(at_wave_begin)
	reset_cooldown()
	_range_shape.shape.radius = current_stats.max_range + DETECTION_RANGE



func _physics_process(delta: float) -> void :
	if _manual_aim:
		if should_rotate_manual():
			if Utils.is_player_using_gamepad(player_index):
				rotation = _parent.gamepad_attack_vector.angle()
			else:
				rotation = (get_global_mouse_position() - global_position).angle()
	else:
		if _is_shooting:
			rotation = get_direction()
		else:
			rotation = get_direction_and_calculate_target()
	if not _is_shooting:
		var cooldown_tick: = 60 * delta
		# Gourmet DLC - Juggler metronome: the active weapon fires 0.3s after the
		# previous one (18 frames / (1 + Attack Speed/100)), whatever its own
		# cooldown; inactive weapons are frozen. Clamped to [3, 180] frames as a
		# safety net at extreme +/- Attack Speed. Card mirror: effect.gd
		# EFFECT_JUGGLER_TEMPO computes the same expression.
		if weapon_pos >= 0 and _parent != null and "player_index" in _parent and RunData.is_juggler_cycling(_parent.player_index):
			if RunData.get_juggler_active_pos(_parent.player_index) == weapon_pos:
				if not _juggler_turn_started:
					_juggler_turn_started = true
					var juggler_as: float = Utils.get_stat(Keys.stat_attack_speed_hash, _parent.player_index)
					_current_cooldown = clamp(18.0 / max(0.1, 1.0 + juggler_as / 100.0), 3.0, 180.0)
			else:
				_juggler_turn_started = false
				cooldown_tick = 0.0
		_current_cooldown = max(_current_cooldown - cooldown_tick, 0)
	if _current_cooldown <= 10 and sprite.texture == stats.custom_on_cooldown_sprite:
		update_sprite(_original_sprite)
	if should_shoot():
		_is_shooting = true
		call_deferred("deferred_shoot")



func should_shoot() -> bool:
	if _is_shooting:
		return false
	# Gourmet DLC - Wildcard (Front of House / Back of House): a banned weapon type does not
	# fire at all this wave. These keys previously only filtered the SHOP pool, so the two
	# modifiers shipped as no-ops; this is the read that makes their card text true. The
	# eligibility roll guarantees the player still owns the other type.
	if current_stats is MeleeWeaponStats:
		if RunData.get_player_effect(Keys.no_melee_weapons_hash, player_index) > 0:
			return false
	elif RunData.get_player_effect(Keys.no_ranged_weapons_hash, player_index) > 0:
		return false
	return (_current_cooldown <= 0
		and not _parent._panic_frozen  # Gourmet DLC - Girly can't shoot mid panic-teleport
		and (
			_parent._current_movement == Vector2.ZERO
			or
			RunData.get_player_effect(Keys.can_attack_while_moving_hash, player_index)

		)
		and 
		(
			(
				_current_target.size() > 0
				and is_instance_valid(_current_target[0])
				and Utils.is_between(_current_target[1], current_stats.min_range, current_stats.max_range + 50)
			)
			or (
				_manual_aim
				and not _parent.cleaning_up
			)
		)
	)





func shoot() -> void :
	# Gourmet DLC - Juggler combo: undo the previous shot's boost before anything reads
	# damage again. Restoring here rather than at the end of shoot() is deliberate: a melee
	# hitbox stays live for the whole swing, so an immediate restore would cancel the bonus
	# mid-animation. The stats object is remembered alongside the value because
	# _stats_every_x_shots can swap current_stats out from under us.
	if _juggler_boosted_stats != null:
		_juggler_boosted_stats.damage = _juggler_base_damage
		_juggler_boosted_stats = null
		_juggler_base_damage = - 1
	# Gourmet DLC - Juggler: firing passes the act to the next weapon. The edge
	# flag resets HERE (not just on the inactive branch) so a solo weapon that
	# hands the turn back to itself still re-arms the 0.3s metronome.
	var juggler_combo: = 0
	if weapon_pos >= 0 and _parent != null and "player_index" in _parent and RunData.is_juggler_cycling(_parent.player_index) and RunData.get_juggler_active_pos(_parent.player_index) == weapon_pos:
		_juggler_turn_started = false
		# The cycle runs left to right from position 0, so the active position IS the number
		# of weapons that already fired this cycle - the combo count needs no extra state.
		juggler_combo = weapon_pos
		RunData.advance_juggler(_parent.player_index)
	_nb_shots_taken += 1
	var original_stats: RangedWeaponStats
	for projectile_count in _stats_every_x_shots:
		if _nb_shots_taken % projectile_count == 0:
			original_stats = current_stats
			current_stats = _stats_every_x_shots[projectile_count]
	for effect in effects:
		if effect.key_hash == Keys.reload_turrets_on_shoot_hash:
			emit_signal("wanted_to_reset_turrets_cooldown")
	# Gourmet DLC - Juggler combo: applied after the _stats_every_x_shots swap so it
	# multiplies whichever stats this shot actually uses. Both paths need it - a projectile
	# reads current_stats.damage, a melee swing reads the hitbox. Card mirror: effect.gd
	# EFFECT_JUGGLER_COMBO. Cleared at the top of the next shoot().
	if juggler_combo > 0:
		_juggler_boosted_stats = current_stats
		_juggler_base_damage = current_stats.damage
		current_stats.damage = int(round(_juggler_base_damage * (1.0 + JUGGLER_COMBO_PER_WEAPON * juggler_combo)))
		_hitbox.set_damage(current_stats.damage, Hitbox.HitboxArgs.new().set_from_weapon_stats(current_stats))
	update_current_spread()
	update_knockback()
	if _manual_aim:
		_shooting_behavior.shoot(current_stats.max_range)
	else:
		if _current_target.size() == 0 or not is_instance_valid(_current_target[0]):
			_shooting_behavior.shoot(current_stats.max_range)
		else:
			_shooting_behavior.shoot(_current_target[1])
	_current_cooldown = get_next_cooldown()
	if stats.custom_on_cooldown_sprite != null and (is_big_reload_active() or current_stats.additional_cooldown_every_x_shots == - 1):
		update_sprite(stats.custom_on_cooldown_sprite)
	if original_stats:
		current_stats = original_stats









func on_weapon_hit_something(_thing_hit: Node, damage_dealt: int, hitbox: Hitbox) -> void :
	RunData.add_weapon_dmg_dealt(weapon_pos, damage_dealt, _parent.player_index)
	if hitbox == null:
		return
	var attack_id: = hitbox.player_attack_id
	if attack_id < 0:
		return
	var attack_hit_count = _hit_count_by_attack_id.get(attack_id, 0)
	attack_hit_count += 1
	_hit_count_by_attack_id[attack_id] = attack_hit_count
	if current_stats is MeleeWeaponStats:
		ChallengeService.try_complete_challenge(ChallengeService.chal_unstoppable_force_hash, attack_hit_count)
	var remove_until_attack_id: = attack_id - MAX_ATTACK_COUNT_HISTORY + 1
	for old_attack_id in range(_oldest_attack_id, remove_until_attack_id):
		var _erased = _hit_count_by_attack_id.erase(old_attack_id)
		_erased = _kill_count_by_attack_id.erase(old_attack_id)
	_oldest_attack_id = remove_until_attack_id
	assert (_hit_count_by_attack_id.size() <= MAX_ATTACK_COUNT_HISTORY)
	assert (_kill_count_by_attack_id.size() <= MAX_ATTACK_COUNT_HISTORY)
	for effect in effects:
		if effect.key_hash == Keys.break_on_hit_hash:
			if Utils.get_chance_success(effect.value / 100.0):
				emit_signal("wanted_to_break", self, effect.value2)
		# Gourmet DLC - on-hit food proc: value = tier's % chance; custom_key names the
		# food. Corn/Fish/Pizza/Sauce/Scoop/Spatula each drop their food where they hit.
		elif effect.custom_key.begins_with("food_drop:"):
			if Utils.get_chance_success(effect.value / 100.0) and is_instance_valid(_thing_hit):
				var fd_main = Utils.get_scene_node()
				if fd_main != null:
					var fd_food = ItemService.get_food_from_hash(Keys.generate_hash(effect.custom_key.substr(10)))
					if fd_food != null:
						fd_main.spawn_food(fd_food, _thing_hit.global_position, - 1.0, _parent.player_index)
