# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# GourmetCore extension of the vanilla file (full modified/new functions + new members)
extends "res://items/consumables/consumable.gd"



func _ready() -> void :
	._ready()
