# generated by asset-dev/gen_extensions.py - DO NOT EDIT
# HAND extension (no pristine baseline - Abyssal Terrors DLC pck is not in the reference);
# segments hand-listed in HAND_EXTENSIONS, emitted verbatim from game-src. Installed LATE
# by the progress_data extension, only when the DLC is mounted.
extends "res://dlcs/dlc_1/dlc_1_data.gd"





# Gourmet DLC - The Freeloader's flat, unmodifiable shop curse rate. Sits deliberately
# above max_curse_item_chance (0.15 in dlc_data.tres), which is the hard ceiling no other
# character can pass no matter how much Curse they stack.
const FREELOADER_CURSE_CHANCE: = 0.25



func update_item_effects(item_data: ItemParentData, player_index: int) -> ItemParentData:
	var curse_chance = max(0, Utils.get_max_capped_stat(Keys.stat_curse_hash, player_index)) as int
	var drop_chance: float = Utils.get_curse_factor(max(base_item_curse_chance * 100.0, curse_chance), max_curse_item_chance * 100.0) / 100.0
	# Gourmet DLC - flat 25% for the Freeloader, ignoring both his own stat_curse and the
	# game ceiling above. He still ACCUMULATES stat_curse from every cursed item he takes:
	# that is the entire cost of the character. Curse has three jobs (enemy curse chance,
	# shop curse chance, cursed drop chance) and for him the last two are locked or dead,
	# so it collapses into "how many enemies are cursed" - and cursed enemies compensate
	# in gold, which he cannot use.
	if RunData.is_freeloader(player_index):
		drop_chance = FREELOADER_CURSE_CHANCE
	return curse_item(item_data, player_index) if Utils.get_chance_success(drop_chance) else item_data
